{
    "items": [
        {
            "tags": [
                "c",
                "macos",
                "filesystems",
                "system-calls"
            ],
            "owner": {
                "reputation": 1690,
                "user_id": 4333809,
                "user_type": "registered",
                "accept_rate": 83,
                "profile_image": "https://www.gravatar.com/avatar/eb246fedefccc8b02a3efb989143d3b9?s=128&d=identicon&r=PG&f=1",
                "display_name": "Zohar81",
                "link": "https://stackoverflow.com/users/4333809/zohar81"
            },
            "is_answered": true,
            "view_count": 27,
            "accepted_answer_id": 49792623,
            "answer_count": 1,
            "score": 2,
            "last_activity_date": 1523524536,
            "creation_date": 1523518184,
            "last_edit_date": 1523522999,
            "question_id": 49790488,
            "body_markdown": "I&#39;d like to get the number of used inodes for specified volume using function API rather then using the output of `df` shell command. \r\n\r\nI&#39;ve looked at the man page of `getattrlist` and found the following attribute, but it may also refer to hard links, but they point to existing inodes, and I don&#39;t want to count them more than once. \r\n\r\n    ATTR_VOL_FILECOUNT        A u_int32_t containing the number of files on the volume.\r\n\r\nI also tried to run `dtruss df` and search for the exact sys call which retrieves this value, but I couldn&#39;t put my finger on it : \r\n\r\n    csops(0x872, 0x7, 0x7FFEEE4C8E80)\t\t = 0 0\r\n    sysctl([CTL_KERN, 14, 1, 2162, 0, 0] (4), 0x7FFEEE4C8FC8, 0x7FFEEE4C8FC0, 0x0, 0x0)\t\t = 0 0\r\n    csops(0x872, 0x7, 0x7FFEEE4C8770)\t\t = 0 0\r\n    getfsstat64(0x0, 0x0, 0x2)\t\t = 6 0\r\n    getfsstat64(0x7FFD41001600, 0x3B48, 0x2)\t\t = 6 0\r\n    getfsstat64(0x7FFD41001600, 0x3B48, 0x1)\t\t = 6 0\r\n    getrlimit(0x1008, 0x7FFEEE4C9EC0, 0x0)\t\t = 0 0\r\n    fstat64(0x1, 0x7FFEEE4C9ED8, 0x0)\t\t = 0 0\r\n    ioctl(0x1, 0x4004667A, 0x7FFEEE4C9F24)\t\t = 0 0  \r\n\r\nHere&#39;s `df` output (notice the iused field) \r\n\r\n    Filesystem    512-blocks      Used Available Capacity iused               ifree %iused  Mounted on\r\n    /dev/disk1s1   976695384 757288824 211770792    79% 2000778 9223372036852775029    0%   /\r\n\r\n\r\nAny ideas where can I find the source code of `df` or to other API for this task.\r\n\r\n\r\n\r\nthanks \r\n  ",
            "link": "https://stackoverflow.com/questions/49790488/macos-getting-number-of-used-inodes-in-volume-programmatically",
            "title": "macOS: Getting number of used inodes in volume programmatically",
            "body": "<p>I'd like to get the number of used inodes for specified volume using function API rather then using the output of <code>df</code> shell command. </p>\n\n<p>I've looked at the man page of <code>getattrlist</code> and found the following attribute, but it may also refer to hard links, but they point to existing inodes, and I don't want to count them more than once. </p>\n\n<pre><code>ATTR_VOL_FILECOUNT        A u_int32_t containing the number of files on the volume.\n</code></pre>\n\n<p>I also tried to run <code>dtruss df</code> and search for the exact sys call which retrieves this value, but I couldn't put my finger on it : </p>\n\n<pre><code>csops(0x872, 0x7, 0x7FFEEE4C8E80)        = 0 0\nsysctl([CTL_KERN, 14, 1, 2162, 0, 0] (4), 0x7FFEEE4C8FC8, 0x7FFEEE4C8FC0, 0x0, 0x0)      = 0 0\ncsops(0x872, 0x7, 0x7FFEEE4C8770)        = 0 0\ngetfsstat64(0x0, 0x0, 0x2)       = 6 0\ngetfsstat64(0x7FFD41001600, 0x3B48, 0x2)         = 6 0\ngetfsstat64(0x7FFD41001600, 0x3B48, 0x1)         = 6 0\ngetrlimit(0x1008, 0x7FFEEE4C9EC0, 0x0)       = 0 0\nfstat64(0x1, 0x7FFEEE4C9ED8, 0x0)        = 0 0\nioctl(0x1, 0x4004667A, 0x7FFEEE4C9F24)       = 0 0  \n</code></pre>\n\n<p>Here's <code>df</code> output (notice the iused field) </p>\n\n<pre><code>Filesystem    512-blocks      Used Available Capacity iused               ifree %iused  Mounted on\n/dev/disk1s1   976695384 757288824 211770792    79% 2000778 9223372036852775029    0%   /\n</code></pre>\n\n<p>Any ideas where can I find the source code of <code>df</code> or to other API for this task.</p>\n\n<p>thanks </p>\n"
        },
        {
            "tags": [
                "database",
                "tfs",
                "code-cleanup"
            ],
            "owner": {
                "reputation": 23,
                "user_id": 3560215,
                "user_type": "registered",
                "accept_rate": 11,
                "profile_image": "https://www.gravatar.com/avatar/88990fdaff2fabb17c04f1edd23d0df0?s=128&d=identicon&r=PG&f=1",
                "display_name": "hitman126",
                "link": "https://stackoverflow.com/users/3560215/hitman126"
            },
            "is_answered": false,
            "view_count": 14,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1523524535,
            "creation_date": 1523521650,
            "last_edit_date": 1523524535,
            "question_id": 49791540,
            "body_markdown": "To reduce the size of our TFS database to enable the use of the DACPAC import method for a pending migration, we&#39;ve carried out some extensive cleanup, including the deletion of redundant team projects and build artifacts.\r\nTo force the cleanup to happen immediately, I&#39;ve run the following two stored procedures (below):\r\n\r\nEXEC prc_CleanupDeletedFileContent 1\r\n\r\n&lt;--You may have to run the following command multiple times, the last parameter is the batch size, if there are more items to prune than the passed in number, you will have to run it multiple times--&gt;\r\n\r\nEXEC prc_DeleteUnusedFiles 1, 0, 100000\r\n\r\nThe first stored procedure completes successfully, however the second throws the below lock resource error, thereby causing it to not complete successfully. All attempts to address the lock issue, including taking the project collection offline and disabling access for all users and then re-running the second stored procedure, has so far proved futile. \r\n\r\nLock Error Message:&lt;br&gt;\r\nMsg 1204, Level 19, State 4, Procedure prc_DeleteUnusedFiles, Line 210\r\nThe instance of the SQL Server Database Engine cannot obtain a LOCK resource at this time. Rerun your statement when there are fewer active users. Ask the database administrator to check the lock and memory configuration for this instance, or to check for long-running transactions.\r\n\r\nWould be grateful for any advice on how I can get this second stored procedure to run successfully. Thank you.",
            "link": "https://stackoverflow.com/questions/49791540/tfs-database-cleanup-job-is-failing",
            "title": "TFS Database Cleanup Job Is Failing",
            "body": "<p>To reduce the size of our TFS database to enable the use of the DACPAC import method for a pending migration, we've carried out some extensive cleanup, including the deletion of redundant team projects and build artifacts.\nTo force the cleanup to happen immediately, I've run the following two stored procedures (below):</p>\n\n<p>EXEC prc_CleanupDeletedFileContent 1</p>\n\n<p>&lt;--You may have to run the following command multiple times, the last parameter is the batch size, if there are more items to prune than the passed in number, you will have to run it multiple times--></p>\n\n<p>EXEC prc_DeleteUnusedFiles 1, 0, 100000</p>\n\n<p>The first stored procedure completes successfully, however the second throws the below lock resource error, thereby causing it to not complete successfully. All attempts to address the lock issue, including taking the project collection offline and disabling access for all users and then re-running the second stored procedure, has so far proved futile. </p>\n\n<p>Lock Error Message:<br>\nMsg 1204, Level 19, State 4, Procedure prc_DeleteUnusedFiles, Line 210\nThe instance of the SQL Server Database Engine cannot obtain a LOCK resource at this time. Rerun your statement when there are fewer active users. Ask the database administrator to check the lock and memory configuration for this instance, or to check for long-running transactions.</p>\n\n<p>Would be grateful for any advice on how I can get this second stored procedure to run successfully. Thank you.</p>\n"
        },
        {
            "tags": [
                "cordova-plugins"
            ],
            "owner": {
                "reputation": 8,
                "user_id": 9253318,
                "user_type": "registered",
                "profile_image": "https://i.stack.imgur.com/rhrN9.jpg?s=128&g=1",
                "display_name": "MOTZI",
                "link": "https://stackoverflow.com/users/9253318/motzi"
            },
            "is_answered": true,
            "view_count": 83,
            "accepted_answer_id": 49792621,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1523524530,
            "creation_date": 1518778733,
            "question_id": 48825311,
            "body_markdown": "i am new to cordova.\r\n\r\nI created a project using the command `cordova create hello com.example.helloapp Hello`. The Project is created with default folders and files and a `package.json`.\r\n\r\nThen, i wanted to add a simple plugin from git *(a hello world plugin for testing)* : `cordova plugin add https://github.com/don/cordova-plugin-hello.git` . \r\n&gt;I get an error that the file `package.json` dosen&#39;t exist in the current directory *(current directory = where i created my project hello that contains that file as said earlier)*, i listed the files with `dir /o`, see screens below :\r\n[Image Error][1] &amp;\r\n[Image package.json][2]\r\n\r\nWhat am i doing wrong ? Thanks in advance.\r\n\r\n\r\n  [1]: https://i.stack.imgur.com/qPEVg.jpg\r\n  [2]: https://i.stack.imgur.com/pMm7d.jpg",
            "link": "https://stackoverflow.com/questions/48825311/cordova-plugin-installation-and-package-json",
            "title": "Cordova plugin installation and package.json",
            "body": "<p>i am new to cordova.</p>\n\n<p>I created a project using the command <code>cordova create hello com.example.helloapp Hello</code>. The Project is created with default folders and files and a <code>package.json</code>.</p>\n\n<p>Then, i wanted to add a simple plugin from git <em>(a hello world plugin for testing)</em> : <code>cordova plugin add https://github.com/don/cordova-plugin-hello.git</code> . </p>\n\n<blockquote>\n  <p>I get an error that the file <code>package.json</code> dosen't exist in the current directory <em>(current directory = where i created my project hello that contains that file as said earlier)</em>, i listed the files with <code>dir /o</code>, see screens below :\n  <a href=\"https://i.stack.imgur.com/qPEVg.jpg\" rel=\"nofollow noreferrer\">Image Error</a> &amp;\n  <a href=\"https://i.stack.imgur.com/pMm7d.jpg\" rel=\"nofollow noreferrer\">Image package.json</a></p>\n</blockquote>\n\n<p>What am i doing wrong ? Thanks in advance.</p>\n"
        },
        {
            "tags": [
                "angular",
                "angular-router"
            ],
            "owner": {
                "reputation": 11441,
                "user_id": 2299820,
                "user_type": "registered",
                "accept_rate": 37,
                "profile_image": "https://i.stack.imgur.com/VlclH.jpg?s=128&g=1",
                "display_name": "Code Whisperer",
                "link": "https://stackoverflow.com/users/2299820/code-whisperer"
            },
            "is_answered": false,
            "view_count": 26,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1523524528,
            "creation_date": 1523461815,
            "question_id": 49779448,
            "body_markdown": "Angular Router defines a directive called `router-outlet` which renders a specified component in that spot if it&#39;s the route loaded by the router.\r\n\r\nSince you can define a base root (`/`), one would assume you no longer need a bootstrap component since the router can now put your parent component on the DOM.\r\n\r\nYet, if you do not define a bootstrap component, you get an error:\r\n\r\n&gt; `The module AppModule was bootstrapped, but it does not declare &quot;@NgModule.bootstrap&quot; components nor a &quot;ngDoBootstrap&quot; method. `\r\n\r\nOne also assumes that the `AppModule`, if it is bootstrapped, should be bootstrapped to the `&lt;app-root/&gt;` tag (by convention).\r\n\r\n\r\n\r\nI don&#39;t understand. How is the app supposed to work if the app bootstraps *and* the router is routing? Won&#39;t this lead to double components, etc? If the app is being rendered into the `router-outlet`, then what is the `app-root` tag doing?",
            "link": "https://stackoverflow.com/questions/49779448/angular-router-why-do-you-need-app-root-and-bootstrap",
            "title": "Angular Router - Why Do You Need App Root and Bootstrap?",
            "body": "<p>Angular Router defines a directive called <code>router-outlet</code> which renders a specified component in that spot if it's the route loaded by the router.</p>\n\n<p>Since you can define a base root (<code>/</code>), one would assume you no longer need a bootstrap component since the router can now put your parent component on the DOM.</p>\n\n<p>Yet, if you do not define a bootstrap component, you get an error:</p>\n\n<blockquote>\n  <p><code>The module AppModule was bootstrapped, but it does not declare \"@NgModule.bootstrap\" components nor a \"ngDoBootstrap\" method.</code></p>\n</blockquote>\n\n<p>One also assumes that the <code>AppModule</code>, if it is bootstrapped, should be bootstrapped to the <code>&lt;app-root/&gt;</code> tag (by convention).</p>\n\n<p>I don't understand. How is the app supposed to work if the app bootstraps <em>and</em> the router is routing? Won't this lead to double components, etc? If the app is being rendered into the <code>router-outlet</code>, then what is the <code>app-root</code> tag doing?</p>\n"
        },
        {
            "tags": [
                "oauth-2.0"
            ],
            "owner": {
                "reputation": 3,
                "user_id": 9218131,
                "user_type": "registered",
                "profile_image": "https://i.stack.imgur.com/T5m6e.jpg?s=128&g=1",
                "display_name": "Judson Abraham",
                "link": "https://stackoverflow.com/users/9218131/judson-abraham"
            },
            "is_answered": false,
            "view_count": 4,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1523524514,
            "creation_date": 1523524514,
            "question_id": 49792618,
            "body_markdown": "Hi everyone i have to create a client id using Installed application in my app.So ia have checked in  console.cloud.google.com but I&#39;m not able to find that tab.This is the screenshot of my client id screen.\r\n[enter image description here][1]\r\n\r\n\r\n  [1]: https://i.stack.imgur.com/2k1xI.png",
            "link": "https://stackoverflow.com/questions/49792618/installed-application-tab-not-found-in-console-cloud-google-com",
            "title": "Installed application tab not found in console.cloud.google.com",
            "body": "<p>Hi everyone i have to create a client id using Installed application in my app.So ia have checked in  console.cloud.google.com but I'm not able to find that tab.This is the screenshot of my client id screen.\n<a href=\"https://i.stack.imgur.com/2k1xI.png\" rel=\"nofollow noreferrer\">enter image description here</a></p>\n"
        },
        {
            "tags": [
                "python",
                "django",
                "unit-testing",
                "logging"
            ],
            "owner": {
                "reputation": 5200,
                "user_id": 170589,
                "user_type": "registered",
                "accept_rate": 86,
                "profile_image": "https://www.gravatar.com/avatar/eda10e362f29d20a1a3f125fa01fa2ef?s=128&d=identicon&r=PG",
                "display_name": "shreddd",
                "link": "https://stackoverflow.com/users/170589/shreddd"
            },
            "is_answered": true,
            "view_count": 29814,
            "accepted_answer_id": 5255760,
            "answer_count": 8,
            "score": 123,
            "last_activity_date": 1523524511,
            "creation_date": 1299733195,
            "last_edit_date": 1447181353,
            "question_id": 5255657,
            "body_markdown": "I am using a simple unit test based test runner to test my Django application.\r\n\r\nMy application itself is configured to use a basic logger in settings.py using:\r\n\r\n    logging.basicConfig(level=logging.DEBUG)\r\n\r\nAnd in my application code using:\r\n\r\n    logger = logging.getLogger(__name__)\r\n    logger.setLevel(getattr(settings, &#39;LOG_LEVEL&#39;, logging.DEBUG))\r\n\r\nHowever, when running unittests, I&#39;d like to disable logging so that it doesn&#39;t clutter my test result output. Is there a simple way to turn off logging in a global way, so that the application specific loggers aren&#39;t writing stuff out to the console when I run tests?\r\n",
            "link": "https://stackoverflow.com/questions/5255657/how-can-i-disable-logging-while-running-unit-tests-in-python-django",
            "title": "How can I disable logging while running unit tests in Python Django?",
            "body": "<p>I am using a simple unit test based test runner to test my Django application.</p>\n\n<p>My application itself is configured to use a basic logger in settings.py using:</p>\n\n<pre><code>logging.basicConfig(level=logging.DEBUG)\n</code></pre>\n\n<p>And in my application code using:</p>\n\n<pre><code>logger = logging.getLogger(__name__)\nlogger.setLevel(getattr(settings, 'LOG_LEVEL', logging.DEBUG))\n</code></pre>\n\n<p>However, when running unittests, I'd like to disable logging so that it doesn't clutter my test result output. Is there a simple way to turn off logging in a global way, so that the application specific loggers aren't writing stuff out to the console when I run tests?</p>\n"
        },
        {
            "tags": [
                "javascript",
                "ecmascript-6",
                "typeerror",
                "ecmascript-5",
                "primitive"
            ],
            "owner": {
                "reputation": 410,
                "user_id": 4969945,
                "user_type": "registered",
                "accept_rate": 11,
                "profile_image": "https://www.gravatar.com/avatar/f0d7c703d6b14143a367efefdbc908fb?s=128&d=identicon&r=PG",
                "display_name": "cpcallen",
                "link": "https://stackoverflow.com/users/4969945/cpcallen"
            },
            "is_answered": true,
            "view_count": 1154,
            "accepted_answer_id": 49683320,
            "answer_count": 2,
            "score": 22,
            "last_activity_date": 1523524510,
            "creation_date": 1522968410,
            "question_id": 49682661,
            "body_markdown": "According to the ES5.1 spec, the program `&quot;use strict;&quot; &quot;foo&quot;.bar = 42;` causes a `String` object to be created, assigns to a property on it, and then throws the object away, resulting in no observable effects - including any exceptions.  (The absence of effect can be confirmed by trying it in an ES5-compatible JS implementation like that in Opera 12.)\r\n\r\nIn modern JS implementations, it throws a `TypeError` instead—try it:\r\n\r\n&lt;!-- begin snippet: js hide: false console: true babel: false --&gt;\r\n&lt;!-- language: lang-js --&gt;\r\n\r\n    &quot;use strict&quot;; &quot;foo&quot;.bar = 42;\r\n\r\n&lt;!-- end snippet --&gt;\r\n\r\nI am pretty sure the new behaviour is mandated by the ES6 spec, but despite reading the relevant sections several times I cannot see where it is specified that `TypeError` be thrown.  In fact, [the key parts][1] appear to be unchanged:\r\n\r\n&gt; 6.2.3.2 PutValue (*V*, *W*)#\r\n\r\n&gt; 1. ReturnIfAbrupt(*V*).\r\n&gt; 1. ReturnIfAbrupt(*W*).\r\n&gt; 1. If Type(*V*) is not Reference, throw a **ReferenceError** exception.\r\n&gt; 1. Let *base* be GetBase(*V*).\r\n&gt; 1. If IsUnresolvableReference(*V*) is true, then\r\n&gt;    * …\r\n&gt; 1. Else if IsPropertyReference(*V*) is true, then\r\n&gt;    * a. If HasPrimitiveBase(*V*) is true, then\r\n&gt;        * i. Assert: In this case, *base* will never be null or undefined.\r\n&gt;        * ii. Set *base* to ToObject(*base*).\r\n&gt;    * b. Let *succeeded* be ? *base*.[[Set]](GetReferencedName(*V*), *W*, GetThisValue(*V*)).\r\n&gt;    * c. ReturnIfAbrupt(*succeeded*).\r\n&gt;    * d. If *succeeded* is false and IsStrictReference(*V*) is true, throw a **TypeError** exception.\r\n&gt;    * e. Return.\r\n&gt; 1. …\r\n\r\nWhere does the spec (ES6 or later) mandate throwing `TypeError`?\r\n\r\n\r\n  [1]: https://www.ecma-international.org/ecma-262/6.0/index.html#sec-putvalue",
            "link": "https://stackoverflow.com/questions/49682661/why-does-foo-bar-42-throw-typeerror-in-strict-mode-in-es6",
            "title": "Why does `&quot;foo&quot;.bar = 42;` throw `TypeError` in strict mode in ES6?",
            "body": "<p>According to the ES5.1 spec, the program <code>\"use strict;\" \"foo\".bar = 42;</code> causes a <code>String</code> object to be created, assigns to a property on it, and then throws the object away, resulting in no observable effects - including any exceptions.  (The absence of effect can be confirmed by trying it in an ES5-compatible JS implementation like that in Opera 12.)</p>\n\n<p>In modern JS implementations, it throws a <code>TypeError</code> instead—try it:</p>\n\n<p><div class=\"snippet\" data-lang=\"js\" data-hide=\"false\" data-console=\"true\" data-babel=\"false\">\r\n<div class=\"snippet-code\">\r\n<pre class=\"snippet-code-js lang-js prettyprint-override\"><code>\"use strict\"; \"foo\".bar = 42;</code></pre>\r\n</div>\r\n</div>\r\n</p>\n\n<p>I am pretty sure the new behaviour is mandated by the ES6 spec, but despite reading the relevant sections several times I cannot see where it is specified that <code>TypeError</code> be thrown.  In fact, <a href=\"https://www.ecma-international.org/ecma-262/6.0/index.html#sec-putvalue\" rel=\"noreferrer\">the key parts</a> appear to be unchanged:</p>\n\n<blockquote>\n  <p>6.2.3.2 PutValue (<em>V</em>, <em>W</em>)#</p>\n  \n  <ol>\n  <li>ReturnIfAbrupt(<em>V</em>).</li>\n  <li>ReturnIfAbrupt(<em>W</em>).</li>\n  <li>If Type(<em>V</em>) is not Reference, throw a <strong>ReferenceError</strong> exception.</li>\n  <li>Let <em>base</em> be GetBase(<em>V</em>).</li>\n  <li>If IsUnresolvableReference(<em>V</em>) is true, then\n  \n  <ul>\n  <li>…</li>\n  </ul></li>\n  <li>Else if IsPropertyReference(<em>V</em>) is true, then\n  \n  <ul>\n  <li>a. If HasPrimitiveBase(<em>V</em>) is true, then\n  \n  <ul>\n  <li>i. Assert: In this case, <em>base</em> will never be null or undefined.</li>\n  <li>ii. Set <em>base</em> to ToObject(<em>base</em>).</li>\n  </ul></li>\n  <li>b. Let <em>succeeded</em> be ? <em>base</em>.[[Set]](GetReferencedName(<em>V</em>), <em>W</em>, GetThisValue(<em>V</em>)).</li>\n  <li>c. ReturnIfAbrupt(<em>succeeded</em>).</li>\n  <li>d. If <em>succeeded</em> is false and IsStrictReference(<em>V</em>) is true, throw a <strong>TypeError</strong> exception.</li>\n  <li>e. Return.</li>\n  </ul></li>\n  <li>…</li>\n  </ol>\n</blockquote>\n\n<p>Where does the spec (ES6 or later) mandate throwing <code>TypeError</code>?</p>\n"
        },
        {
            "tags": [
                "python",
                "type-conversion",
                "series",
                "pi"
            ],
            "owner": {
                "reputation": 13,
                "user_id": 9634762,
                "user_type": "registered",
                "profile_image": "https://graph.facebook.com/1961302920578413/picture?type=large",
                "display_name": "Laura Marinescu",
                "link": "https://stackoverflow.com/users/9634762/laura-marinescu"
            },
            "is_answered": true,
            "view_count": 30,
            "accepted_answer_id": 49791637,
            "answer_count": 2,
            "score": 2,
            "last_activity_date": 1523524506,
            "creation_date": 1523520872,
            "last_edit_date": 1523523334,
            "question_id": 49791305,
            "body_markdown": "I just started using python and can&#39;t really get the hang of it.. \r\n\r\nI wrote the code in **mathlab** but is hard to covert it the right way in **python**. \r\n\r\n[![Image][1]][1]\r\n\r\nCould you please help?\r\n\r\n\r\n   \r\n\r\n     x=0;\r\n        for i=1:1000\r\n             x=x+(1/((((2*i)-1)^2)*(((2*i)+1^2))));\r\n             z=sqrt((x*16)+8);\r\n             error=abs(z-pi);\r\n             if (error &lt; 10^-8)\r\n                i\r\n                break\r\n             end\r\n        end\r\n\r\n\r\n\r\nThank you \r\n\r\n\r\n    \r\n\r\n\r\n  [1]: https://i.stack.imgur.com/xOG2h.png",
            "link": "https://stackoverflow.com/questions/49791305/compute-the-value-of-%cf%80-using-the-following-series-matlab-conversion",
            "title": "Compute the value of π using the following series (Matlab conversion)",
            "body": "<p>I just started using Python and can't really get the hang of it.. </p>\n\n<p>I wrote the code in <strong>Matlab</strong> but is hard to covert it the right way in <strong>Python</strong>. </p>\n\n<p><a href=\"https://i.stack.imgur.com/xOG2h.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/xOG2h.png\" alt=\"Image\"></a></p>\n\n<p>Could you please help?</p>\n\n<pre><code> x=0;\n    for i=1:1000\n         x=x+(1/((((2*i)-1)^2)*(((2*i)+1^2))));\n         z=sqrt((x*16)+8);\n         error=abs(z-pi);\n         if (error &lt; 10^-8)\n            i\n            break\n         end\n    end\n</code></pre>\n\n<p>Thank you </p>\n"
        },
        {
            "tags": [
                "linux",
                "docker",
                "ports",
                "docker-networking",
                "penetration-testing"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 8836508,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/18e8d9e9afec1c86fbaa0ab6bb4bf5df?s=128&d=identicon&r=PG&f=1",
                "display_name": "Ion",
                "link": "https://stackoverflow.com/users/8836508/ion"
            },
            "is_answered": false,
            "view_count": 41,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1523524503,
            "creation_date": 1523355240,
            "last_edit_date": 1523524503,
            "question_id": 49751031,
            "body_markdown": "I&#39;m trying to pen-test a container with another container, and need to have port 2375 opened in order to acomplish the exploit: \r\n    exploit/linux/http/docker_daemon_tcp. \r\nI&#39;ve tried various scenarios, first I port mapped with the flag\r\n \r\n     -p hostport:2375 \r\nafterwards I tried to customize the Docker daemon options and add the \r\n\r\n    tcp socket -H tcp://0.0.0.0:2375\r\noption, \r\nI even port forward in the container, in the host too. I tried to delete the firewalls, disable iptables and couldn&#39;t get a response from the port 2375. As much as I nmap it I couldn&#39;t get the port opened from a container. Also, on the\r\n\r\n    systemctl status docker.service\r\n there is actual exception created for and with\r\n\r\n    tcp://0.0.0.0:2375\r\nBut nmap and metasploit don&#39;t have the port opened, neither docker when\r\n\r\n    netstat -plnt \r\ndoesn&#39;t show the opened port. \r\nDocker Inspect doesn&#39;t show the opened port either.\r\nIf anyone could suggest any explanation or solution, I would kindly appreciate it. ",
            "link": "https://stackoverflow.com/questions/49751031/docker-port-mapping-pen-test-container",
            "title": "Docker port mapping, pen-test container",
            "body": "<p>I'm trying to pen-test a container with another container, and need to have port 2375 opened in order to acomplish the exploit: \n    exploit/linux/http/docker_daemon_tcp. \nI've tried various scenarios, first I port mapped with the flag</p>\n\n<pre><code> -p hostport:2375 \n</code></pre>\n\n<p>afterwards I tried to customize the Docker daemon options and add the </p>\n\n<pre><code>tcp socket -H tcp://0.0.0.0:2375\n</code></pre>\n\n<p>option, \nI even port forward in the container, in the host too. I tried to delete the firewalls, disable iptables and couldn't get a response from the port 2375. As much as I nmap it I couldn't get the port opened from a container. Also, on the</p>\n\n<pre><code>systemctl status docker.service\n</code></pre>\n\n<p>there is actual exception created for and with</p>\n\n<pre><code>tcp://0.0.0.0:2375\n</code></pre>\n\n<p>But nmap and metasploit don't have the port opened, neither docker when</p>\n\n<pre><code>netstat -plnt \n</code></pre>\n\n<p>doesn't show the opened port. \nDocker Inspect doesn't show the opened port either.\nIf anyone could suggest any explanation or solution, I would kindly appreciate it. </p>\n"
        },
        {
            "tags": [
                "java",
                "json",
                "spring"
            ],
            "owner": {
                "reputation": 49,
                "user_id": 1241448,
                "user_type": "registered",
                "accept_rate": 75,
                "profile_image": "https://www.gravatar.com/avatar/accb72f6262f98657931dd192b0644f9?s=128&d=identicon&r=PG",
                "display_name": "Novacane",
                "link": "https://stackoverflow.com/users/1241448/novacane"
            },
            "is_answered": true,
            "view_count": 96,
            "accepted_answer_id": 44560557,
            "answer_count": 2,
            "score": 0,
            "last_activity_date": 1523524501,
            "creation_date": 1497480121,
            "last_edit_date": 1497491848,
            "question_id": 44555834,
            "body_markdown": "What I&#39;m attempting to do here is only read/parse the JSON portion of a file that is structured like this:\r\n\r\n    From: blahblah:blahblah:3:120319123\r\n    2015-02-03 20:05:48.4070783443 +0000 UTC\r\n    {&quot;id&quot;:&quot;daj;flkaj;dl&quot;, &quot;body&quot;:&quot;dafjelkaf&quot;, &quot;morestuff&quot;: \r\n    &quot;flakejfl;ka}flkajfl;daf{fad&quot;}\r\n\r\n    From: blahblah:blahblah:2:120319123\r\n    2016-04-03 20:05:48.4070783443 +0000 UTC\r\n    {&quot;id&quot;:&quot;daj;flkaj;dl&quot;, &quot;body&quot;:&quot;dafjelkaf&quot;, &quot;morestuff&quot;: \r\n    &quot;flakejfl;ka}flkajfl;daf{fad&quot;}\r\n\r\nI was originally planning to use FlatFileItemReader with the JsonLineMapper, but I would first need to discard the useless lines before parsing the Json line.\r\n\r\n How can I skip the line that starts with `From:`, the line with the date, and blank line when reading?\r\n\r\n",
            "link": "https://stackoverflow.com/questions/44555834/spring-batch-remove-certain-types-of-lines-from-reader-json-parsing",
            "title": "Spring Batch - Remove Certain Types of Lines From Reader &amp; JSON Parsing",
            "body": "<p>What I'm attempting to do here is only read/parse the JSON portion of a file that is structured like this:</p>\n\n<pre><code>From: blahblah:blahblah:3:120319123\n2015-02-03 20:05:48.4070783443 +0000 UTC\n{\"id\":\"daj;flkaj;dl\", \"body\":\"dafjelkaf\", \"morestuff\": \n\"flakejfl;ka}flkajfl;daf{fad\"}\n\nFrom: blahblah:blahblah:2:120319123\n2016-04-03 20:05:48.4070783443 +0000 UTC\n{\"id\":\"daj;flkaj;dl\", \"body\":\"dafjelkaf\", \"morestuff\": \n\"flakejfl;ka}flkajfl;daf{fad\"}\n</code></pre>\n\n<p>I was originally planning to use FlatFileItemReader with the JsonLineMapper, but I would first need to discard the useless lines before parsing the Json line.</p>\n\n<p>How can I skip the line that starts with <code>From:</code>, the line with the date, and blank line when reading?</p>\n"
        },
        {
            "tags": [
                "database",
                "database-design"
            ],
            "owner": {
                "reputation": 35,
                "user_id": 8091237,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/90fbd0d8c8265998e6a0681976a5ac41?s=128&d=identicon&r=PG&f=1",
                "display_name": "AKS",
                "link": "https://stackoverflow.com/users/8091237/aks"
            },
            "is_answered": false,
            "view_count": 6,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1523524496,
            "creation_date": 1523524496,
            "question_id": 49792611,
            "body_markdown": "I have requirement for saving setting&#39;s for different users like date, number and currency display. Meaning if date then user can choose between `dd-mm-yy or mm-dd-yy` for date format, for currency the values will be like `rupee`, `$`, for number `lac`,`million`, for time format `12h/24h`.\r\n\r\nI did something like this `Setting`, `settingattr`, `settingattrvalue` tables. Is there better solution or this is enough?",
            "link": "https://stackoverflow.com/questions/49792611/settings-for-different-user-for-data-display-format-likedate-currency-number",
            "title": "Setting&#39;s for different user for data display format like(date, Currency, number format) in web app",
            "body": "<p>I have requirement for saving setting's for different users like date, number and currency display. Meaning if date then user can choose between <code>dd-mm-yy or mm-dd-yy</code> for date format, for currency the values will be like <code>rupee</code>, <code>$</code>, for number <code>lac</code>,<code>million</code>, for time format <code>12h/24h</code>.</p>\n\n<p>I did something like this <code>Setting</code>, <code>settingattr</code>, <code>settingattrvalue</code> tables. Is there better solution or this is enough?</p>\n"
        },
        {
            "tags": [
                "java"
            ],
            "migrated_from": {
                "other_site": {
                    "styling": {
                        "tag_background_color": "#FFFFFF",
                        "tag_foreground_color": "#1087A4",
                        "link_color": "#1086A4"
                    },
                    "related_sites": [
                        {
                            "relation": "meta",
                            "api_site_parameter": "meta.superuser",
                            "site_url": "https://meta.superuser.com",
                            "name": "Meta Super User"
                        },
                        {
                            "relation": "chat",
                            "site_url": "https://chat.stackexchange.com?tab=site&host=superuser.com",
                            "name": "Chat Stack Exchange"
                        }
                    ],
                    "markdown_extensions": [
                        "Prettify"
                    ],
                    "launch_date": 1250553600,
                    "open_beta_date": 1247529600,
                    "site_state": "normal",
                    "high_resolution_icon_url": "https://cdn.sstatic.net/Sites/superuser/img/apple-touch-icon@2.png",
                    "twitter_account": "super_user",
                    "favicon_url": "https://cdn.sstatic.net/Sites/superuser/img/favicon.ico",
                    "icon_url": "https://cdn.sstatic.net/Sites/superuser/img/apple-touch-icon.png",
                    "audience": "computer enthusiasts and power users",
                    "site_url": "https://superuser.com",
                    "api_site_parameter": "superuser",
                    "logo_url": "https://cdn.sstatic.net/Sites/superuser/img/logo.png",
                    "name": "Super User",
                    "site_type": "main_site"
                },
                "on_date": 1250673046,
                "question_id": 24698
            },
            "owner": {
                "reputation": 303,
                "user_id": 221250,
                "user_type": "registered",
                "accept_rate": 28,
                "profile_image": "https://www.gravatar.com/avatar/ff6eebf40850e16b0db629e1c10b6586?s=128&d=identicon&r=PG",
                "display_name": "arnold",
                "link": "https://stackoverflow.com/users/221250/arnold"
            },
            "is_answered": true,
            "view_count": 5183,
            "accepted_answer_id": 1298665,
            "answer_count": 9,
            "score": 4,
            "last_activity_date": 1523524494,
            "creation_date": 1250615356,
            "last_edit_date": 1250754964,
            "question_id": 1298661,
            "body_markdown": "Why Java is still used in web development? I&#39;m just curious..",
            "link": "https://stackoverflow.com/questions/1298661/why-java-is-still-used-in-web-development",
            "title": "Why Java is still used in web development?",
            "body": "<p>Why Java is still used in web development? I'm just curious..</p>\n"
        },
        {
            "tags": [
                "mongodb"
            ],
            "owner": {
                "reputation": 101,
                "user_id": 5244410,
                "user_type": "registered",
                "accept_rate": 37,
                "profile_image": "https://www.gravatar.com/avatar/c2e125721f74672d38c5dcd66aaf5bb4?s=128&d=identicon&r=PG&f=1",
                "display_name": "wprins",
                "link": "https://stackoverflow.com/users/5244410/wprins"
            },
            "is_answered": false,
            "view_count": 13,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1523524493,
            "creation_date": 1523406553,
            "last_edit_date": 1523471272,
            "question_id": 49764679,
            "body_markdown": "I&#39;ve been following this guide: https://gist.github.com/calvinh8/c99e198ce5df3d8b1f1e42c1b984d7a4\r\n\r\nI just finished setting up all my servers and created the user in the admin database giving this return:\r\n\r\n    Successfully added user: {\r\n    \t&quot;user&quot; : &quot;user&quot;,\r\n    \t&quot;roles&quot; : [\r\n    \t\t{\r\n    \t\t\t&quot;role&quot; : &quot;root&quot;,\r\n    \t\t\t&quot;db&quot; : &quot;admin&quot;\r\n    \t\t}\r\n    \t]\r\n    }\r\n\r\nNow I am trying to link up the databases with the command:\r\n\r\n`rs.add(&quot;ec2-XX-XXX-XX-XXX.compute-1.amazonaws.com&quot;)`\r\n\r\nBut it gives me back the error: \r\n\r\n    2018-04-11T00:20:56.389+0000 E QUERY    [thread1] Error: count failed: {\r\n    \t&quot;ok&quot; : 0,\r\n    \t&quot;errmsg&quot; : &quot;not authorized on local to execute command { count: \\&quot;system.replset\\&quot;, query: {}, fields: {} }&quot;,\r\n    \t&quot;code&quot; : 13,\r\n    \t&quot;codeName&quot; : &quot;Unauthorized&quot;\r\n    } :\r\n    _getErrorWithCode@src/mongo/shell/utils.js:25:13\r\n    DBQuery.prototype.count@src/mongo/shell/query.js:383:11\r\n    DBCollection.prototype.count@src/mongo/shell/collection.js:1700:12\r\n    rs.add@src/mongo/shell/utils.js:1240:1\r\n    @(shell):1:1\r\n\r\nIs there some login I need to do for authentication when pointing to the replica? Do I have the keyFile wrong between machines? Can anyone shed some light?",
            "link": "https://stackoverflow.com/questions/49764679/mongodb-replica-setup-not-authorized-on-local-to-execute-command",
            "title": "mongodb replica setup: not authorized on local to execute command",
            "body": "<p>I've been following this guide: <a href=\"https://gist.github.com/calvinh8/c99e198ce5df3d8b1f1e42c1b984d7a4\" rel=\"nofollow noreferrer\">https://gist.github.com/calvinh8/c99e198ce5df3d8b1f1e42c1b984d7a4</a></p>\n\n<p>I just finished setting up all my servers and created the user in the admin database giving this return:</p>\n\n<pre><code>Successfully added user: {\n    \"user\" : \"user\",\n    \"roles\" : [\n        {\n            \"role\" : \"root\",\n            \"db\" : \"admin\"\n        }\n    ]\n}\n</code></pre>\n\n<p>Now I am trying to link up the databases with the command:</p>\n\n<p><code>rs.add(\"ec2-XX-XXX-XX-XXX.compute-1.amazonaws.com\")</code></p>\n\n<p>But it gives me back the error: </p>\n\n<pre><code>2018-04-11T00:20:56.389+0000 E QUERY    [thread1] Error: count failed: {\n    \"ok\" : 0,\n    \"errmsg\" : \"not authorized on local to execute command { count: \\\"system.replset\\\", query: {}, fields: {} }\",\n    \"code\" : 13,\n    \"codeName\" : \"Unauthorized\"\n} :\n_getErrorWithCode@src/mongo/shell/utils.js:25:13\nDBQuery.prototype.count@src/mongo/shell/query.js:383:11\nDBCollection.prototype.count@src/mongo/shell/collection.js:1700:12\nrs.add@src/mongo/shell/utils.js:1240:1\n@(shell):1:1\n</code></pre>\n\n<p>Is there some login I need to do for authentication when pointing to the replica? Do I have the keyFile wrong between machines? Can anyone shed some light?</p>\n"
        },
        {
            "tags": [
                "r",
                "dataframe"
            ],
            "owner": {
                "reputation": 23,
                "user_id": 8495426,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/3f7fbe96555b207e012bb0a3b232e9fc?s=128&d=identicon&r=PG&f=1",
                "display_name": "You Zhou",
                "link": "https://stackoverflow.com/users/8495426/you-zhou"
            },
            "is_answered": true,
            "view_count": 32,
            "accepted_answer_id": 49778715,
            "answer_count": 1,
            "score": 1,
            "last_activity_date": 1523524487,
            "creation_date": 1523458745,
            "last_edit_date": 1523524487,
            "question_id": 49778438,
            "body_markdown": "    c1 &lt;- c(&quot;product a1&quot;,&quot;product a2&quot;,&quot;product a3&quot;,&quot;product b1&quot;,&quot;product b2&quot;,&quot;product b3&quot;)\r\n    c2 &lt;- matrix (c1,nrow=2,ncol=3,dimnames = list(c(&quot;productline a&quot;,&quot;productline b&quot;),c(&quot;1&quot;,&quot;2&quot;,&quot;3&quot;)))\r\n    company1 &lt;- c(0,1,0,0,0,0)\r\n    company2 &lt;- c(0,0,0,1,1,0)\r\n    company3 &lt;- c(1,1,0,0,0,0)\r\n    data1 &lt;- data.frame(company1,company2,company3,row.names = c1)\r\n    c2            \r\n                       1            2            3           \r\n    productline a &quot;product a1&quot; &quot;product a2&quot; &quot;product b3&quot;\r\n    productline b &quot;product b1&quot; &quot;product b2&quot; &quot;product b3&quot;   \r\n    \r\n    data1\r\n                company1 company2 company3\r\n    product a1        0        0        1\r\n    product a2        1        0        1\r\n    product a3        0        0        0\r\n    product b1        0        1        0\r\n    product b2        0        1        0\r\n    product b3        0        0        0\r\n    result\r\n                productline a   productline b\r\n     company1        1               0         \r\n     company2        0               2\r\n     company3        2               0  \r\n\r\n\r\n I have a table data1 up here. Now I want to analyse data1. And the basic information is product a1，a2，a3 all belong to &quot;productline a&quot;, product b1,b2,b3 belong to &quot;productline b&quot;, like table c2 shows. \r\n\r\nI want to combine table c2 and data1 to get the result table like I show up there. \r\n\r\nHow can I do that?",
            "link": "https://stackoverflow.com/questions/49778438/how-to-build-a-link-between-a-character-table-and-a-numeric-table",
            "title": "How to build a link between a character table and a numeric table?",
            "body": "<pre><code>c1 &lt;- c(\"product a1\",\"product a2\",\"product a3\",\"product b1\",\"product b2\",\"product b3\")\nc2 &lt;- matrix (c1,nrow=2,ncol=3,dimnames = list(c(\"productline a\",\"productline b\"),c(\"1\",\"2\",\"3\")))\ncompany1 &lt;- c(0,1,0,0,0,0)\ncompany2 &lt;- c(0,0,0,1,1,0)\ncompany3 &lt;- c(1,1,0,0,0,0)\ndata1 &lt;- data.frame(company1,company2,company3,row.names = c1)\nc2            \n                   1            2            3           \nproductline a \"product a1\" \"product a2\" \"product b3\"\nproductline b \"product b1\" \"product b2\" \"product b3\"   \n\ndata1\n            company1 company2 company3\nproduct a1        0        0        1\nproduct a2        1        0        1\nproduct a3        0        0        0\nproduct b1        0        1        0\nproduct b2        0        1        0\nproduct b3        0        0        0\nresult\n            productline a   productline b\n company1        1               0         \n company2        0               2\n company3        2               0  \n</code></pre>\n\n<p>I have a table data1 up here. Now I want to analyse data1. And the basic information is product a1，a2，a3 all belong to \"productline a\", product b1,b2,b3 belong to \"productline b\", like table c2 shows. </p>\n\n<p>I want to combine table c2 and data1 to get the result table like I show up there. </p>\n\n<p>How can I do that?</p>\n"
        },
        {
            "tags": [
                "python"
            ],
            "owner": {
                "reputation": 82,
                "user_id": 7759296,
                "user_type": "registered",
                "accept_rate": 50,
                "profile_image": "https://www.gravatar.com/avatar/24dc65bcbed839a24876f45ca7ae2eb1?s=128&d=identicon&r=PG&f=1",
                "display_name": "Ofey",
                "link": "https://stackoverflow.com/users/7759296/ofey"
            },
            "is_answered": true,
            "view_count": 24,
            "accepted_answer_id": 49792578,
            "answer_count": 2,
            "score": -4,
            "last_activity_date": 1523524483,
            "creation_date": 1523524219,
            "question_id": 49792494,
            "body_markdown": "I was writing some python code and I found a strange behaviour in my code.\r\n\r\nThis is the code:\r\n\r\n    import sys\r\n    \r\n    f=open(&quot;test1&quot;,&quot;wb&quot;)\r\n    test=&quot;1000000000&quot;\r\n    f.write(bytearray(int(test)))\r\n    f.close()\r\n\r\n\r\n\r\nIt generates the file **test1** with lenght 1000000000 (1,0 GB) filled with 0.\r\nIs this supposed to happen(if yes, **why**?) or is a bug?",
            "link": "https://stackoverflow.com/questions/49792494/strange-python-behaviour-of-f-write",
            "title": "Strange python behaviour of f.write()",
            "body": "<p>I was writing some python code and I found a strange behaviour in my code.</p>\n\n<p>This is the code:</p>\n\n<pre><code>import sys\n\nf=open(\"test1\",\"wb\")\ntest=\"1000000000\"\nf.write(bytearray(int(test)))\nf.close()\n</code></pre>\n\n<p>It generates the file <strong>test1</strong> with lenght 1000000000 (1,0 GB) filled with 0.\nIs this supposed to happen(if yes, <strong>why</strong>?) or is a bug?</p>\n"
        },
        {
            "tags": [
                "x86-16",
                "emu8086"
            ],
            "owner": {
                "reputation": 36,
                "user_id": 3140379,
                "user_type": "registered",
                "accept_rate": 50,
                "profile_image": "https://www.gravatar.com/avatar/140ac8205deee8c5ba7ff9666d1e1267?s=128&d=identicon&r=PG&f=1",
                "display_name": "user3140379",
                "link": "https://stackoverflow.com/users/3140379/user3140379"
            },
            "is_answered": true,
            "view_count": 36,
            "answer_count": 1,
            "score": 4,
            "last_activity_date": 1523524480,
            "creation_date": 1523390399,
            "last_edit_date": 1523390905,
            "question_id": 49761994,
            "body_markdown": "I just checked the manual again and MOV Immediate, REG is not allowed and in fact is illogical, but when I compile, it runs just fine.",
            "link": "https://stackoverflow.com/questions/49761994/why-is-mov-0900h-ax-allowed-in-emu8086",
            "title": "Why is mov 0900h, ax allowed in emu8086?",
            "body": "<p>I just checked the manual again and MOV Immediate, REG is not allowed and in fact is illogical, but when I compile, it runs just fine.</p>\n"
        },
        {
            "tags": [
                "javascript",
                "jquery",
                "html",
                "html2canvas",
                "webpage-screenshot"
            ],
            "owner": {
                "reputation": 124,
                "user_id": 3787306,
                "user_type": "registered",
                "accept_rate": 60,
                "profile_image": "https://www.gravatar.com/avatar/6453b04b1c233d67def512a801eb8162?s=128&d=identicon&r=PG&f=1",
                "display_name": "divelner",
                "link": "https://stackoverflow.com/users/3787306/divelner"
            },
            "is_answered": true,
            "view_count": 28943,
            "closed_date": 1450164612,
            "accepted_answer_id": 34272656,
            "answer_count": 3,
            "score": 5,
            "last_activity_date": 1523524472,
            "creation_date": 1450111467,
            "question_id": 34272274,
            "body_markdown": "I&#39;m need my clients be able to capture screenshot of any page of my website using button like this:\r\n\r\n&lt;!-- begin snippet: js hide: false --&gt;\r\n\r\n&lt;!-- language: lang-html --&gt;\r\n\r\n    &lt;button&gt;Take screenshot&lt;/button&gt;\r\n\r\n&lt;!-- end snippet --&gt;\r\n\r\nI tried to use html2canvas but it&#39;s doesn&#39;t work properly for me because i have iframe&#39;s in my website and it&#39;s cause some session problems.\r\n\r\nsomeone have solution for this?\r\n\r\ni looked all over google and didn&#39;t found something that&#39;s helps me much.\r\n\r\n ",
            "link": "https://stackoverflow.com/questions/34272274/how-to-capture-screenshot-in-html-using-js-or-jquery",
            "closed_reason": "duplicate",
            "title": "how to capture screenshot in html using js or jquery",
            "body": "<p>I'm need my clients be able to capture screenshot of any page of my website using button like this:</p>\n\n<p><div class=\"snippet\" data-lang=\"js\" data-hide=\"false\">\r\n<div class=\"snippet-code\">\r\n<pre class=\"snippet-code-html lang-html prettyprint-override\"><code>&lt;button&gt;Take screenshot&lt;/button&gt;</code></pre>\r\n</div>\r\n</div>\r\n</p>\n\n<p>I tried to use html2canvas but it's doesn't work properly for me because i have iframe's in my website and it's cause some session problems.</p>\n\n<p>someone have solution for this?</p>\n\n<p>i looked all over google and didn't found something that's helps me much.</p>\n"
        },
        {
            "tags": [
                "android",
                "android-studio"
            ],
            "owner": {
                "reputation": 14,
                "user_id": 5834902,
                "user_type": "registered",
                "profile_image": "https://i.stack.imgur.com/scr2z.png?s=128&g=1",
                "display_name": "forgot2015",
                "link": "https://stackoverflow.com/users/5834902/forgot2015"
            },
            "is_answered": false,
            "view_count": 68,
            "answer_count": 1,
            "score": -2,
            "last_activity_date": 1523524468,
            "creation_date": 1523440106,
            "last_edit_date": 1523440271,
            "question_id": 49771833,
            "body_markdown": "I have update Android Studio to latest version 3.1.1, but is so slowly , especially when I editing build.gradle file , is there any solution ?\r\n(before I use 3.0.1 , that is so fast)",
            "link": "https://stackoverflow.com/questions/49771833/android-studio-3-1-1-editing-build-gradle-file-slow",
            "title": "android studio 3.1.1 editing build.gradle file slow",
            "body": "<p>I have update Android Studio to latest version 3.1.1, but is so slowly , especially when I editing build.gradle file , is there any solution ?\n(before I use 3.0.1 , that is so fast)</p>\n"
        },
        {
            "tags": [
                "azure",
                "azure-webjobs"
            ],
            "owner": {
                "reputation": 279,
                "user_id": 1535658,
                "user_type": "registered",
                "accept_rate": 57,
                "profile_image": "https://i.stack.imgur.com/w3hOR.png?s=128&g=1",
                "display_name": "onesixtyfourth",
                "link": "https://stackoverflow.com/users/1535658/onesixtyfourth"
            },
            "is_answered": false,
            "view_count": 6,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1523524467,
            "creation_date": 1523519767,
            "last_edit_date": 1523520096,
            "question_id": 49790970,
            "body_markdown": "I have created an App Service that contains three WebJobs that are triggered from queues:\r\n\r\n&gt; BlobContainer -&gt; WJ1 -&gt; Q1 -&gt; WJ2 -&gt; Q2 -&gt; WJ3 -&gt; (Released into the\r\n&gt; wild)\r\n\r\nWhen I deploy the WebJobs (Visual Studio) the exe, exe.config and pdb files of WJ2 are in both WJ2 and WJ3 directories. WJ3 dir contains its own files as well but this means that WJ3 is not being triggered correctly.\r\n\r\nI have manually deleted the files from WJ3, removed my existing profiles and reset them. I have redeployed and the situation is the same. How do I resolve this situation.",
            "link": "https://stackoverflow.com/questions/49790970/deploying-webjobs-from-vs-puts-files-in-wrong-folder",
            "title": "Deploying WebJobs from VS puts files in wrong folder",
            "body": "<p>I have created an App Service that contains three WebJobs that are triggered from queues:</p>\n\n<blockquote>\n  <p>BlobContainer -> WJ1 -> Q1 -> WJ2 -> Q2 -> WJ3 -> (Released into the\n  wild)</p>\n</blockquote>\n\n<p>When I deploy the WebJobs (Visual Studio) the exe, exe.config and pdb files of WJ2 are in both WJ2 and WJ3 directories. WJ3 dir contains its own files as well but this means that WJ3 is not being triggered correctly.</p>\n\n<p>I have manually deleted the files from WJ3, removed my existing profiles and reset them. I have redeployed and the situation is the same. How do I resolve this situation.</p>\n"
        },
        {
            "tags": [
                "r",
                "duplicates",
                "key",
                "data.table"
            ],
            "owner": {
                "reputation": 335,
                "user_id": 5735794,
                "user_type": "registered",
                "accept_rate": 86,
                "profile_image": "https://www.gravatar.com/avatar/df619654445c0d6558a8c2f104685616?s=128&d=identicon&r=PG&f=1",
                "display_name": "hellter",
                "link": "https://stackoverflow.com/users/5735794/hellter"
            },
            "is_answered": true,
            "view_count": 1968,
            "accepted_answer_id": 37628660,
            "answer_count": 1,
            "score": 8,
            "last_activity_date": 1523524462,
            "creation_date": 1465032456,
            "last_edit_date": 1495540465,
            "question_id": 37628601,
            "body_markdown": "I have a `data.table` (`data` in the following) with 10 columns (`C1, ..., C10`) and I want to delete duplicate rows.  \r\n\r\nI accidentally used `setkey(data,C1)`, so now when I run `unique(data)` I only get unique rows based on the column `C1`, while I want to remove a row only if it&#39;s identical to another one on all the columns `C1, ..., C10`.  \r\nIs there a way to undo the `setkey()` operation? I found [this question][1] but it didn&#39;t help to solve my provlem.\r\n\r\nPS: I can get around the problem by setting all columns in my `data.table` as keys with `setkeyv(data, paste0(&quot;C&quot;, 1:10))`, but this is not at all an elegant/practical solution.\r\n\r\n\r\n  [1]: https://stackoverflow.com/questions/15552181/how-do-you-undo-a-setkey-ordering-in-data-table",
            "link": "https://stackoverflow.com/questions/37628601/undo-setkey-on-data-table-in-r",
            "title": "Undo setkey() on data.table in R",
            "body": "<p>I have a <code>data.table</code> (<code>data</code> in the following) with 10 columns (<code>C1, ..., C10</code>) and I want to delete duplicate rows.  </p>\n\n<p>I accidentally used <code>setkey(data,C1)</code>, so now when I run <code>unique(data)</code> I only get unique rows based on the column <code>C1</code>, while I want to remove a row only if it's identical to another one on all the columns <code>C1, ..., C10</code>.<br>\nIs there a way to undo the <code>setkey()</code> operation? I found <a href=\"https://stackoverflow.com/questions/15552181/how-do-you-undo-a-setkey-ordering-in-data-table\">this question</a> but it didn't help to solve my provlem.</p>\n\n<p>PS: I can get around the problem by setting all columns in my <code>data.table</code> as keys with <code>setkeyv(data, paste0(\"C\", 1:10))</code>, but this is not at all an elegant/practical solution.</p>\n"
        },
        {
            "tags": [
                "python",
                "csv"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 9631155,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/0c38927389ec5a15b5a18d6d8c780413?s=128&d=identicon&r=PG&f=1",
                "display_name": "Ma_",
                "link": "https://stackoverflow.com/users/9631155/ma"
            },
            "is_answered": false,
            "view_count": 19,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1523524461,
            "creation_date": 1523468058,
            "last_edit_date": 1523524461,
            "question_id": 49781283,
            "body_markdown": "I have been tasked with calculating 2017 monthly average precipitation for four cities in the United\r\nStates. I have been provided a file (stations.csv) containing station identifiers for the four cities\r\nas well as a URL for accessing the weather data online. My first task is to create a script the accesses\r\nthe monthly weather data for 2017 at each of the stations in the station file and saves the data as\r\nseparate files. This will result in a total of 48 files (4 stations x 12 months).\r\n\r\nHere is what &quot;stations.csv&quot; looks like:\r\n\r\n    KCASANFR131,37.778,-122.408\r\n    KDCWASHI48,38.913,-77.031\r\n    IBRITISH359,49.256,-123.245\r\n    KNYNEWYO639,40.755,-74.007\r\n\r\nI am getting data from: www.underground.com\r\n\r\nSpecifically editing the line: \r\n\r\nhttps://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KMDLAURE5&amp;year=2018&amp;month=2&amp;graphspan=month&amp;format=1\r\n\r\nMy problem is to specifically do this:\r\n\r\nManually create a new directory (right-click, create new folder) in which to save your 48 weather files.\r\nThis is good practice since you want to keep your data separate from your scripts. Save each file into\r\nthe data directory using the format &lt;StationID&gt;&#173;&lt;Month&#160;(with&#160;leading&#160;zero)&gt;&#173;&lt;Year&gt;.csv\r\n\r\nExample:&#160;KDCWASHI48&#173;-04-&#173;2017.csv\r\n\r\nI think I am close to that but not quite saving each month&#39;s temperature data. After I have that temperature data I need to save that into a file and then send that file into a directory file that I made.\r\n\r\nHere is my code thus far:\r\n\r\n\r\n    import urllib\r\n    \r\n    \r\n    def accessData(Id, Month):\r\n        url = &quot;https://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=&quot; + str(Id) + &quot;&amp;year=2017&amp;month=&quot; + str(Month) + &quot;&amp;graphspan=month&amp;format=1&quot;\r\n        infile = urllib.urlopen(url)\r\n        readLineByLine = infile.readlines()\r\n        infile.close()\r\n    \r\n        return readLineByLine\r\n    \r\n    \r\n    f = open(&#39;stations.csv&#39;, &#39;r&#39;)\r\n    \r\n    for line in f.readlines():\r\n        vals = line.split(&#39;,&#39;)\r\n    \r\n        for j in range(1,13): # accessing months here from 1 to 12, b/c 13 exclusive\r\n    \r\n            data = accessData(line, j)\r\n    \r\n            filename = &quot;{}-0{}-2017.csv&quot;.format(vals[0], j)\r\n    \r\n            row_count = len(data)\r\n    \r\n            for i in range(2, row_count):\r\n                if(data[i] != &#39;&lt;br&gt;\\n&#39; and data[i] != &#39;\\n&#39;):\r\n                    writeFile = open(filename, &#39;w&#39;)\r\n                    writeFile.write(data[i])\r\n\r\n\r\n\r\n\r\n",
            "link": "https://stackoverflow.com/questions/49781283/downloading-weather-data-from-the-web-cleaning-it-and-then-saving-that-into-a",
            "title": "Downloading weather data from the web, cleaning it, and then saving that into a series of comma separated files?",
            "body": "<p>I have been tasked with calculating 2017 monthly average precipitation for four cities in the United\nStates. I have been provided a file (stations.csv) containing station identifiers for the four cities\nas well as a URL for accessing the weather data online. My first task is to create a script the accesses\nthe monthly weather data for 2017 at each of the stations in the station file and saves the data as\nseparate files. This will result in a total of 48 files (4 stations x 12 months).</p>\n\n<p>Here is what \"stations.csv\" looks like:</p>\n\n<pre><code>KCASANFR131,37.778,-122.408\nKDCWASHI48,38.913,-77.031\nIBRITISH359,49.256,-123.245\nKNYNEWYO639,40.755,-74.007\n</code></pre>\n\n<p>I am getting data from: www.underground.com</p>\n\n<p>Specifically editing the line: </p>\n\n<p><a href=\"https://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KMDLAURE5&amp;year=2018&amp;month=2&amp;graphspan=month&amp;format=1\" rel=\"nofollow noreferrer\">https://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KMDLAURE5&amp;year=2018&amp;month=2&amp;graphspan=month&amp;format=1</a></p>\n\n<p>My problem is to specifically do this:</p>\n\n<p>Manually create a new directory (right-click, create new folder) in which to save your 48 weather files.\nThis is good practice since you want to keep your data separate from your scripts. Save each file into\nthe data directory using the format ­­.csv</p>\n\n<p>Example: KDCWASHI48­-04-­2017.csv</p>\n\n<p>I think I am close to that but not quite saving each month's temperature data. After I have that temperature data I need to save that into a file and then send that file into a directory file that I made.</p>\n\n<p>Here is my code thus far:</p>\n\n<pre><code>import urllib\n\n\ndef accessData(Id, Month):\n    url = \"https://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=\" + str(Id) + \"&amp;year=2017&amp;month=\" + str(Month) + \"&amp;graphspan=month&amp;format=1\"\n    infile = urllib.urlopen(url)\n    readLineByLine = infile.readlines()\n    infile.close()\n\n    return readLineByLine\n\n\nf = open('stations.csv', 'r')\n\nfor line in f.readlines():\n    vals = line.split(',')\n\n    for j in range(1,13): # accessing months here from 1 to 12, b/c 13 exclusive\n\n        data = accessData(line, j)\n\n        filename = \"{}-0{}-2017.csv\".format(vals[0], j)\n\n        row_count = len(data)\n\n        for i in range(2, row_count):\n            if(data[i] != '&lt;br&gt;\\n' and data[i] != '\\n'):\n                writeFile = open(filename, 'w')\n                writeFile.write(data[i])\n</code></pre>\n"
        },
        {
            "tags": [
                "spring-boot",
                "java-8",
                "mapping",
                "orika"
            ],
            "owner": {
                "reputation": 97,
                "user_id": 5446273,
                "user_type": "registered",
                "accept_rate": 75,
                "profile_image": "https://www.gravatar.com/avatar/2e539922e707c005c65e5d5911b7503c?s=128&d=identicon&r=PG&f=1",
                "display_name": "JavaDeveloper",
                "link": "https://stackoverflow.com/users/5446273/javadeveloper"
            },
            "is_answered": false,
            "view_count": 23,
            "bounty_amount": 50,
            "bounty_closes_date": 1524104195,
            "answer_count": 1,
            "score": 2,
            "last_activity_date": 1523524455,
            "creation_date": 1523243322,
            "last_edit_date": 1523278484,
            "question_id": 49725000,
            "body_markdown": "I have created a class to copy bean properties using Orika Mapper API in spring boot application as shown below:\r\n\r\n    public class ObjectMapper {\r\n    \r\n    \tprivate static MapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();\r\n    \t\r\n    \tpublic static ClientEntity toClientEntity(ClientDTO clientDTO) {\r\n    \t\tBoundMapperFacade&lt;ClientDTO, ClientEntity&gt; boundMapper = mapperFactory.getMapperFacade(ClientDTO.class, ClientEntity.class);\r\n    \t\treturn boundMapper.map(clientDTO);\r\n    \t}\t\r\n    \t\r\n    \tpublic static UserEntity toUserEntity(UserDTO userDTO) {\r\n    \t\tmapperFactory.getConverterFactory().registerConverter(new PassThroughConverter(LocalDate.class));\r\n    \t\tmapperFactory.getConverterFactory().registerConverter(new PassThroughConverter(LocalTime.class));\r\n    \t\tBoundMapperFacade&lt;UserDTO, UserEntity&gt; boundMapper = mapperFactory.getMapperFacade(UserDTO.class, UserEntity.class);\r\n    \t\treturn boundMapper.map(userDTO);\r\n    \t}\r\n    }\r\n\r\nUserEntity &amp; UserDTO POJO classes have JAVA 8 LocalDate and LocalTime properties so have registeredConverters for mapperFactory. This works fine for first time but on consecutive call it throws the below exception :\r\n\r\n    java.lang.IllegalStateException: Cannot register converters after MapperFacade has been initialized\r\n    \tat ma.glasnost.orika.converter.DefaultConverterFactory.registerConverter(DefaultConverterFactory.java:192) ~[orika-core-1.4.6.jar:na]\r\n    \tat ma.glasnost.orika.impl.DefaultMapperFactory$ConverterFactoryFacade.registerConverter(DefaultMapperFactory.java:1614) ~[orika-core-1.4.6.jar:na]\r\n\r\nI understand this is because converters are being registered after MapperFacade is initialized. How to resolve this issue? How to register converters before initialization?",
            "link": "https://stackoverflow.com/questions/49725000/orika-mapper-cannot-register-converters-after-mapperfacade-has-been-initialize",
            "title": "Orika Mapper - Cannot register converters after MapperFacade has been initialized",
            "body": "<p>I have created a class to copy bean properties using Orika Mapper API in spring boot application as shown below:</p>\n\n<pre><code>public class ObjectMapper {\n\n    private static MapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();\n\n    public static ClientEntity toClientEntity(ClientDTO clientDTO) {\n        BoundMapperFacade&lt;ClientDTO, ClientEntity&gt; boundMapper = mapperFactory.getMapperFacade(ClientDTO.class, ClientEntity.class);\n        return boundMapper.map(clientDTO);\n    }   \n\n    public static UserEntity toUserEntity(UserDTO userDTO) {\n        mapperFactory.getConverterFactory().registerConverter(new PassThroughConverter(LocalDate.class));\n        mapperFactory.getConverterFactory().registerConverter(new PassThroughConverter(LocalTime.class));\n        BoundMapperFacade&lt;UserDTO, UserEntity&gt; boundMapper = mapperFactory.getMapperFacade(UserDTO.class, UserEntity.class);\n        return boundMapper.map(userDTO);\n    }\n}\n</code></pre>\n\n<p>UserEntity &amp; UserDTO POJO classes have JAVA 8 LocalDate and LocalTime properties so have registeredConverters for mapperFactory. This works fine for first time but on consecutive call it throws the below exception :</p>\n\n<pre><code>java.lang.IllegalStateException: Cannot register converters after MapperFacade has been initialized\n    at ma.glasnost.orika.converter.DefaultConverterFactory.registerConverter(DefaultConverterFactory.java:192) ~[orika-core-1.4.6.jar:na]\n    at ma.glasnost.orika.impl.DefaultMapperFactory$ConverterFactoryFacade.registerConverter(DefaultMapperFactory.java:1614) ~[orika-core-1.4.6.jar:na]\n</code></pre>\n\n<p>I understand this is because converters are being registered after MapperFacade is initialized. How to resolve this issue? How to register converters before initialization?</p>\n"
        },
        {
            "tags": [
                "java",
                "dto",
                "modelmapper"
            ],
            "owner": {
                "reputation": 2821,
                "user_id": 999353,
                "user_type": "registered",
                "accept_rate": 51,
                "profile_image": "https://www.gravatar.com/avatar/98bced27aa499af81f823b998d23c79d?s=128&d=identicon&r=PG",
                "display_name": "TheCoder",
                "link": "https://stackoverflow.com/users/999353/thecoder"
            },
            "is_answered": false,
            "view_count": 15,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1523524455,
            "creation_date": 1523518768,
            "question_id": 49790651,
            "body_markdown": "I am mapping a Dto to a domain object. The domain is immutable and therefore has no no-arg constructor, which ModelMapper complains about.\r\n\r\nIs there anyway for to make ModelMapper construct the object via a constructor and not setters?\r\n\r\nMy Dto has 6 member variables but my domain has 2 less (same names and types) so I&#39;m guessing constructor creation might not be straightforward.\r\n\r\n",
            "link": "https://stackoverflow.com/questions/49790651/modelmapper-dto-to-immutable",
            "title": "ModelMapper - DTO to Immutable",
            "body": "<p>I am mapping a Dto to a domain object. The domain is immutable and therefore has no no-arg constructor, which ModelMapper complains about.</p>\n\n<p>Is there anyway for to make ModelMapper construct the object via a constructor and not setters?</p>\n\n<p>My Dto has 6 member variables but my domain has 2 less (same names and types) so I'm guessing constructor creation might not be straightforward.</p>\n"
        },
        {
            "tags": [
                "angular",
                "api",
                "typescript"
            ],
            "owner": {
                "reputation": 269,
                "user_id": 3732502,
                "user_type": "registered",
                "accept_rate": 68,
                "profile_image": "https://i.stack.imgur.com/epV4F.jpg?s=128&g=1",
                "display_name": "Sanjeev S",
                "link": "https://stackoverflow.com/users/3732502/sanjeev-s"
            },
            "is_answered": false,
            "view_count": 17,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1523524447,
            "creation_date": 1523524447,
            "question_id": 49792586,
            "body_markdown": "`ng2-auto-complete` works differently in the timeout function in the Angular and Typescript. The `setTimeout()` function is required because it needed to retrieve data from the API. If we call the function on `ngOninit` works differently in timeout and non timeout conditions.\r\n\r\nWe try to set a value for auto complete textbox. Without any timeout function autocomplete works as per the expected. But it takes little time to get data from API. So we use small timeout. We get the data but its bind and show as below. Please correct me if I did anything wrong and suggest me a solution\r\n\r\n    [object Object]\r\n\r\n[Plunkr][1]\r\n\r\n\r\n  [1]: http://plnkr.co/edit/FAlPL99RogKaGtlAjDPZ?p=preview",
            "link": "https://stackoverflow.com/questions/49792586/ng2-auto-complete-works-differently-on-the-timeout-function",
            "title": "ng2-auto-complete works differently on the timeout function",
            "body": "<p><code>ng2-auto-complete</code> works differently in the timeout function in the Angular and Typescript. The <code>setTimeout()</code> function is required because it needed to retrieve data from the API. If we call the function on <code>ngOninit</code> works differently in timeout and non timeout conditions.</p>\n\n<p>We try to set a value for auto complete textbox. Without any timeout function autocomplete works as per the expected. But it takes little time to get data from API. So we use small timeout. We get the data but its bind and show as below. Please correct me if I did anything wrong and suggest me a solution</p>\n\n<pre><code>[object Object]\n</code></pre>\n\n<p><a href=\"http://plnkr.co/edit/FAlPL99RogKaGtlAjDPZ?p=preview\" rel=\"nofollow noreferrer\">Plunkr</a></p>\n"
        },
        {
            "tags": [
                "tomcat8",
                "illegalargumentexception"
            ],
            "owner": {
                "reputation": 146,
                "user_id": 2016012,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/b786297ab07185d851992b9c2759ec0c?s=128&d=identicon&r=PG",
                "display_name": "user2016012",
                "link": "https://stackoverflow.com/users/2016012/user2016012"
            },
            "is_answered": true,
            "view_count": 43516,
            "answer_count": 2,
            "score": 29,
            "last_activity_date": 1523524443,
            "creation_date": 1487048559,
            "question_id": 42218237,
            "body_markdown": "I am getting below stack trace when I am deploying my application in a multi-server Apache Tomcat 8 environment. I am getting this error frequently, and it seems it is blocking the tomcat thread:\r\n\r\n    INFO [http-nio-80-exec-4461] org.apache.coyote.http11.AbstractHttp11Processor.process Error parsing HTTP request header\r\n    &#160;Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.\r\n    &#160;java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens\r\n    &#160;at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:233)\r\n    &#160;at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1017)\r\n    &#160;at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)\r\n    &#160;at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1524)\r\n    &#160;at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480)\r\n    &#160;at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n    &#160;at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n    &#160;at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\r\n    &#160;at java.lang.Thread.run(Unknown Source)\r\n\r\nCan any one direct me how to troubleshoot or narrow down such an exeption? I am not getting any reference to any of my application source files. I tried to google around, and in of the links it said, you are trying to access http url through https, which seems unlikely. I am not getting this error, when the application runs on a single Tomcat 8 instance. I get this only in a multi-server environment.\r\n\r\nI am also sharing the meta tags I have embedded on each page, if that helps to identify the cause.\r\n\r\n    &lt;%\r\n    \tresponse.setHeader(&quot;Cache-Control&quot;, &quot;no-cache&quot;);\r\n    \tresponse.setHeader(&quot;Cache-Control&quot;, &quot;no-store&quot;);\r\n    \tresponse.setDateHeader(&quot;Expires&quot;, 0);\r\n    \tresponse.setHeader(&quot;Pragma&quot;, &quot;no-cache&quot;);\r\n    %&gt;\r\n\r\n\r\n    &lt;head&gt;\r\n    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;\r\n    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, minimum-scale=1.0, maximum-scale=1.0&quot;&gt;\r\n    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;\r\n\r\n\r\n\r\nI am also using the following in a few pages, which basically is same as above:\r\n\r\n    &lt;meta charset=&quot;utf-8&quot;&gt;\r\n    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;\r\n    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;\r\n    &lt;meta http-equiv=&quot;Expires&quot; content=&quot;-1&quot; /&gt;\r\n    &lt;meta http-equiv=&quot;Cache-Control&quot; content=&quot;private&quot; /&gt;\r\n    &lt;meta http-equiv=&quot;Cache-Control&quot; content=&quot;no-store&quot; /&gt;\r\n    &lt;meta http-equiv=&quot;Pragma&quot; content=&quot;no-cache&quot; /&gt;\r\n\r\nEven if anyone helps in giving a direction to my troubleshooting attempt, that will be useful, as currently I have no idea, where to look into.\r\n\r\nThanks in advance.\r\n",
            "link": "https://stackoverflow.com/questions/42218237/java-lang-illegalargumentexception-invalid-character-found-in-method-name-http",
            "title": "java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens",
            "body": "<p>I am getting below stack trace when I am deploying my application in a multi-server Apache Tomcat 8 environment. I am getting this error frequently, and it seems it is blocking the tomcat thread:</p>\n\n<pre><code>INFO [http-nio-80-exec-4461] org.apache.coyote.http11.AbstractHttp11Processor.process Error parsing HTTP request header\n Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.\n java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens\n at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:233)\n at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1017)\n at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)\n at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1524)\n at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480)\n at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n at java.lang.Thread.run(Unknown Source)\n</code></pre>\n\n<p>Can any one direct me how to troubleshoot or narrow down such an exeption? I am not getting any reference to any of my application source files. I tried to google around, and in of the links it said, you are trying to access http url through https, which seems unlikely. I am not getting this error, when the application runs on a single Tomcat 8 instance. I get this only in a multi-server environment.</p>\n\n<p>I am also sharing the meta tags I have embedded on each page, if that helps to identify the cause.</p>\n\n<pre><code>&lt;%\n    response.setHeader(\"Cache-Control\", \"no-cache\");\n    response.setHeader(\"Cache-Control\", \"no-store\");\n    response.setDateHeader(\"Expires\", 0);\n    response.setHeader(\"Pragma\", \"no-cache\");\n%&gt;\n\n\n&lt;head&gt;\n&lt;meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"&gt;\n&lt;meta name=\"viewport\" content=\"width=device-width, minimum-scale=1.0, maximum-scale=1.0\"&gt;\n&lt;meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"&gt;\n</code></pre>\n\n<p>I am also using the following in a few pages, which basically is same as above:</p>\n\n<pre><code>&lt;meta charset=\"utf-8\"&gt;\n&lt;meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"&gt;\n&lt;meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"&gt;\n&lt;meta http-equiv=\"Expires\" content=\"-1\" /&gt;\n&lt;meta http-equiv=\"Cache-Control\" content=\"private\" /&gt;\n&lt;meta http-equiv=\"Cache-Control\" content=\"no-store\" /&gt;\n&lt;meta http-equiv=\"Pragma\" content=\"no-cache\" /&gt;\n</code></pre>\n\n<p>Even if anyone helps in giving a direction to my troubleshooting attempt, that will be useful, as currently I have no idea, where to look into.</p>\n\n<p>Thanks in advance.</p>\n"
        },
        {
            "tags": [
                "routing",
                "locale",
                "url-redirection",
                "laravel-5.5"
            ],
            "owner": {
                "reputation": 111,
                "user_id": 7544279,
                "user_type": "registered",
                "accept_rate": 70,
                "profile_image": "https://www.gravatar.com/avatar/2d95a8e43c2879da92b1d3f83e6d05d2?s=128&d=identicon&r=PG&f=1",
                "display_name": "Anime",
                "link": "https://stackoverflow.com/users/7544279/anime"
            },
            "is_answered": false,
            "view_count": 5,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1523524436,
            "creation_date": 1523524045,
            "last_edit_date": 1523524436,
            "question_id": 49792436,
            "body_markdown": "I have successfully **set language switcher** in my project. It works very fine some pages but not in some pages.\r\nThis is my language switching **form**:\r\n\r\n    &lt;form id=&quot;language_switcher_form&quot;  action=&quot;language&quot; method=&quot;post&quot;&gt;\r\n    \t&lt;select \tname=&quot;locale&quot; id=&quot;language_switcher&quot;&gt;\r\n    \t\t&lt;option value=&quot;en&quot; {{App::getLocale()==&#39;en&#39;?&#39; selected&#39; : &#39;&#39;}} class=&quot;mt-english&quot;&gt; English&lt;/option&gt;\r\n    \t\t&lt;option value=&quot;np&quot; {{App::getLocale()==&#39;np&#39;?&#39; selected&#39; : &#39;&#39;}}  class=&quot;mt-nepali&quot;&gt;Nepali&lt;/option&gt;\r\n    \t&lt;/select&gt;\r\n    \t{{ csrf_field() }}\r\n    &lt;/form&gt; \r\nMy javascript to submit form is:\r\n\r\n    $( &quot;#language_switcher&quot; ).change(function() {\r\n      $(&quot;#language_switcher_form&quot;).submit();\r\n    });\r\nMy **routes** for language switching is:\r\n\r\n    Route::resource(&#39;properties&#39;, &#39;PropertiesController&#39;);\r\n    Route::post(&#39;/language&#39;, array(\r\n    \t&#39;Middleware&#39;=&gt;&#39;LanguageSwitcher&#39;,\r\n    \t&#39;uses&#39;=&gt;&#39;LanguageController@index&#39;\r\n    ));\r\n\r\nMy **middleware**:\r\n\r\n    &lt;?php\r\n    namespace App\\Http\\Middleware;\r\n    use Closure;\r\n    use App;\r\n    use Illuminate\\Support\\Facades\\Session;\r\n    use Illuminate\\Support\\Facades\\Config;\r\n    \r\n    class LanguageSwitcher\r\n    {\r\n        public function handle($request, Closure $next)\r\n        {\r\n            App::setLocale(Session::has(&#39;locale&#39;)? Session::get(&#39;locale&#39;): Config::get(&#39;app.locale&#39;));\r\n            return $next($request);\r\n        }\r\n    }\r\nMy **language controller** is:\r\n\r\n    &lt;?php\r\n    \r\n    namespace App\\Http\\Controllers;\r\n    \r\n    use Illuminate\\Http\\Request;\r\n    use Illuminate\\Support\\Facades\\Input;\r\n    use Illuminate\\Support\\Facades\\Session;\r\n    use Redirect;\r\n    use App\\Http\\Requests;\r\n    \r\n    class LanguageController extends Controller\r\n    {\r\n    \tpublic function index(){\r\n    \t\tif(!\\Session::has(&#39;locale&#39;)){\r\n    \t\t\t\\Session::put(&#39;locale&#39;, Input::get(&#39;locale&#39;));\r\n    \t\t}\r\n    \t\telse{\r\n    \t\t\tsession([&#39;locale&#39; =&gt; Input::get(&#39;locale&#39;)]);\r\n    \t\t}\r\n    \t\treturn Redirect::back();\r\n    \t}\r\n    }\r\nWhen I try to switch the language from **homepage or http://localhost/myproject/properties** , it **works as expected**. But when I try to do the same from http://localhost/gharsansar/properties/create it redirects me to http://localhost/gharsansar/properties/**language**. Similary for http://localhost/gharsansar/properties/12 it redirects to http://localhost/gharsansar/properties/**language**. What mistake have I made? \r\nIt throws this error.\r\n\r\n&gt; Symfony \\ Component \\ HttpKernel \\ Exception \\\r\n&gt; MethodNotAllowedHttpException No message\r\n\r\nThank you in advance.",
            "link": "https://stackoverflow.com/questions/49792436/laravel-language-switching-not-working-for-some-routes-in-laravel-5-5",
            "title": "Laravel language switching not working for some routes in Laravel 5.5",
            "body": "<p>I have successfully <strong>set language switcher</strong> in my project. It works very fine some pages but not in some pages.\nThis is my language switching <strong>form</strong>:</p>\n\n<pre><code>&lt;form id=\"language_switcher_form\"  action=\"language\" method=\"post\"&gt;\n    &lt;select     name=\"locale\" id=\"language_switcher\"&gt;\n        &lt;option value=\"en\" {{App::getLocale()=='en'?' selected' : ''}} class=\"mt-english\"&gt; English&lt;/option&gt;\n        &lt;option value=\"np\" {{App::getLocale()=='np'?' selected' : ''}}  class=\"mt-nepali\"&gt;Nepali&lt;/option&gt;\n    &lt;/select&gt;\n    {{ csrf_field() }}\n&lt;/form&gt; \n</code></pre>\n\n<p>My javascript to submit form is:</p>\n\n<pre><code>$( \"#language_switcher\" ).change(function() {\n  $(\"#language_switcher_form\").submit();\n});\n</code></pre>\n\n<p>My <strong>routes</strong> for language switching is:</p>\n\n<pre><code>Route::resource('properties', 'PropertiesController');\nRoute::post('/language', array(\n    'Middleware'=&gt;'LanguageSwitcher',\n    'uses'=&gt;'LanguageController@index'\n));\n</code></pre>\n\n<p>My <strong>middleware</strong>:</p>\n\n<pre><code>&lt;?php\nnamespace App\\Http\\Middleware;\nuse Closure;\nuse App;\nuse Illuminate\\Support\\Facades\\Session;\nuse Illuminate\\Support\\Facades\\Config;\n\nclass LanguageSwitcher\n{\n    public function handle($request, Closure $next)\n    {\n        App::setLocale(Session::has('locale')? Session::get('locale'): Config::get('app.locale'));\n        return $next($request);\n    }\n}\n</code></pre>\n\n<p>My <strong>language controller</strong> is:</p>\n\n<pre><code>&lt;?php\n\nnamespace App\\Http\\Controllers;\n\nuse Illuminate\\Http\\Request;\nuse Illuminate\\Support\\Facades\\Input;\nuse Illuminate\\Support\\Facades\\Session;\nuse Redirect;\nuse App\\Http\\Requests;\n\nclass LanguageController extends Controller\n{\n    public function index(){\n        if(!\\Session::has('locale')){\n            \\Session::put('locale', Input::get('locale'));\n        }\n        else{\n            session(['locale' =&gt; Input::get('locale')]);\n        }\n        return Redirect::back();\n    }\n}\n</code></pre>\n\n<p>When I try to switch the language from <strong>homepage or <a href=\"http://localhost/myproject/properties\" rel=\"nofollow noreferrer\">http://localhost/myproject/properties</a></strong> , it <strong>works as expected</strong>. But when I try to do the same from <a href=\"http://localhost/gharsansar/properties/create\" rel=\"nofollow noreferrer\">http://localhost/gharsansar/properties/create</a> it redirects me to <a href=\"http://localhost/gharsansar/properties/\" rel=\"nofollow noreferrer\">http://localhost/gharsansar/properties/</a><strong>language</strong>. Similary for <a href=\"http://localhost/gharsansar/properties/12\" rel=\"nofollow noreferrer\">http://localhost/gharsansar/properties/12</a> it redirects to <a href=\"http://localhost/gharsansar/properties/\" rel=\"nofollow noreferrer\">http://localhost/gharsansar/properties/</a><strong>language</strong>. What mistake have I made? \nIt throws this error.</p>\n\n<blockquote>\n  <p>Symfony \\ Component \\ HttpKernel \\ Exception \\\n  MethodNotAllowedHttpException No message</p>\n</blockquote>\n\n<p>Thank you in advance.</p>\n"
        },
        {
            "tags": [
                "excel",
                "charts",
                "filter",
                "pivot"
            ],
            "owner": {
                "reputation": 3,
                "user_id": 8085149,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/113d72e439d659bf0d199847bd4384c9?s=128&d=identicon&r=PG&f=1",
                "display_name": "Henning",
                "link": "https://stackoverflow.com/users/8085149/henning"
            },
            "is_answered": false,
            "view_count": 11,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1523524435,
            "creation_date": 1523524435,
            "question_id": 49792583,
            "body_markdown": "I&#180;m using a Pivot Table to create a Pivot Chart.\r\n\r\nThe Pivot Chart has got on the primary axis numbers (bulk) &amp; and on the secondary percentages values (line).\r\n\r\nThe values (in my case projects) are splitted by years (2016/2017). \r\n\r\nIf I&#180;m using a filter e.g. to show only the year 2016 -&gt; The formatting will be deleted. \r\n\r\nHow can I fix the formatting? (Pictures in the appendix)\r\n\r\n[Filter two years][1]\r\n\r\n\r\n[Changed Filter to one year][2]\r\n\r\n\r\n  [1]: https://i.stack.imgur.com/XYD6M.png\r\n  [2]: https://i.stack.imgur.com/hx2Ck.png",
            "link": "https://stackoverflow.com/questions/49792583/excel-pivot-chart-filter",
            "title": "Excel Pivot Chart Filter",
            "body": "<p>I´m using a Pivot Table to create a Pivot Chart.</p>\n\n<p>The Pivot Chart has got on the primary axis numbers (bulk) &amp; and on the secondary percentages values (line).</p>\n\n<p>The values (in my case projects) are splitted by years (2016/2017). </p>\n\n<p>If I´m using a filter e.g. to show only the year 2016 -> The formatting will be deleted. </p>\n\n<p>How can I fix the formatting? (Pictures in the appendix)</p>\n\n<p><a href=\"https://i.stack.imgur.com/XYD6M.png\" rel=\"nofollow noreferrer\">Filter two years</a></p>\n\n<p><a href=\"https://i.stack.imgur.com/hx2Ck.png\" rel=\"nofollow noreferrer\">Changed Filter to one year</a></p>\n"
        },
        {
            "tags": [
                "ansible"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 9539994,
                "user_type": "registered",
                "profile_image": "https://lh5.googleusercontent.com/-hiK5fDopvrA/AAAAAAAAAAI/AAAAAAAAAls/x_Mg5pIBtG0/photo.jpg?sz=128",
                "display_name": "mujahed alwagia",
                "link": "https://stackoverflow.com/users/9539994/mujahed-alwagia"
            },
            "is_answered": false,
            "view_count": 8,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1523524434,
            "creation_date": 1523523820,
            "last_edit_date": 1523524434,
            "question_id": 49792354,
            "body_markdown": "I&#39;ve just started to use Ansible to automate binary deployments. \r\n\r\nWhen downloading the zip files and trying to unzip it by passing the downloaded zip files as variable to be unzipped/unarchived but an error is always thrown.\r\n\r\nSnippet of the YML below:\r\n \r\n    - name: Download binaries\r\n      get_url:\r\n        url={{ download_server }}\r\n        url_username={{ username }}\r\n        url_password={{ passwd }}\r\n        dest={{ base_dir }}\r\n      register: bin_files\r\n\r\n    - set_fact:\r\n      my_unzipped_file: &quot;{{ bin_files[0].stdout }}&quot;\r\n\t  \r\n    - name: UNZIPPING the files\r\n      unarchive: src={{ base_dir }}/{{ item }} dest={{ base_dir }} copy=no\r\n      with_items: my_unzipped_file",
            "link": "https://stackoverflow.com/questions/49792354/pass-get-url-downloaded-zip-files-as-variable-to-unarchive",
            "title": "Pass get_url downloaded zip files as variable to unarchive",
            "body": "<p>I've just started to use Ansible to automate binary deployments. </p>\n\n<p>When downloading the zip files and trying to unzip it by passing the downloaded zip files as variable to be unzipped/unarchived but an error is always thrown.</p>\n\n<p>Snippet of the YML below:</p>\n\n<pre><code>- name: Download binaries\n  get_url:\n    url={{ download_server }}\n    url_username={{ username }}\n    url_password={{ passwd }}\n    dest={{ base_dir }}\n  register: bin_files\n\n- set_fact:\n  my_unzipped_file: \"{{ bin_files[0].stdout }}\"\n\n- name: UNZIPPING the files\n  unarchive: src={{ base_dir }}/{{ item }} dest={{ base_dir }} copy=no\n  with_items: my_unzipped_file\n</code></pre>\n"
        },
        {
            "tags": [
                "angular",
                "visual-studio-2017",
                "angular2-routing"
            ],
            "owner": {
                "reputation": 6,
                "user_id": 9157023,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/f9e695620267fe71bac563eebda80e3d?s=128&d=identicon&r=PG&f=1",
                "display_name": "vish G",
                "link": "https://stackoverflow.com/users/9157023/vish-g"
            },
            "is_answered": false,
            "view_count": 16,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1523524434,
            "creation_date": 1522752110,
            "last_edit_date": 1523524434,
            "question_id": 49628045,
            "body_markdown": "I have below code which is working fine in all browsers upon launching the application except while refreshing the page, immediately I&#39;m getting HTTP 404-Not Found Issue. In angular, don&#39;t know the exact reason and solution.\r\n\r\nFollowing are my components in my application:\r\n\r\n**app.component.ts**\r\n\r\n    import { Component } from &#39;@angular/core&#39;;\r\n    @Component({\r\n    selector: &#39;my-app&#39;,\r\n    templateUrl: &#39;./main.html&#39;,\r\n    })\r\n    export class AppComponent { }\r\n\r\n**main.html**\r\n\r\n    &lt;div&gt;\r\n    &lt;nav&gt;\r\n        &lt;ul class=&quot; nav nav-pills&quot;&gt;\r\n            &lt;li routerLinkActive=&quot;active&quot;&gt; &lt;a \r\n     routerLink=&quot;/checkifc&quot;&gt;checkifc&lt;/a&gt;&lt;/li&gt;\r\n            &lt;li routerLinkActive=&quot;active&quot;&gt;&lt;a \r\n     routerLink=&quot;checkmaterial&quot;&gt;checkmaterial&lt;/a&gt;\r\n            &lt;li routerLinkActive=&quot;active&quot;&gt;&lt;a \r\n     routerLink=&quot;checkcosts&quot;&gt;checkcosts&lt;/a&gt;\r\n        &lt;/ul&gt;\r\n\r\n        &lt;router-outlet&gt;&lt;/router-outlet&gt;\r\n\r\n     &lt;/nav&gt;\r\n    &lt;/div&gt;\r\n\r\n**app.routes.ts**\r\n\r\n    import { Routes, RouterModule } from &#39;@angular/router&#39;;\r\n    import { AppComponent } from &#39;./app.component&#39;;\r\n    import { CheckifcComponent } from &#39;./checkifc/checkifc.component&#39;;\r\n    import { CheckmaterialComponent } from \r\n    &#39;./checkmaterial/checkmaterial.component&#39;;\r\n    import { CheckcostsComponent } from &#39;./checkcosts/checkcosts.component&#39;;\r\n\r\n    export const routes: Routes = [\r\n    { path: &#39;checkifc&#39;, component: CheckifcComponent },\r\n    { path: &#39;checkmaterial&#39;, component: CheckmaterialComponent },\r\n    { path: &#39;checkcosts&#39;, component: CheckcostsComponent },\r\n    //{ path: &#39;&#39;, redirectTo: &#39;/checkifc&#39;, pathMatch: &#39;full&#39; }];\r\n\r\n    export const routing = RouterModule.forRoot(routes);\r\n\r\n**app.module.ts**\r\n\r\n    import { NgModule } from &#39;@angular/core&#39;;\r\n    import { BrowserModule } from &#39;@angular/platform-browser&#39;;\r\n    import { HttpModule, Http, Response } from &#39;@angular/http&#39;;\r\n    import { FormsModule } from &#39;@angular/forms&#39;;\r\n    import { routing } from &#39;./app.routes&#39;;\r\n    import { AppComponent } from &#39;./app.component&#39;;\r\n    import { CheckifcComponent } from &#39;./checkifc/checkifc.component&#39;;\r\n    import { CheckmaterialComponent} from \r\n     &#39;./checkmaterial/checkmaterial.component&#39;;\r\n     import { CheckcostsComponent } from &#39;./checkcosts/checkcosts.component&#39;;\r\n     import{ ifcobjecttypeComponent} from &#39;./ifcobjectType.component&#39;\r\n\r\n     @NgModule({\r\n    imports: [BrowserModule, routing , FormsModule, HttpModule,],\r\n    declarations: [AppComponent, CheckifcComponent, CheckmaterialComponent, \r\n     CheckcostsComponent, ifcobjecttypeComponent ],\r\n    bootstrap: [AppComponent]})\r\n     export class AppModule { }\r\n\r\nfollowing are the components where routing is implemented for\r\n\r\n**checkifc.component.ts**\r\n\r\n    import { Component, OnInit} from &#39;@angular/core&#39;;\r\n    import { Ifc } from &#39;./ifc&#39;;\r\n    import { BimService } from &#39;./bimifc.service&#39;;\r\n\r\n    @Component({\r\n    selector: &#39;checkifc&#39;,\r\n    templateUrl: &#39;./checkifc.html&#39;,\r\n    providers: [BimService]})\r\n\r\n    //implementing the class OnInit\r\n    export class CheckifcComponent implements OnInit {\r\n    ifcprops: Ifc[];}\r\n\r\n**checkifc.html**\r\n\r\n**checkcosts.component.ts**\r\n    \r\n    import { Component, OnInit } from &#39;@angular/core&#39;;\r\n    import { Costs } from &#39;./costs&#39;;\r\n    import { BimService } from &#39;./bimcosts.service&#39;;\r\n\r\n    @Component({\r\n    selector: &#39;checkcosts&#39;,\r\n    templateUrl: &#39;./checkcosts.html&#39;,\r\n    providers: [BimService]})\r\n\r\n     export class CheckcostsComponent implements OnInit {\r\n    checkCost: Costs[];}\r\n\r\n**checkmaterial.component.ts**\r\n \r\n    import { Component, OnInit } from &#39;@angular/core&#39;;\r\n    import { Material } from &#39;./material&#39;;\r\n    import { BimService } from &#39;./bim.service&#39;;\r\n\r\n     @Component({\r\n    selector: &#39;checkmaterial&#39;,\r\n    templateUrl: &#39;./checkmaterial.html&#39;,\r\n    providers: [BimService]})\r\n\r\n    export class CheckmaterialComponent implements OnInit {\r\n    AmtofMaterial: Material[];}\r\n\r\n\r\nI am successfully able to debug the application and navigate between the components by loading respective components &amp; HTML pages but HTTP Error 404.0 - Not Found is displaying while I am refreshing the page or URL.\r\n\r\nImplemented angular2 in Visualstudio 2017.\r\n\r\nAlso, from the blogs, I found some solution like add rewrite rules in web.config file. there is No fix to my issue even after adding rewrite rules.\r\n\r\nYour inputs are most appreciable!! Thanks in advance.",
            "link": "https://stackoverflow.com/questions/49628045/angular-2-routing-visual-studio-2017-getting-http-error-404-0-not-found-whe",
            "title": "Angular 2 Routing - Visual studio 2017, getting HTTP Error 404.0 - Not Found when refreshing the url in browser",
            "body": "<p>I have below code which is working fine in all browsers upon launching the application except while refreshing the page, immediately I'm getting HTTP 404-Not Found Issue. In angular, don't know the exact reason and solution.</p>\n\n<p>Following are my components in my application:</p>\n\n<p><strong>app.component.ts</strong></p>\n\n<pre><code>import { Component } from '@angular/core';\n@Component({\nselector: 'my-app',\ntemplateUrl: './main.html',\n})\nexport class AppComponent { }\n</code></pre>\n\n<p><strong>main.html</strong></p>\n\n<pre><code>&lt;div&gt;\n&lt;nav&gt;\n    &lt;ul class=\" nav nav-pills\"&gt;\n        &lt;li routerLinkActive=\"active\"&gt; &lt;a \n routerLink=\"/checkifc\"&gt;checkifc&lt;/a&gt;&lt;/li&gt;\n        &lt;li routerLinkActive=\"active\"&gt;&lt;a \n routerLink=\"checkmaterial\"&gt;checkmaterial&lt;/a&gt;\n        &lt;li routerLinkActive=\"active\"&gt;&lt;a \n routerLink=\"checkcosts\"&gt;checkcosts&lt;/a&gt;\n    &lt;/ul&gt;\n\n    &lt;router-outlet&gt;&lt;/router-outlet&gt;\n\n &lt;/nav&gt;\n&lt;/div&gt;\n</code></pre>\n\n<p><strong>app.routes.ts</strong></p>\n\n<pre><code>import { Routes, RouterModule } from '@angular/router';\nimport { AppComponent } from './app.component';\nimport { CheckifcComponent } from './checkifc/checkifc.component';\nimport { CheckmaterialComponent } from \n'./checkmaterial/checkmaterial.component';\nimport { CheckcostsComponent } from './checkcosts/checkcosts.component';\n\nexport const routes: Routes = [\n{ path: 'checkifc', component: CheckifcComponent },\n{ path: 'checkmaterial', component: CheckmaterialComponent },\n{ path: 'checkcosts', component: CheckcostsComponent },\n//{ path: '', redirectTo: '/checkifc', pathMatch: 'full' }];\n\nexport const routing = RouterModule.forRoot(routes);\n</code></pre>\n\n<p><strong>app.module.ts</strong></p>\n\n<pre><code>import { NgModule } from '@angular/core';\nimport { BrowserModule } from '@angular/platform-browser';\nimport { HttpModule, Http, Response } from '@angular/http';\nimport { FormsModule } from '@angular/forms';\nimport { routing } from './app.routes';\nimport { AppComponent } from './app.component';\nimport { CheckifcComponent } from './checkifc/checkifc.component';\nimport { CheckmaterialComponent} from \n './checkmaterial/checkmaterial.component';\n import { CheckcostsComponent } from './checkcosts/checkcosts.component';\n import{ ifcobjecttypeComponent} from './ifcobjectType.component'\n\n @NgModule({\nimports: [BrowserModule, routing , FormsModule, HttpModule,],\ndeclarations: [AppComponent, CheckifcComponent, CheckmaterialComponent, \n CheckcostsComponent, ifcobjecttypeComponent ],\nbootstrap: [AppComponent]})\n export class AppModule { }\n</code></pre>\n\n<p>following are the components where routing is implemented for</p>\n\n<p><strong>checkifc.component.ts</strong></p>\n\n<pre><code>import { Component, OnInit} from '@angular/core';\nimport { Ifc } from './ifc';\nimport { BimService } from './bimifc.service';\n\n@Component({\nselector: 'checkifc',\ntemplateUrl: './checkifc.html',\nproviders: [BimService]})\n\n//implementing the class OnInit\nexport class CheckifcComponent implements OnInit {\nifcprops: Ifc[];}\n</code></pre>\n\n<p><strong>checkifc.html</strong></p>\n\n<p><strong>checkcosts.component.ts</strong></p>\n\n<pre><code>import { Component, OnInit } from '@angular/core';\nimport { Costs } from './costs';\nimport { BimService } from './bimcosts.service';\n\n@Component({\nselector: 'checkcosts',\ntemplateUrl: './checkcosts.html',\nproviders: [BimService]})\n\n export class CheckcostsComponent implements OnInit {\ncheckCost: Costs[];}\n</code></pre>\n\n<p><strong>checkmaterial.component.ts</strong></p>\n\n<pre><code>import { Component, OnInit } from '@angular/core';\nimport { Material } from './material';\nimport { BimService } from './bim.service';\n\n @Component({\nselector: 'checkmaterial',\ntemplateUrl: './checkmaterial.html',\nproviders: [BimService]})\n\nexport class CheckmaterialComponent implements OnInit {\nAmtofMaterial: Material[];}\n</code></pre>\n\n<p>I am successfully able to debug the application and navigate between the components by loading respective components &amp; HTML pages but HTTP Error 404.0 - Not Found is displaying while I am refreshing the page or URL.</p>\n\n<p>Implemented angular2 in Visualstudio 2017.</p>\n\n<p>Also, from the blogs, I found some solution like add rewrite rules in web.config file. there is No fix to my issue even after adding rewrite rules.</p>\n\n<p>Your inputs are most appreciable!! Thanks in advance.</p>\n"
        },
        {
            "tags": [
                "mysql",
                "laravel",
                "laravel-4",
                "amazon-rds",
                "database-performance"
            ],
            "owner": {
                "reputation": 940,
                "user_id": 1260819,
                "user_type": "registered",
                "accept_rate": 63,
                "profile_image": "https://www.gravatar.com/avatar/3570bf91a3dab72a7823cbb97a714c80?s=128&d=identicon&r=PG",
                "display_name": "Ankit",
                "link": "https://stackoverflow.com/users/1260819/ankit"
            },
            "is_answered": false,
            "view_count": 41,
            "bounty_amount": 50,
            "bounty_closes_date": 1524036765,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1523524425,
            "creation_date": 1523161259,
            "last_edit_date": 1523433902,
            "question_id": 49714386,
            "body_markdown": "I am facing some very weird issue here. We have a laravel API hosted on AWS EC2 and we using RDS (mysql 5.6). I recently enabled performance_schema on RDS. Following is the behavior I am noticing\r\n\r\n 1. We have two databases on our RDS instance. One for wordpress and one for our laravel API. Wordpress database query are getting digested fine. But queries run from our laravel app are not.\r\n 2. For some reason when I connect MySql Workbench to RDS Instance and executes queries on our Laravel database then they appear in statement summary fine. \r\n 3. I logged into my EC2 machine, connected to MySQL on RDS and executes some queries and they are getting tracked in statement summary.\r\n\r\n\r\n**So it looks like only when queries are executed from our Laravel App, they do not get tracked.** \r\n\r\nOur Laravel version is 4.2. I am trying to identify the reason from last two days, any help will be a relief.\r\n\r\nThe user that I used in all above steps is same and have all privileges on all databases.\r\n\r\n**--EDIT--**\r\n\r\nI performed many other tests and they all point out to only one conclusion that it has something to do with Laravel. I created a simple php file on the same server where laravel is hosted. In this file, I  connected to the same instance/database with same user/password. Only thing I did in this file was to run a very simple Query on $pdo like this.\r\n\r\n    $stmt = $pdo-&gt;query(&#39;SELECT name FROM trades&#39;);\r\n    \t\twhile ($row = $stmt-&gt;fetch())\r\n    \t\t{\r\n    \t\t    echo $row[&#39;name&#39;] . &quot;\\n&quot;;\r\n    \t\t}\r\n\r\nand it appears in query analytics [https://prnt.sc/j3ochd] (I manually checked performance_schema.events_statements_summary_by_digest as well)\r\n\r\nBut then I can hit our laravel api which infact returns the entries from trade table itself ( very much like the query I run above). but that would appear in my query analytics reports ( Percona PMM) or in events_statements_summary_by_digest",
            "link": "https://stackoverflow.com/questions/49714386/laravel-apis-mysql-queries-not-getting-tracked-in-performance-schema-events-sta",
            "title": "Laravel API&#39;s mysql queries not getting tracked in performance_schema.events_statements_summary_by_digest",
            "body": "<p>I am facing some very weird issue here. We have a laravel API hosted on AWS EC2 and we using RDS (mysql 5.6). I recently enabled performance_schema on RDS. Following is the behavior I am noticing</p>\n\n<ol>\n<li>We have two databases on our RDS instance. One for wordpress and one for our laravel API. Wordpress database query are getting digested fine. But queries run from our laravel app are not.</li>\n<li>For some reason when I connect MySql Workbench to RDS Instance and executes queries on our Laravel database then they appear in statement summary fine. </li>\n<li>I logged into my EC2 machine, connected to MySQL on RDS and executes some queries and they are getting tracked in statement summary.</li>\n</ol>\n\n<p><strong>So it looks like only when queries are executed from our Laravel App, they do not get tracked.</strong> </p>\n\n<p>Our Laravel version is 4.2. I am trying to identify the reason from last two days, any help will be a relief.</p>\n\n<p>The user that I used in all above steps is same and have all privileges on all databases.</p>\n\n<p><strong>--EDIT--</strong></p>\n\n<p>I performed many other tests and they all point out to only one conclusion that it has something to do with Laravel. I created a simple php file on the same server where laravel is hosted. In this file, I  connected to the same instance/database with same user/password. Only thing I did in this file was to run a very simple Query on $pdo like this.</p>\n\n<pre><code>$stmt = $pdo-&gt;query('SELECT name FROM trades');\n        while ($row = $stmt-&gt;fetch())\n        {\n            echo $row['name'] . \"\\n\";\n        }\n</code></pre>\n\n<p>and it appears in query analytics [<a href=\"https://prnt.sc/j3ochd]\" rel=\"nofollow noreferrer\">https://prnt.sc/j3ochd]</a> (I manually checked performance_schema.events_statements_summary_by_digest as well)</p>\n\n<p>But then I can hit our laravel api which infact returns the entries from trade table itself ( very much like the query I run above). but that would appear in my query analytics reports ( Percona PMM) or in events_statements_summary_by_digest</p>\n"
        }
    ],
    "has_more": true,
    "quota_max": 300,
    "quota_remaining": 24
}