{
    "items": [
        {
            "tags": [
                "junit5",
                "test-suite"
            ],
            "owner": {
                "reputation": 6,
                "user_id": 9657064,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/353703a41f43f48bcb36d8754641fcd5?s=128&d=identicon&r=PG&f=1",
                "display_name": "Mauricio Zanon",
                "link": "https://stackoverflow.com/users/9657064/mauricio-zanon"
            },
            "is_answered": false,
            "view_count": 15,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524166414,
            "creation_date": 1524166414,
            "question_id": 49928909,
            "body_markdown": "I have a test suite with multiple test clases in Junit5, one of those clases has some tests that use @RepeatedTest, they do repeat when I run them from that class but not when I run the suite itself, any idea why?",
            "link": "https://stackoverflow.com/questions/49928909/use-repeatedtest-in-a-test-suite",
            "title": "Use @RepeatedTest in a test suite",
            "body": "<p>I have a test suite with multiple test clases in Junit5, one of those clases has some tests that use @RepeatedTest, they do repeat when I run them from that class but not when I run the suite itself, any idea why?</p>\n"
        },
        {
            "tags": [
                "twitter-bootstrap",
                "bootstrap-4",
                "photo-gallery"
            ],
            "owner": {
                "reputation": 6226,
                "user_id": 574122,
                "user_type": "registered",
                "accept_rate": 64,
                "profile_image": "https://www.gravatar.com/avatar/cdee80cac2627edea00e921974867bb0?s=128&d=identicon&r=PG",
                "display_name": "ace",
                "link": "https://stackoverflow.com/users/574122/ace"
            },
            "is_answered": false,
            "view_count": 19,
            "answer_count": 0,
            "score": -1,
            "last_activity_date": 1524166402,
            "creation_date": 1524166402,
            "question_id": 49928904,
            "body_markdown": "Bootstrap 4 has carousal component as documented here:\r\n\r\n [Boostrap 4 Carousal ][1]\r\n\r\n\r\n  [1]: https://getbootstrap.com/docs/4.0/components/carousel/\r\n\r\n\r\nHow can I add the ability to make it native fullscreen with fullscreen icon which if clicked, the photo takes the full device screen and not just within browser window ? It should work on iphone, ipad and Android devices as well desktops.\r\n\r\nAlso what is the meaning of Lightbox in above context?",
            "link": "https://stackoverflow.com/questions/49928904/how-to-make-bootstrap-4-carousal-native-fullscreen",
            "title": "How to make bootstrap 4 carousal native fullscreen?",
            "body": "<p>Bootstrap 4 has carousal component as documented here:</p>\n\n<p><a href=\"https://getbootstrap.com/docs/4.0/components/carousel/\" rel=\"nofollow noreferrer\">Boostrap 4 Carousal </a></p>\n\n<p>How can I add the ability to make it native fullscreen with fullscreen icon which if clicked, the photo takes the full device screen and not just within browser window ? It should work on iphone, ipad and Android devices as well desktops.</p>\n\n<p>Also what is the meaning of Lightbox in above context?</p>\n"
        },
        {
            "tags": [
                ".net",
                "windows-installer",
                "ravendb",
                "ravendb-studio"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 9668170,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/83c98933e2e35b58a5ef46a2176a7238?s=128&d=identicon&r=PG&f=1",
                "display_name": "nano",
                "link": "https://stackoverflow.com/users/9668170/nano"
            },
            "is_answered": false,
            "view_count": 30,
            "answer_count": 2,
            "score": 0,
            "last_activity_date": 1524166392,
            "creation_date": 1524120760,
            "last_edit_date": 1524120994,
            "question_id": 49914522,
            "body_markdown": "I am currently trying to install ravendb on a prod server. The licens file I am using, is the same being used for another test/prod server. \r\n\r\nThe installation seem to chrash all the time when i pass the license file to the installation. \r\n\r\nSomething i found interesting in the log file was this. \r\n\r\n    Action start 08:14:02: OpenLicenseFileChooser.\r\n    MSI (c) (AC:A8) [08:14:02:763]: Invoking remote custom action. DLL: C:\\Users\\prod\\AppData\\Local\\Temp\\MSI7901.tmp, Entrypoint: OpenLicenseFileChooser\r\n    MSI (c) (AC!30) [08:14:04:934]: PROPERTY CHANGE: Adding RAVEN_LICENSE_FILE_PATH property. Its value is &#39;C:\\license.xml&#39;.\r\n    Action ended 08:14:04: OpenLicenseFileChooser. Return value 1.\r\n    MSI (c) (AC:F0) [08:14:04:950]: Doing action: LicenseFileExists\r\n    Action 08:14:04: LicenseFileExists. \r\n    Action start 08:14:04: LicenseFileExists.\r\n    MSI (c) (AC:20) [08:14:04:997]: Invoking remote custom action. DLL: C:\\Users\\prod\\AppData\\Local\\Temp\\MSI81BD.tmp, Entrypoint: LicenseFileExists\r\n    MSI (c) (AC!FC) [08:14:05:231]: PROPERTY CHANGE: Deleting RAVEN_LICENSE_VALID property. Its current value is &#39;False&#39;.\r\n    MSI (c) (AC!FC) [08:14:05:231]: PROPERTY CHANGE: Adding RAVEN_INSTALLER_INFO property. Its value is &#39;Checking existing license file&#39;.\r\n    Action ended 08:14:07: LicenseFileExists. Return value 3.\r\n    DEBUG: Error 2896:  Executing action LicenseFileExists failed.\r\n    The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2896. The arguments are: LicenseFileExists, , \r\n    Action ended 08:14:07: WelcomeDlg. Return value 3.\r\n    MSI (c) (AC:1C) [08:14:07:281]: Doing action: CustomFatalError\r\n    Action 08:14:07: CustomFatalError. \r\n    Action start 08:14:07: CustomFatalError.\r\n\r\nThe path to the license file is correct, so why does it fail? \r\n\r\nIs there some limitation on the number of test/prod server that can use the license file, and if so, how do i check the number of servers that may use this license file?\r\n\r\nAnd if that is not the case, are there any dependencies i am missing? \r\n- Does it need acess to the internet?\r\n- does it need something else installed?\r\n\r\nbesides this I also noticed this line \r\n\r\n&gt;The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2896. The arguments are: LicenseFileExists, , \r\n\r\nwhat could this indicate?\r\n\r\n",
            "link": "https://stackoverflow.com/questions/49914522/the-installer-has-encountered-an-unexpected-error-installing-this-package-err",
            "title": "The installer has encountered an unexpected error installing this package - .Error code 2896",
            "body": "<p>I am currently trying to install ravendb on a prod server. The licens file I am using, is the same being used for another test/prod server. </p>\n\n<p>The installation seem to chrash all the time when i pass the license file to the installation. </p>\n\n<p>Something i found interesting in the log file was this. </p>\n\n<pre><code>Action start 08:14:02: OpenLicenseFileChooser.\nMSI (c) (AC:A8) [08:14:02:763]: Invoking remote custom action. DLL: C:\\Users\\prod\\AppData\\Local\\Temp\\MSI7901.tmp, Entrypoint: OpenLicenseFileChooser\nMSI (c) (AC!30) [08:14:04:934]: PROPERTY CHANGE: Adding RAVEN_LICENSE_FILE_PATH property. Its value is 'C:\\license.xml'.\nAction ended 08:14:04: OpenLicenseFileChooser. Return value 1.\nMSI (c) (AC:F0) [08:14:04:950]: Doing action: LicenseFileExists\nAction 08:14:04: LicenseFileExists. \nAction start 08:14:04: LicenseFileExists.\nMSI (c) (AC:20) [08:14:04:997]: Invoking remote custom action. DLL: C:\\Users\\prod\\AppData\\Local\\Temp\\MSI81BD.tmp, Entrypoint: LicenseFileExists\nMSI (c) (AC!FC) [08:14:05:231]: PROPERTY CHANGE: Deleting RAVEN_LICENSE_VALID property. Its current value is 'False'.\nMSI (c) (AC!FC) [08:14:05:231]: PROPERTY CHANGE: Adding RAVEN_INSTALLER_INFO property. Its value is 'Checking existing license file'.\nAction ended 08:14:07: LicenseFileExists. Return value 3.\nDEBUG: Error 2896:  Executing action LicenseFileExists failed.\nThe installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2896. The arguments are: LicenseFileExists, , \nAction ended 08:14:07: WelcomeDlg. Return value 3.\nMSI (c) (AC:1C) [08:14:07:281]: Doing action: CustomFatalError\nAction 08:14:07: CustomFatalError. \nAction start 08:14:07: CustomFatalError.\n</code></pre>\n\n<p>The path to the license file is correct, so why does it fail? </p>\n\n<p>Is there some limitation on the number of test/prod server that can use the license file, and if so, how do i check the number of servers that may use this license file?</p>\n\n<p>And if that is not the case, are there any dependencies i am missing? \n- Does it need acess to the internet?\n- does it need something else installed?</p>\n\n<p>besides this I also noticed this line </p>\n\n<blockquote>\n  <p>The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2896. The arguments are: LicenseFileExists, , </p>\n</blockquote>\n\n<p>what could this indicate?</p>\n"
        },
        {
            "tags": [
                "python",
                "linux",
                "ubuntu",
                "openssl",
                "pip"
            ],
            "owner": {
                "reputation": 1466,
                "user_id": 5908241,
                "user_type": "registered",
                "accept_rate": 64,
                "profile_image": "https://i.stack.imgur.com/HsWX0.jpg?s=128&g=1",
                "display_name": "Backdoor Cipher",
                "link": "https://stackoverflow.com/users/5908241/backdoor-cipher"
            },
            "is_answered": true,
            "view_count": 8242,
            "answer_count": 7,
            "score": 5,
            "last_activity_date": 1524166392,
            "creation_date": 1481550305,
            "last_edit_date": 1524166392,
            "question_id": 41102299,
            "body_markdown": "I tried to install from pip and keep on getting similar type of errors.\r\n\r\n    $ pip install quandl\r\n    Traceback (most recent call last):\r\n      File &quot;/usr/bin/pip&quot;, line 9, in &lt;module&gt;\r\n        load_entry_point(&#39;pip==1.5.6&#39;, &#39;console_scripts&#39;, &#39;pip&#39;)()\r\n      File &quot;/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py&quot;, line 558, in load_entry_point\r\n        return get_distribution(dist).load_entry_point(group, name)\r\n      File &quot;/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py&quot;, line 2682, in load_entry_point\r\n        return ep.load()\r\n      File &quot;/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py&quot;, line 2355, in load\r\n        return self.resolve()\r\n      File &quot;/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py&quot;, line 2361, in resolve\r\n        module = __import__(self.module_name, fromlist=[&#39;__name__&#39;], level=0)\r\n      File &quot;/usr/lib/python2.7/dist-packages/pip/__init__.py&quot;, line 74, in &lt;module&gt;\r\n        from pip.vcs import git, mercurial, subversion, bazaar  # noqa\r\n      File &quot;/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py&quot;, line 9, in &lt;module&gt;\r\n        from pip.download import path_to_url\r\n      File &quot;/usr/lib/python2.7/dist-packages/pip/download.py&quot;, line 22, in &lt;module&gt;\r\n        import requests, six\r\n      File &quot;/usr/lib/python2.7/dist-packages/requests/__init__.py&quot;, line 53, in &lt;module&gt;\r\n        from .packages.urllib3.contrib import pyopenssl\r\n      File &quot;/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py&quot;, line 53, in &lt;module&gt;\r\n        import OpenSSL.SSL\r\n      File &quot;/home/ubuntu/.local/lib/python2.7/site-packages/OpenSSL/__init__.py&quot;, line 8, in &lt;module&gt;\r\n        from OpenSSL import rand, crypto, SSL\r\n      File &quot;/home/ubuntu/.local/lib/python2.7/site-packages/OpenSSL/SSL.py&quot;, line 112, in &lt;module&gt;\r\n        if _lib.Cryptography_HAS_SSL_ST:\r\n    AttributeError: &#39;module&#39; object has no attribute &#39;Cryptography_HAS_SSL_ST&#39;\r\n\r\nNow even though i tried to install different pip modules iam getting same error.Is there any solution for this ? This was caused due to the unexpected killing of the process while a pip module is being downloaded.\r\n\r\nPlease help me with the necessary steps to rectify this error.\r\n\r\nI tried to install this \r\n\r\n    $ pip install -U cryptography\r\n    Traceback (most recent call last):\r\n      File &quot;/usr/bin/pip&quot;, line 9, in &lt;module&gt;\r\n        load_entry_point(&#39;pip==1.5.6&#39;, &#39;console_scripts&#39;, &#39;pip&#39;)()\r\n      File &quot;/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py&quot;, line 558, in load_entry_point\r\n        return get_distribution(dist).load_entry_point(group, name)\r\n      File &quot;/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py&quot;, line 2682, in load_entry_point\r\n        return ep.load()\r\n      File &quot;/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py&quot;, line 2355, in load\r\n        return self.resolve()\r\n      File &quot;/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py&quot;, line 2361, in resolve\r\n        module = __import__(self.module_name, fromlist=[&#39;__name__&#39;], level=0)\r\n      File &quot;/usr/lib/python2.7/dist-packages/pip/__init__.py&quot;, line 74, in &lt;module&gt;\r\n        from pip.vcs import git, mercurial, subversion, bazaar  # noqa\r\n      File &quot;/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py&quot;, line 9, in &lt;module&gt;\r\n        from pip.download import path_to_url\r\n      File &quot;/usr/lib/python2.7/dist-packages/pip/download.py&quot;, line 22, in &lt;module&gt;\r\n        import requests, six\r\n      File &quot;/usr/lib/python2.7/dist-packages/requests/__init__.py&quot;, line 53, in &lt;module&gt;\r\n        from .packages.urllib3.contrib import pyopenssl\r\n      File &quot;/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py&quot;, line 53, in &lt;module&gt;\r\n        import OpenSSL.SSL\r\n      File &quot;/home/ubuntu/.local/lib/python2.7/site-packages/OpenSSL/__init__.py&quot;, line 8, in &lt;module&gt;\r\n        from OpenSSL import rand, crypto, SSL\r\n      File &quot;/home/ubuntu/.local/lib/python2.7/site-packages/OpenSSL/SSL.py&quot;, line 112, in &lt;module&gt;\r\n        if _lib.Cryptography_HAS_SSL_ST:\r\n    AttributeError: &#39;module&#39; object has no attribute &#39;Cryptography_HAS_SSL_ST&#39;\r\n\r\n",
            "link": "https://stackoverflow.com/questions/41102299/unable-to-install-any-pip-module-module-object-has-no-attribute-cryptography",
            "title": "Unable to install any pip module.&#39;module&#39; object has no attribute &#39;Cryptography_HAS_SSL_ST&#39;",
            "body": "<p>I tried to install from pip and keep on getting similar type of errors.</p>\n\n<pre><code>$ pip install quandl\nTraceback (most recent call last):\n  File \"/usr/bin/pip\", line 9, in &lt;module&gt;\n    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 558, in load_entry_point\n    return get_distribution(dist).load_entry_point(group, name)\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2682, in load_entry_point\n    return ep.load()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2355, in load\n    return self.resolve()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2361, in resolve\n    module = __import__(self.module_name, fromlist=['__name__'], level=0)\n  File \"/usr/lib/python2.7/dist-packages/pip/__init__.py\", line 74, in &lt;module&gt;\n    from pip.vcs import git, mercurial, subversion, bazaar  # noqa\n  File \"/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py\", line 9, in &lt;module&gt;\n    from pip.download import path_to_url\n  File \"/usr/lib/python2.7/dist-packages/pip/download.py\", line 22, in &lt;module&gt;\n    import requests, six\n  File \"/usr/lib/python2.7/dist-packages/requests/__init__.py\", line 53, in &lt;module&gt;\n    from .packages.urllib3.contrib import pyopenssl\n  File \"/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py\", line 53, in &lt;module&gt;\n    import OpenSSL.SSL\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/OpenSSL/__init__.py\", line 8, in &lt;module&gt;\n    from OpenSSL import rand, crypto, SSL\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/OpenSSL/SSL.py\", line 112, in &lt;module&gt;\n    if _lib.Cryptography_HAS_SSL_ST:\nAttributeError: 'module' object has no attribute 'Cryptography_HAS_SSL_ST'\n</code></pre>\n\n<p>Now even though i tried to install different pip modules iam getting same error.Is there any solution for this ? This was caused due to the unexpected killing of the process while a pip module is being downloaded.</p>\n\n<p>Please help me with the necessary steps to rectify this error.</p>\n\n<p>I tried to install this </p>\n\n<pre><code>$ pip install -U cryptography\nTraceback (most recent call last):\n  File \"/usr/bin/pip\", line 9, in &lt;module&gt;\n    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 558, in load_entry_point\n    return get_distribution(dist).load_entry_point(group, name)\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2682, in load_entry_point\n    return ep.load()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2355, in load\n    return self.resolve()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2361, in resolve\n    module = __import__(self.module_name, fromlist=['__name__'], level=0)\n  File \"/usr/lib/python2.7/dist-packages/pip/__init__.py\", line 74, in &lt;module&gt;\n    from pip.vcs import git, mercurial, subversion, bazaar  # noqa\n  File \"/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py\", line 9, in &lt;module&gt;\n    from pip.download import path_to_url\n  File \"/usr/lib/python2.7/dist-packages/pip/download.py\", line 22, in &lt;module&gt;\n    import requests, six\n  File \"/usr/lib/python2.7/dist-packages/requests/__init__.py\", line 53, in &lt;module&gt;\n    from .packages.urllib3.contrib import pyopenssl\n  File \"/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py\", line 53, in &lt;module&gt;\n    import OpenSSL.SSL\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/OpenSSL/__init__.py\", line 8, in &lt;module&gt;\n    from OpenSSL import rand, crypto, SSL\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/OpenSSL/SSL.py\", line 112, in &lt;module&gt;\n    if _lib.Cryptography_HAS_SSL_ST:\nAttributeError: 'module' object has no attribute 'Cryptography_HAS_SSL_ST'\n</code></pre>\n"
        },
        {
            "tags": [
                "php",
                "timestamp"
            ],
            "owner": {
                "reputation": 85,
                "user_id": 2254798,
                "user_type": "registered",
                "accept_rate": 33,
                "profile_image": "https://www.gravatar.com/avatar/f4c42a404034238fae4355241b099425?s=128&d=identicon&r=PG",
                "display_name": "user2254798",
                "link": "https://stackoverflow.com/users/2254798/user2254798"
            },
            "is_answered": true,
            "view_count": 35,
            "answer_count": 2,
            "score": 0,
            "last_activity_date": 1524166391,
            "creation_date": 1524157189,
            "question_id": 49926480,
            "body_markdown": "I&#39;m using API that return date like `2018-04-19 20:32:51.439702` and timestamp like `1524153770.26`.\r\n\r\nIn PHP how to convert date like ``2018-04-19 20:32:51.439702`` to this timetamp like that?",
            "link": "https://stackoverflow.com/questions/49926480/convert-millisecond-date-to-timestamp-in-php",
            "title": "convert millisecond date to timestamp in php",
            "body": "<p>I'm using API that return date like <code>2018-04-19 20:32:51.439702</code> and timestamp like <code>1524153770.26</code>.</p>\n\n<p>In PHP how to convert date like <code>2018-04-19 20:32:51.439702</code> to this timetamp like that?</p>\n"
        },
        {
            "tags": [
                "tensorflow",
                "resnet"
            ],
            "owner": {
                "reputation": 6,
                "user_id": 9642857,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/aabf3cae94c078876bc5d3dc5a23ba5b?s=128&d=identicon&r=PG&f=1",
                "display_name": "ALFS",
                "link": "https://stackoverflow.com/users/9642857/alfs"
            },
            "is_answered": false,
            "view_count": 14,
            "answer_count": 0,
            "score": 1,
            "last_activity_date": 1524166387,
            "creation_date": 1524166387,
            "question_id": 49928901,
            "body_markdown": "I&#39;m trying to run Tensorflow&#39;s &lt;a href=&quot;https://github.com/tensorflow/models/tree/master/official/resnet&quot;&gt;ResNet implementation&lt;/a&gt; on a custom image dataset I have. I have no prior experience with Tensorflow and neural/conv nets, so this has been a learning experience for me as well.\r\n\r\nThere are two examples of the implementation, one for the CIFAR10 dataset and another for the ImageNet dataset. I chose to use CIFAR10&#39;s example as a baseline because it seemed easier to get started and I was already familiar with the CIFAR10 dataset. I ran it on the CIFAR10 dataset following the README file available and managed to switch the data and run it for my own dataset of 32x32 images with relative ease.\r\n\r\nThe problem is, my original dataset contains 512x512 images and I&#39;d like to run it with this original size. I converted the dataset into cifar10&#39;s binary format (maintaining the 512x512 size) and adapted the implementation to try to run it. Namely, I changed the file paths and file names and changed the size constants to reflect the dataset:\r\n\r\n    _HEIGHT = 512\r\n    _WIDTH = 512\r\n    _NUM_CHANNELS = 3\r\n    _DEFAULT_IMAGE_BYTES = _HEIGHT * _WIDTH * _NUM_CHANNELS\r\n    _RECORD_BYTES = _DEFAULT_IMAGE_BYTES + 1\r\n    _NUM_CLASSES = 5\r\n    _NUM_DATA_FILES = 10\r\n\r\n    _NUM_IMAGES = {\r\n        &#39;train&#39;: 1000,\r\n        &#39;validation&#39;: 200,\r\n    }\r\n\r\nHowever, when I try to run a few problems appear. If I try to run it as is, I get the bad memory alloc error below:\r\n\r\n    INFO:tensorflow:Running local_init_op.\r\n    INFO:tensorflow:Done running local_init_op.\r\n    terminate called after throwing an instance of &#39;std::bad_alloc&#39;\r\n    what():  std::bad_alloc\r\n\r\nMy dataset contains more than 1200 images, but if I try to use them all at once my computer runs out of memory and crashes (I&#39;m currently setting up a more resourceful computer to address this issue). Because of this, I was wondering if this still meant that I didn&#39;t have enough memory to run the code with the 512x512 images. I saw that tensorflow uses the batch_size parameter to decide on how many images to buffer\r\n\r\n    dataset = dataset.prefetch(buffer_size=batch_size)\r\n\r\nso I tried reducing the batch size as well, to see if it was a problem in allocating memory for the image buffer. The same error occurs until I get as low as a batch of 16 images. For 8 images, however, this problem no longer appears and instead I get a different error message:\r\n\r\n    INFO:tensorflow:Running local_init_op.\r\n    INFO:tensorflow:Done running local_init_op.\r\n    Traceback (most recent call last):\r\n      File &quot;path-to/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py&quot;, line 1327, in _do_call\r\n    return fn(*args)\r\n      File &quot;path-to/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py&quot;, line 1312, in _run_fn\r\n    options, feed_dict, fetch_list, target_list, run_metadata)\r\n      File &quot;path-to/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py&quot;, line 1420, in _call_tf_sessionrun\r\n    status, run_metadata)\r\n      File &quot;path-to/venv/lib/python3.4/site-packages/tensorflow/python/framework/errors_impl.py&quot;, line 516, in __exit__\r\n    c_api.TF_GetCode(self.status.status))\r\n    tensorflow.python.framework.errors_impl.InvalidArgumentError: logits and labels must be same size: logits_size=[117128,5] labels_size=[8,5]\r\n\t [[Node: softmax_cross_entropy_loss/xentropy = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device=&quot;/job:localhost/replica:0/task:0/device:CPU:0&quot;](softmax_cross_entropy_loss/xentropy/Reshape, softmax_cross_entropy_loss/xentropy/Reshape_1)]]\r\n\r\nIt seems that there is a mismatch between the dataset size and the labels array, but that problem appears only when I try running it on 512x512 images, it works for any batch size on 32x32 images.\r\n\r\n**Finally, my question is,** is there some other parameter I have to change or other adaptation I have to make to run the ResNet CIFAR10 code on my 512x512 dataset? Are these errors somehow related to something I&#39;m doing wrong or there are likely two things I have to address? Any insight on what is causing these errors would be of great help as well.\r\n\r\n**Put briefly, what changes would I have to make to input my own 512x512 dataset into TensorFlow&#39;s ResNet CIFAR10 implementation?**\r\n\r\nThis is my first question at StackOverflow and as I said I&#39;m new to many things in the field of the question, so please, forgive any rookie mistake.\r\n\r\n",
            "link": "https://stackoverflow.com/questions/49928901/tensorflows-resnet-on-custom-image-data",
            "title": "Tensorflow&#39;s ResNet on custom image data",
            "body": "<p>I'm trying to run Tensorflow's <a href=\"https://github.com/tensorflow/models/tree/master/official/resnet\" rel=\"nofollow noreferrer\">ResNet implementation</a> on a custom image dataset I have. I have no prior experience with Tensorflow and neural/conv nets, so this has been a learning experience for me as well.</p>\n\n<p>There are two examples of the implementation, one for the CIFAR10 dataset and another for the ImageNet dataset. I chose to use CIFAR10's example as a baseline because it seemed easier to get started and I was already familiar with the CIFAR10 dataset. I ran it on the CIFAR10 dataset following the README file available and managed to switch the data and run it for my own dataset of 32x32 images with relative ease.</p>\n\n<p>The problem is, my original dataset contains 512x512 images and I'd like to run it with this original size. I converted the dataset into cifar10's binary format (maintaining the 512x512 size) and adapted the implementation to try to run it. Namely, I changed the file paths and file names and changed the size constants to reflect the dataset:</p>\n\n<pre><code>_HEIGHT = 512\n_WIDTH = 512\n_NUM_CHANNELS = 3\n_DEFAULT_IMAGE_BYTES = _HEIGHT * _WIDTH * _NUM_CHANNELS\n_RECORD_BYTES = _DEFAULT_IMAGE_BYTES + 1\n_NUM_CLASSES = 5\n_NUM_DATA_FILES = 10\n\n_NUM_IMAGES = {\n    'train': 1000,\n    'validation': 200,\n}\n</code></pre>\n\n<p>However, when I try to run a few problems appear. If I try to run it as is, I get the bad memory alloc error below:</p>\n\n<pre><code>INFO:tensorflow:Running local_init_op.\nINFO:tensorflow:Done running local_init_op.\nterminate called after throwing an instance of 'std::bad_alloc'\nwhat():  std::bad_alloc\n</code></pre>\n\n<p>My dataset contains more than 1200 images, but if I try to use them all at once my computer runs out of memory and crashes (I'm currently setting up a more resourceful computer to address this issue). Because of this, I was wondering if this still meant that I didn't have enough memory to run the code with the 512x512 images. I saw that tensorflow uses the batch_size parameter to decide on how many images to buffer</p>\n\n<pre><code>dataset = dataset.prefetch(buffer_size=batch_size)\n</code></pre>\n\n<p>so I tried reducing the batch size as well, to see if it was a problem in allocating memory for the image buffer. The same error occurs until I get as low as a batch of 16 images. For 8 images, however, this problem no longer appears and instead I get a different error message:</p>\n\n<pre><code>INFO:tensorflow:Running local_init_op.\nINFO:tensorflow:Done running local_init_op.\nTraceback (most recent call last):\n  File \"path-to/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py\", line 1327, in _do_call\nreturn fn(*args)\n  File \"path-to/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py\", line 1312, in _run_fn\noptions, feed_dict, fetch_list, target_list, run_metadata)\n  File \"path-to/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py\", line 1420, in _call_tf_sessionrun\nstatus, run_metadata)\n  File \"path-to/venv/lib/python3.4/site-packages/tensorflow/python/framework/errors_impl.py\", line 516, in __exit__\nc_api.TF_GetCode(self.status.status))\ntensorflow.python.framework.errors_impl.InvalidArgumentError: logits and labels must be same size: logits_size=[117128,5] labels_size=[8,5]\n [[Node: softmax_cross_entropy_loss/xentropy = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](softmax_cross_entropy_loss/xentropy/Reshape, softmax_cross_entropy_loss/xentropy/Reshape_1)]]\n</code></pre>\n\n<p>It seems that there is a mismatch between the dataset size and the labels array, but that problem appears only when I try running it on 512x512 images, it works for any batch size on 32x32 images.</p>\n\n<p><strong>Finally, my question is,</strong> is there some other parameter I have to change or other adaptation I have to make to run the ResNet CIFAR10 code on my 512x512 dataset? Are these errors somehow related to something I'm doing wrong or there are likely two things I have to address? Any insight on what is causing these errors would be of great help as well.</p>\n\n<p><strong>Put briefly, what changes would I have to make to input my own 512x512 dataset into TensorFlow's ResNet CIFAR10 implementation?</strong></p>\n\n<p>This is my first question at StackOverflow and as I said I'm new to many things in the field of the question, so please, forgive any rookie mistake.</p>\n"
        },
        {
            "tags": [
                "continuous-integration",
                "gitlab",
                "pivotaltracker"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 5853160,
                "user_type": "registered",
                "profile_image": "https://lh6.googleusercontent.com/-d3mHgwC_5lg/AAAAAAAAAAI/AAAAAAAAAB8/Gq1_YtScXIo/photo.jpg?sz=128",
                "display_name": "Peter Ndungu",
                "link": "https://stackoverflow.com/users/5853160/peter-ndungu"
            },
            "is_answered": false,
            "view_count": 3,
            "answer_count": 0,
            "score": -1,
            "last_activity_date": 1524166377,
            "creation_date": 1524166377,
            "question_id": 49928899,
            "body_markdown": "After activating pivotal tracker in gitlab, by adding your user API token, how does one add gitlab integration on pivotal tracker, there is no option for it like others, github, jira or Zendesk.",
            "link": "https://stackoverflow.com/questions/49928899/integrate-pivotal-tracker-project-with-gitlab",
            "title": "integrate pivotal tracker project with gitlab",
            "body": "<p>After activating pivotal tracker in gitlab, by adding your user API token, how does one add gitlab integration on pivotal tracker, there is no option for it like others, github, jira or Zendesk.</p>\n"
        },
        {
            "tags": [
                "sql-server",
                "ssms",
                "sql-server-2017"
            ],
            "owner": {
                "reputation": 55,
                "user_id": 1330150,
                "user_type": "registered",
                "accept_rate": 40,
                "profile_image": "https://www.gravatar.com/avatar/379c9008f1ba764dae1d02e7e5c72221?s=128&d=identicon&r=PG",
                "display_name": "Daryl1976",
                "link": "https://stackoverflow.com/users/1330150/daryl1976"
            },
            "is_answered": false,
            "view_count": 23,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524166363,
            "creation_date": 1524153162,
            "last_edit_date": 1524153768,
            "question_id": 49925304,
            "body_markdown": "I set up a local database (SQL Server 2017 Express). Everything works fine, but I&#39;m getting errors when creating even a simple stored procedure in SSMS. \r\n\r\nFor example, this  \r\n\r\n    CREATE PROCEDURE [dbo].[EMS_Operations_SyncAssetTableByID2]\r\n    \t@Table_Name VARCHAR(255),\r\n    \t@Ids_For_Update VARCHAR(255),\r\n    \t@Is_Test BIT = 0\r\n    AS\r\n    BEGIN\r\n    \tDECLARE @DB_String varchar(55) =&#39;Redesign&#39;\r\n    END\r\n\r\nWill not run, and I get the error message:\r\n\r\n&gt; Msg 156, Level 15, State 1, Line 1  \r\n&gt; Incorrect syntax near the keyword &#39;PROCEDURE&#39;.\r\n&gt;\r\n&gt; Msg 156, Level 15, State 1, Line 1  \r\n&gt; Incorrect syntax near the keyword &#39;PROCEDURE&#39;.\r\n&gt;\r\n&gt; Msg 8180, Level 16, State 1, Procedure sp_describe_parameter_encryption, Line 1 [Batch Start Line 0]  \r\n&gt; Statement(s) could not be prepared.\r\n&gt;\r\n&gt; Msg 8180, Level 16, State 1, Procedure sp_describe_parameter_encryption, Line 1 [Batch Start Line 0]  \r\n&gt; Statement(s) could not be prepared.\r\n&gt;\r\n&gt; An error occurred while executing batch. Error message is: Internal error. The format of the resultset returned by sp_describe_parameter_encryption is invalid. One of the resultsets is missing.\r\n\r\nI&#39;m not sure what is causing this, or if there is corruption in the database, as there is encryption in the database, and I&#39;m not sure what it&#39;s calling.\r\n\r\nI also notice that there is a blue line underneath the first SQL Statement in the batch that says\r\n\r\n&gt; @DB_String will be converted into a System.Data.SqlClient.SqlParameter with the following properties: SqlDbType = varchar,Size 55, Precision=0\r\n\r\nWhen I run the same code on our remote server, it completes without issue. Any idea what could be causing this?",
            "link": "https://stackoverflow.com/questions/49925304/cannot-add-a-stored-procedure-to-database-due-to-encryption-message",
            "title": "Cannot add a stored procedure to database due to encryption message",
            "body": "<p>I set up a local database (SQL Server 2017 Express). Everything works fine, but I'm getting errors when creating even a simple stored procedure in SSMS. </p>\n\n<p>For example, this  </p>\n\n<pre><code>CREATE PROCEDURE [dbo].[EMS_Operations_SyncAssetTableByID2]\n    @Table_Name VARCHAR(255),\n    @Ids_For_Update VARCHAR(255),\n    @Is_Test BIT = 0\nAS\nBEGIN\n    DECLARE @DB_String varchar(55) ='Redesign'\nEND\n</code></pre>\n\n<p>Will not run, and I get the error message:</p>\n\n<blockquote>\n  <p>Msg 156, Level 15, State 1, Line 1<br>\n  Incorrect syntax near the keyword 'PROCEDURE'.</p>\n  \n  <p>Msg 156, Level 15, State 1, Line 1<br>\n  Incorrect syntax near the keyword 'PROCEDURE'.</p>\n  \n  <p>Msg 8180, Level 16, State 1, Procedure sp_describe_parameter_encryption, Line 1 [Batch Start Line 0]<br>\n  Statement(s) could not be prepared.</p>\n  \n  <p>Msg 8180, Level 16, State 1, Procedure sp_describe_parameter_encryption, Line 1 [Batch Start Line 0]<br>\n  Statement(s) could not be prepared.</p>\n  \n  <p>An error occurred while executing batch. Error message is: Internal error. The format of the resultset returned by sp_describe_parameter_encryption is invalid. One of the resultsets is missing.</p>\n</blockquote>\n\n<p>I'm not sure what is causing this, or if there is corruption in the database, as there is encryption in the database, and I'm not sure what it's calling.</p>\n\n<p>I also notice that there is a blue line underneath the first SQL Statement in the batch that says</p>\n\n<blockquote>\n  <p>@DB_String will be converted into a System.Data.SqlClient.SqlParameter with the following properties: SqlDbType = varchar,Size 55, Precision=0</p>\n</blockquote>\n\n<p>When I run the same code on our remote server, it completes without issue. Any idea what could be causing this?</p>\n"
        },
        {
            "tags": [
                "python",
                "python-3.x",
                "matplotlib"
            ],
            "owner": {
                "reputation": 26,
                "user_id": 8776627,
                "user_type": "registered",
                "profile_image": "https://lh4.googleusercontent.com/-rPEPPeqYwN8/AAAAAAAAAAI/AAAAAAAAAAA/cXIGgMY0j1M/photo.jpg?sz=128",
                "display_name": "Chicrala",
                "link": "https://stackoverflow.com/users/8776627/chicrala"
            },
            "is_answered": false,
            "view_count": 20,
            "answer_count": 0,
            "score": 1,
            "last_activity_date": 1524166353,
            "creation_date": 1524145013,
            "last_edit_date": 1524166353,
            "question_id": 49922514,
            "body_markdown": "I am currently processing some images using numpy and I&#39;m storing the new arrays with the results in dictionaries. An example of the images is below:\r\n\r\n[![enter image description here][1]][1]\r\n\r\nOnce I have the dictionary with the results, that are also images, how can I make a movie sequence of them? Using this I intend to observe how the structures evolve in time.\r\n\r\nMy attempt to achieve this is represented below:\r\n\r\n    import matplotlib.pyplot as plt\r\n\r\n    def init(img):\r\n        &#39;&#39;&#39;\r\n        This function supports the &#39;&#39;make_anim&#39;&#39; function by plotting the\r\n        background of each frame\r\n        &#39;&#39;&#39;\r\n        img.set_data([],[])\r\n    \r\n        return(img)\r\n\r\n\r\n    def updatefig(data, keys, i):\r\n        &#39;&#39;&#39;\r\n        This function supports the &#39;&#39;make_anim&#39;&#39; function by refreshing the \r\n        image space.\r\n        &#39;&#39;&#39;\r\n    \r\n        img.set_data(data[keys[i]])\r\n    \r\n        return(img)\r\n\r\n    def make_anim(data, keys = []):\r\n        &#39;&#39;&#39;\r\n        This function will produce an animation from a dataset.\r\n        &#39;&#39;&#39;\r\n        if keys == []:\r\n            keys = list(data.keys())\r\n\r\n        dims = data[keys[0]].shape\r\n    \r\n        #defining the figure\r\n        fig = plt.figure()\r\n    \r\n        #defining axis\r\n        ax = plt.axes(xlim=(0, dims[1]), ylim=(0, dims[0]))\r\n    \r\n        #inserting the dataset to an image\r\n        img = plt.imgshow(data, animated = True)\r\n        #using the animation function\r\n        ani = animation.FuncAnimation(fig, updatefig(data, keys), \r\n                                      interval = 50,\r\n                                      frames = len(keys), blit = False)\r\n        plt.show()\r\n    \r\n        return()\r\n\r\nI&#39;m struggling to find tutorials that deal with similar problems and when I find them I can&#39;t really reproduce.\r\n\r\nIn advance, thanks for your time!\r\n\r\nAndre\r\n\r\n  [1]: https://i.stack.imgur.com/aEwIQ.png",
            "link": "https://stackoverflow.com/questions/49922514/how-to-make-an-animation-out-of-images-represented-by-numpy-arrays-in-a-dictiona",
            "title": "How to make an animation out of images represented by numpy arrays in a dictionary",
            "body": "<p>I am currently processing some images using numpy and I'm storing the new arrays with the results in dictionaries. An example of the images is below:</p>\n\n<p><a href=\"https://i.stack.imgur.com/aEwIQ.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/aEwIQ.png\" alt=\"enter image description here\"></a></p>\n\n<p>Once I have the dictionary with the results, that are also images, how can I make a movie sequence of them? Using this I intend to observe how the structures evolve in time.</p>\n\n<p>My attempt to achieve this is represented below:</p>\n\n<pre><code>import matplotlib.pyplot as plt\n\ndef init(img):\n    '''\n    This function supports the ''make_anim'' function by plotting the\n    background of each frame\n    '''\n    img.set_data([],[])\n\n    return(img)\n\n\ndef updatefig(data, keys, i):\n    '''\n    This function supports the ''make_anim'' function by refreshing the \n    image space.\n    '''\n\n    img.set_data(data[keys[i]])\n\n    return(img)\n\ndef make_anim(data, keys = []):\n    '''\n    This function will produce an animation from a dataset.\n    '''\n    if keys == []:\n        keys = list(data.keys())\n\n    dims = data[keys[0]].shape\n\n    #defining the figure\n    fig = plt.figure()\n\n    #defining axis\n    ax = plt.axes(xlim=(0, dims[1]), ylim=(0, dims[0]))\n\n    #inserting the dataset to an image\n    img = plt.imgshow(data, animated = True)\n    #using the animation function\n    ani = animation.FuncAnimation(fig, updatefig(data, keys), \n                                  interval = 50,\n                                  frames = len(keys), blit = False)\n    plt.show()\n\n    return()\n</code></pre>\n\n<p>I'm struggling to find tutorials that deal with similar problems and when I find them I can't really reproduce.</p>\n\n<p>In advance, thanks for your time!</p>\n\n<p>Andre</p>\n"
        },
        {
            "tags": [
                "php",
                "ajax",
                "angular4-forms"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 9671490,
                "user_type": "registered",
                "profile_image": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=128",
                "display_name": "Sagar Sasuke",
                "link": "https://stackoverflow.com/users/9671490/sagar-sasuke"
            },
            "is_answered": false,
            "view_count": 14,
            "closed_date": 1524164738,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524166341,
            "creation_date": 1524163885,
            "last_edit_date": 1524166341,
            "question_id": 49928236,
            "body_markdown": "I have following code which give me list of all image in localhost :-\r\n\r\n    &lt;?php\r\n    $target_dir = &quot;uploadToper/&quot;;\r\n    header(&#39;Access-Control-Allow-Origin: *&#39;);\r\n    header(&#39;Access-Control-Allow-Methods: GET, POST&#39;);\r\n    $dir = &quot;http://&quot;.$_SERVER[&#39;SERVER_NAME&#39;].&quot;/apimerit/&quot;;\r\n    $collection = array();\r\n    /*\r\n    $collection[] = array(&#39;title&#39; =&gt; &#39;sdfsdf&#39;, &#39;artist&#39; =&gt;&#39;dsfsdf&#39;);\r\n    $collection[] = array(&#39;title&#39; =&gt; &#39;dsfsdfs&#39;, &#39;artist&#39; =&gt;&#39;dswdf&#39;);\r\n    $collection[] = array(&#39;title&#39; =&gt; &#39;ssdfsf&#39;, &#39;artist&#39; =&gt;&#39;dwer&#39;);\r\n    $collection[] = array(&#39;title&#39; =&gt; &#39;sdsdfsd&#39;, &#39;artist&#39; =&gt;&#39;dewrwedf&#39;);*/\r\n    foreach(glob($target_dir . &#39;*.*&#39;) as $filename){\r\n    // echo $dir. $filename;\r\n\t$imageFileType = pathinfo($filename,PATHINFO_EXTENSION);\r\n\t$filename = explode(&quot;/&quot;,$filename)[1];\r\n    $collection[] = array(&#39;fileName&#39; =&gt;  $filename, &#39;fullPath&#39;=&gt;$dir.$target_dir. $filename, &#39;icon&#39;=&gt;$imageFileType);\r\n     }\r\n    echo json_encode($collection);\r\n\r\n    ?&gt;\r\nI get this proper output:-\r\n\r\n    [{&quot;fileName&quot;:&quot;slide1.jpg&quot;,&quot;fullPath&quot;:&quot;http:\\/\\/localhost\\/apimerit\\/uploadToper\\/slide1.jpg&quot;,&quot;icon&quot;:&quot;jpg&quot;},{&quot;fileName&quot;:&quot;slide2.jpg&quot;,&quot;fullPath&quot;:&quot;http:\\/\\/localhost\\/apimerit\\/uploadToper\\/slide2.jpg&quot;,&quot;icon&quot;:&quot;jpg&quot;},{&quot;fileName&quot;:&quot;toper1_2016.jpg&quot;,&quot;fullPath&quot;:&quot;http:\\/\\/localhost\\/apimerit\\/uploadToper\\/toper1_2016.jpg&quot;,&quot;icon&quot;:&quot;jpg&quot;},{&quot;fileName&quot;:&quot;toper3_2015.jpg&quot;,&quot;fullPath&quot;:&quot;http:\\/\\/localhost\\/apimerit\\/uploadToper\\/toper3_2015.jpg&quot;,&quot;icon&quot;:&quot;jpg&quot;},{&quot;fileName&quot;:&quot;toper3_2017.jpg&quot;,&quot;fullPath&quot;:&quot;http:\\/\\/localhost\\/apimerit\\/uploadToper\\/toper3_2017.jpg&quot;,&quot;icon&quot;:&quot;jpg&quot;},{&quot;fileName&quot;:&quot;toper4_2017.jpg&quot;,&quot;fullPath&quot;:&quot;http:\\/\\/localhost\\/apimerit\\/uploadToper\\/toper4_2017.jpg&quot;,&quot;icon&quot;:&quot;jpg&quot;}]\r\n\r\n**but when I upload it ot my webserver on godady it giv following error:-**\r\n\r\n\r\n&gt; &quot;Parse error: syntax error, unexpected &#39;[&#39; in\r\n&gt; G:\\PleskVhosts\\worldplanetesolutions.com\\merithub2.worldplanetesolutions.com\\apimerit\\getToperImagesapi.php\r\n&gt; on line 15&quot;\r\n\r\n\r\n**and if I remove &quot;[1]&quot; from &quot;$filename = explode(&quot;/&quot;,$filename)[1];&quot;\r\nit provides me an array of filename like this:-**\r\n\r\n&gt; [{&quot;fileName&quot;:[&quot;uploadToper&quot;,&quot;slide1.jpg&quot;],&quot;fullPath&quot;:&quot;http:\\/   \r\n&gt; \\/merithub2.worldplanetesolutions.com\\/apimerit\\/uploadToper\\/Array&quot;,&quot;icon&quot;:&quot;jpg&quot;},{&quot;fileName&quot;:[&quot;uploadToper&quot;,&quot;slide2.jpg&quot;],&quot;fullPath&quot;:&quot;http:\\/\\/merithub2.worldplanetesolutions.com\\/apimerit\\/uploadToper\\/Array&quot;,&quot;icon&quot;:&quot;jpg&quot;},{&quot;fileName&quot;:[&quot;uploadToper&quot;,&quot;toper1_2016.jpg&quot;],&quot;fullPath&quot;:&quot;http:\\/\\/merithub2.worldplanetesolutions.com\\/apimerit\\/uploadToper\\/Array&quot;,&quot;icon&quot;:&quot;jpg&quot;},{&quot;fileName&quot;:[&quot;uploadToper&quot;,&quot;toper3_2015.jpg&quot;],&quot;fullPath&quot;:&quot;http:\\/\\/merithub2.worldplanetesolutions.com\\/apimerit\\/uploadToper\\/Array&quot;,&quot;icon&quot;:&quot;jpg&quot;},{&quot;fileName&quot;:[&quot;uploadToper&quot;,&quot;toper3_2017.jpg&quot;],&quot;fullPath&quot;:&quot;http:\\/\\/merithub2.worldplanetesolutions.com\\/apimerit\\/uploadToper\\/Array&quot;,&quot;icon&quot;:&quot;jpg&quot;},{&quot;fileName&quot;:[&quot;uploadToper&quot;,&quot;toper4_2017.jpg&quot;],&quot;fullPath&quot;:&quot;http:\\/\\/merithub2.worldplanetesolutions.com\\/apimerit\\/uploadToper\\/Array&quot;,&quot;icon&quot;:&quot;jpg&quot;}]\r\n\r\n",
            "link": "https://stackoverflow.com/questions/49928236/php-fetch-images-from-folder",
            "closed_reason": "duplicate",
            "title": "Php fetch Images from folder",
            "body": "<p>I have following code which give me list of all image in localhost :-</p>\n\n<pre><code>&lt;?php\n$target_dir = \"uploadToper/\";\nheader('Access-Control-Allow-Origin: *');\nheader('Access-Control-Allow-Methods: GET, POST');\n$dir = \"http://\".$_SERVER['SERVER_NAME'].\"/apimerit/\";\n$collection = array();\n/*\n$collection[] = array('title' =&gt; 'sdfsdf', 'artist' =&gt;'dsfsdf');\n$collection[] = array('title' =&gt; 'dsfsdfs', 'artist' =&gt;'dswdf');\n$collection[] = array('title' =&gt; 'ssdfsf', 'artist' =&gt;'dwer');\n$collection[] = array('title' =&gt; 'sdsdfsd', 'artist' =&gt;'dewrwedf');*/\nforeach(glob($target_dir . '*.*') as $filename){\n// echo $dir. $filename;\n$imageFileType = pathinfo($filename,PATHINFO_EXTENSION);\n$filename = explode(\"/\",$filename)[1];\n$collection[] = array('fileName' =&gt;  $filename, 'fullPath'=&gt;$dir.$target_dir. $filename, 'icon'=&gt;$imageFileType);\n }\necho json_encode($collection);\n\n?&gt;\n</code></pre>\n\n<p>I get this proper output:-</p>\n\n<pre><code>[{\"fileName\":\"slide1.jpg\",\"fullPath\":\"http:\\/\\/localhost\\/apimerit\\/uploadToper\\/slide1.jpg\",\"icon\":\"jpg\"},{\"fileName\":\"slide2.jpg\",\"fullPath\":\"http:\\/\\/localhost\\/apimerit\\/uploadToper\\/slide2.jpg\",\"icon\":\"jpg\"},{\"fileName\":\"toper1_2016.jpg\",\"fullPath\":\"http:\\/\\/localhost\\/apimerit\\/uploadToper\\/toper1_2016.jpg\",\"icon\":\"jpg\"},{\"fileName\":\"toper3_2015.jpg\",\"fullPath\":\"http:\\/\\/localhost\\/apimerit\\/uploadToper\\/toper3_2015.jpg\",\"icon\":\"jpg\"},{\"fileName\":\"toper3_2017.jpg\",\"fullPath\":\"http:\\/\\/localhost\\/apimerit\\/uploadToper\\/toper3_2017.jpg\",\"icon\":\"jpg\"},{\"fileName\":\"toper4_2017.jpg\",\"fullPath\":\"http:\\/\\/localhost\\/apimerit\\/uploadToper\\/toper4_2017.jpg\",\"icon\":\"jpg\"}]\n</code></pre>\n\n<p><strong>but when I upload it ot my webserver on godady it giv following error:-</strong></p>\n\n<blockquote>\n  <p>\"Parse error: syntax error, unexpected '[' in\n  G:\\PleskVhosts\\worldplanetesolutions.com\\merithub2.worldplanetesolutions.com\\apimerit\\getToperImagesapi.php\n  on line 15\"</p>\n</blockquote>\n\n<p><strong>and if I remove \"[1]\" from \"$filename = explode(\"/\",$filename)[1];\"\nit provides me an array of filename like this:-</strong></p>\n\n<blockquote>\n  <p>[{\"fileName\":[\"uploadToper\",\"slide1.jpg\"],\"fullPath\":\"http:/<br>\n  /merithub2.worldplanetesolutions.com/apimerit/uploadToper/Array\",\"icon\":\"jpg\"},{\"fileName\":[\"uploadToper\",\"slide2.jpg\"],\"fullPath\":\"http://merithub2.worldplanetesolutions.com/apimerit/uploadToper/Array\",\"icon\":\"jpg\"},{\"fileName\":[\"uploadToper\",\"toper1_2016.jpg\"],\"fullPath\":\"http://merithub2.worldplanetesolutions.com/apimerit/uploadToper/Array\",\"icon\":\"jpg\"},{\"fileName\":[\"uploadToper\",\"toper3_2015.jpg\"],\"fullPath\":\"http://merithub2.worldplanetesolutions.com/apimerit/uploadToper/Array\",\"icon\":\"jpg\"},{\"fileName\":[\"uploadToper\",\"toper3_2017.jpg\"],\"fullPath\":\"http://merithub2.worldplanetesolutions.com/apimerit/uploadToper/Array\",\"icon\":\"jpg\"},{\"fileName\":[\"uploadToper\",\"toper4_2017.jpg\"],\"fullPath\":\"http://merithub2.worldplanetesolutions.com/apimerit/uploadToper/Array\",\"icon\":\"jpg\"}]</p>\n</blockquote>\n"
        },
        {
            "tags": [
                "google-cloud-platform",
                "dataflow",
                "stackdriver"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 8492398,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/01cad2760570611e43723d1729b0ccfe?s=128&d=identicon&r=PG&f=1",
                "display_name": "andrew",
                "link": "https://stackoverflow.com/users/8492398/andrew"
            },
            "is_answered": false,
            "view_count": 26,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524166338,
            "creation_date": 1522795168,
            "last_edit_date": 1524166338,
            "question_id": 49640105,
            "body_markdown": "I need to run a batch job from GCS to BigQuery via Dataflow and Beam. All my files are avro with the same schema.\r\nI&#39;ve created a dataflow java application that is successful on a smaller set of data (~1gb, about 5 files).\r\nBut when I try to run it on a bigger set of data ( &gt;500gb, &gt;1000 files), i receive an error message \r\n\r\n    java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: java.lang.RuntimeException: Failed to create load job with id prefix 1b83679a4f5d48c5b45ff20b2b822728_6e48345728d4da6cb51353f0dc550c1b_00001_00000, reached max retries: 3, last failed load job: ...\r\n\r\nAfter 3 retries it terminates with: \r\n\r\n    Workflow failed. Causes: S57....... A work item was attempted 4 times without success....\r\n\r\nThis step is the load to BigQuery.\r\n\r\nStack Driver says the processing is stuck in step ....for 10m00s... and\r\n\r\n    Request failed with code 409, performed 0 retries due to IOExceptions, performed 0 retries due to unsuccessful status codes.....\r\n\r\nI looked up the 409 error code stating that I might have an existing job, dataset, or table. I&#39;ve removed all the tables and re-ran the application but it still shows the same error message.\r\n\r\nI am currently limited on 65 workers and I have them using n1-standard-4 cpus. \r\n\r\nI believe there are other ways to move the data from gcs to bq, but i need to demonstrate dataflow.\r\n\r\n\r\n",
            "link": "https://stackoverflow.com/questions/49640105/bigquery-unable-to-insert-job-workflow-failed",
            "title": "BigQuery unable to insert job. Workflow failed",
            "body": "<p>I need to run a batch job from GCS to BigQuery via Dataflow and Beam. All my files are avro with the same schema.\nI've created a dataflow java application that is successful on a smaller set of data (~1gb, about 5 files).\nBut when I try to run it on a bigger set of data ( >500gb, >1000 files), i receive an error message </p>\n\n<pre><code>java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: java.lang.RuntimeException: Failed to create load job with id prefix 1b83679a4f5d48c5b45ff20b2b822728_6e48345728d4da6cb51353f0dc550c1b_00001_00000, reached max retries: 3, last failed load job: ...\n</code></pre>\n\n<p>After 3 retries it terminates with: </p>\n\n<pre><code>Workflow failed. Causes: S57....... A work item was attempted 4 times without success....\n</code></pre>\n\n<p>This step is the load to BigQuery.</p>\n\n<p>Stack Driver says the processing is stuck in step ....for 10m00s... and</p>\n\n<pre><code>Request failed with code 409, performed 0 retries due to IOExceptions, performed 0 retries due to unsuccessful status codes.....\n</code></pre>\n\n<p>I looked up the 409 error code stating that I might have an existing job, dataset, or table. I've removed all the tables and re-ran the application but it still shows the same error message.</p>\n\n<p>I am currently limited on 65 workers and I have them using n1-standard-4 cpus. </p>\n\n<p>I believe there are other ways to move the data from gcs to bq, but i need to demonstrate dataflow.</p>\n"
        },
        {
            "tags": [
                "oop",
                "inheritance",
                "software-design",
                "solid-principles",
                "design-principles"
            ],
            "owner": {
                "reputation": 28,
                "user_id": 9372858,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/86f3bde73c0d9d96eb08010d88916c3f?s=128&d=identicon&r=PG&f=1",
                "display_name": "user9372858",
                "link": "https://stackoverflow.com/users/9372858/user9372858"
            },
            "is_answered": true,
            "view_count": 56,
            "accepted_answer_id": 49918194,
            "answer_count": 2,
            "score": 2,
            "last_activity_date": 1524166337,
            "creation_date": 1524121698,
            "last_edit_date": 1524125922,
            "question_id": 49914802,
            "body_markdown": "I am trying to model geographic locations in OOP.  Location types are as follows:continent, country, state, county or more specific (e.g city, town, village, all modeled as a single type). Continents have continent code, counties have continent code and country code, states have continent code, country code and adm1code, counties and those more specific than counties have continent code, country code, adm1code and adm2code. I need all locations to implement an interface with method &quot;isContainedIn(Location loc)&quot;. This checks whether the current location is contained in loc based on the administrative code. So in case of countries, this method would first check if loc is Continent - if not, return false. If it is continent, then it will check whether the continent code of loc is the same as the continent code of the country.\r\n\r\nI can model the locations using a single class with a type field or use inheritance. I would rather model using inheritance with a base class called location representing locations more specific than adm2 which all administrative location types (country, code, state and county) would extend (which conceptually is not right - I&#39;m saying that town is the parent class of continent). This way I can simply override other methods too such as the equals operator (e.g. two countries are equal if the have same country codes). However, then the base class would need to include continent code, country code, adm1code and adm2code to allow me to implement the isContainedIn(Location loc) method in every case. Country code does not make sense for continents, adm1code does not make sense for countries and so on. I can have blank strings when they don&#39;t make sense but would that violate Liskov substitution principle or any other standard design principle? If so, could you suggest other design options for this problem?\r\n\r\nEDIT: I would want a client class to get two location instances, say l1 and l2, and be able to call l1.isContainedIn(l2) without knowing the specific type of the location. Let me elaborate on how it becomes a problem if I model the classes as follows:\r\n1. A parent class containing only the variables making sense for all locations which are name, latitude and  longitude\r\n2. Children classes (continent, country, state, county and more specific), all implementing the isContainedIn(Location loc) interface. Continent would have continent code, country would have continent code &amp; country code and so on.\r\n\r\nWith this structure I simply can&#39;t write out the logic for isContainedIn(Location loc) in any of the child classes. For instance, a location is contained in a continent if 1) it is not a continent and 2) it has the same continent code as the continent. But Location class has no continent code.  I hope this clarifies the question and thanks a lot for looking into this!\r\n\r\nEDIT2: **Here is some example code (instead of interface I have an abstract class):**\r\n\r\n    abstract class Location {\r\n      protected String name;\r\n      protected double lat;\r\n      protected double lng;\r\n    \r\n      @Override\r\n      public boolean equals(Object loc) {\r\n        if(!(loc instanceof Location)) {\r\n          return false;\r\n        }\r\n        Location l = (Location) loc;\r\n        return this.lat==l.lat &amp;&amp; this.lng==l.lng;\r\n      }\r\n    \r\n      abstract boolean isContainedIn(Location loc);\r\n    \r\n    } \r\n      \r\n    class Continent extends Location {\r\n      protected String continentCode;\r\n      \r\n      @Override\r\n      public boolean equals(Object loc) {\r\n        if(!(loc instanceof Continent)) {\r\n          return false;\r\n        }\r\n        Location l = (Continent) loc;\r\n        return this.continentCode.equals(loc.continentCode);\r\n      }\r\n    \r\n      boolean isContainedIn(Location loc) {\r\n        if(loc instance of Continent) {\r\n          return false;\r\n        }\r\n         //the following is the logic but won&#39;t work since location has no \r\n           continentCode variable\r\n         //return loc.continentCode.equals(continentCode);\r\n      }\r\n    }\r\n      \r\n    class Country extends Location {\r\n      protected String continentCode;\r\n      protected String countryCode;\r\n      @Override\r\n      public boolean equals(Object loc) {\r\n        if(!(loc instanceof Country)) {\r\n          return false;\r\n        }\r\n        Location l = (Country) loc;\r\n        return this.continentCode.equals(loc.continentCode) &amp;&amp; this.countryCode.equals(loc.countryCode);\r\n      }\r\n    \r\n      boolean isContainedIn(Location loc) {\r\n        if(loc instance of Continent|| loc instance of Country) {\r\n          return false;\r\n        }\r\n         //the following is the logic but won&#39;t work since location has no \r\n           countryCode or continent code variable\r\n         //return loc.continentCode.equals(continentCode) &amp;&amp; loc.countryCode.equals(countryCode);\r\n      }\r\n    }\r\n  //other classes will be similar\r\n\r\n\r\n **This is what the client class might look like**\r\n\r\n    class ClientClass {\r\n      void someMethod {\r\n       Location l1 = someClass.getLocation(String...searchParameters);\r\n      Location l2 = someClass.getLocation(String...searchParameters);\r\n      if(l1.isContainedIn(l2)) {\r\n        //do something\r\n      }\r\n    }\r\n\r\n**Objective: Model the location classes, to enable the client code to use isContainedIn method without knowing the specific type of the location. Can this be done if parent class has no knowledge of continent code, country code etc?**\r\n\r\n**Alternate class design**\r\n\r\n    //for locations contained in counties\r\n    class Location {\r\n      String name;\r\n      double lat;\r\n      double lng;\r\n      String continentCode;\r\n      String countryCode;\r\n      String adm1code;\r\n      String adm2code;\r\n    }\r\n    \r\n    class Continent extends Location {\r\n      String countryCode =&quot;&quot;;\r\n      String adm1code = &quot;&quot;;\r\n      String adm2code = &quot;&quot;;\r\n    \r\n      public Continent(String continentCode) {\r\n        this.continentCode = continentCode;\r\n      }\r\n      //all logic will work but does that violate design principles since Continent technically has no country code, adm1code or adm2code - blank strings returned for these cases?\r\n\r\nThanks.\r\n\r\n",
            "link": "https://stackoverflow.com/questions/49914802/using-inheritance-with-a-parent-class-which-contains-empty-strings-for-variables",
            "title": "Using inheritance with a parent class which contains empty strings for variables that are only applicable in child classes",
            "body": "<p>I am trying to model geographic locations in OOP.  Location types are as follows:continent, country, state, county or more specific (e.g city, town, village, all modeled as a single type). Continents have continent code, counties have continent code and country code, states have continent code, country code and adm1code, counties and those more specific than counties have continent code, country code, adm1code and adm2code. I need all locations to implement an interface with method \"isContainedIn(Location loc)\". This checks whether the current location is contained in loc based on the administrative code. So in case of countries, this method would first check if loc is Continent - if not, return false. If it is continent, then it will check whether the continent code of loc is the same as the continent code of the country.</p>\n\n<p>I can model the locations using a single class with a type field or use inheritance. I would rather model using inheritance with a base class called location representing locations more specific than adm2 which all administrative location types (country, code, state and county) would extend (which conceptually is not right - I'm saying that town is the parent class of continent). This way I can simply override other methods too such as the equals operator (e.g. two countries are equal if the have same country codes). However, then the base class would need to include continent code, country code, adm1code and adm2code to allow me to implement the isContainedIn(Location loc) method in every case. Country code does not make sense for continents, adm1code does not make sense for countries and so on. I can have blank strings when they don't make sense but would that violate Liskov substitution principle or any other standard design principle? If so, could you suggest other design options for this problem?</p>\n\n<p>EDIT: I would want a client class to get two location instances, say l1 and l2, and be able to call l1.isContainedIn(l2) without knowing the specific type of the location. Let me elaborate on how it becomes a problem if I model the classes as follows:\n1. A parent class containing only the variables making sense for all locations which are name, latitude and  longitude\n2. Children classes (continent, country, state, county and more specific), all implementing the isContainedIn(Location loc) interface. Continent would have continent code, country would have continent code &amp; country code and so on.</p>\n\n<p>With this structure I simply can't write out the logic for isContainedIn(Location loc) in any of the child classes. For instance, a location is contained in a continent if 1) it is not a continent and 2) it has the same continent code as the continent. But Location class has no continent code.  I hope this clarifies the question and thanks a lot for looking into this!</p>\n\n<p>EDIT2: <strong>Here is some example code (instead of interface I have an abstract class):</strong></p>\n\n<pre><code>abstract class Location {\n  protected String name;\n  protected double lat;\n  protected double lng;\n\n  @Override\n  public boolean equals(Object loc) {\n    if(!(loc instanceof Location)) {\n      return false;\n    }\n    Location l = (Location) loc;\n    return this.lat==l.lat &amp;&amp; this.lng==l.lng;\n  }\n\n  abstract boolean isContainedIn(Location loc);\n\n} \n\nclass Continent extends Location {\n  protected String continentCode;\n\n  @Override\n  public boolean equals(Object loc) {\n    if(!(loc instanceof Continent)) {\n      return false;\n    }\n    Location l = (Continent) loc;\n    return this.continentCode.equals(loc.continentCode);\n  }\n\n  boolean isContainedIn(Location loc) {\n    if(loc instance of Continent) {\n      return false;\n    }\n     //the following is the logic but won't work since location has no \n       continentCode variable\n     //return loc.continentCode.equals(continentCode);\n  }\n}\n\nclass Country extends Location {\n  protected String continentCode;\n  protected String countryCode;\n  @Override\n  public boolean equals(Object loc) {\n    if(!(loc instanceof Country)) {\n      return false;\n    }\n    Location l = (Country) loc;\n    return this.continentCode.equals(loc.continentCode) &amp;&amp; this.countryCode.equals(loc.countryCode);\n  }\n\n  boolean isContainedIn(Location loc) {\n    if(loc instance of Continent|| loc instance of Country) {\n      return false;\n    }\n     //the following is the logic but won't work since location has no \n       countryCode or continent code variable\n     //return loc.continentCode.equals(continentCode) &amp;&amp; loc.countryCode.equals(countryCode);\n  }\n}\n</code></pre>\n\n<p>//other classes will be similar</p>\n\n<p><strong>This is what the client class might look like</strong></p>\n\n<pre><code>class ClientClass {\n  void someMethod {\n   Location l1 = someClass.getLocation(String...searchParameters);\n  Location l2 = someClass.getLocation(String...searchParameters);\n  if(l1.isContainedIn(l2)) {\n    //do something\n  }\n}\n</code></pre>\n\n<p><strong>Objective: Model the location classes, to enable the client code to use isContainedIn method without knowing the specific type of the location. Can this be done if parent class has no knowledge of continent code, country code etc?</strong></p>\n\n<p><strong>Alternate class design</strong></p>\n\n<pre><code>//for locations contained in counties\nclass Location {\n  String name;\n  double lat;\n  double lng;\n  String continentCode;\n  String countryCode;\n  String adm1code;\n  String adm2code;\n}\n\nclass Continent extends Location {\n  String countryCode =\"\";\n  String adm1code = \"\";\n  String adm2code = \"\";\n\n  public Continent(String continentCode) {\n    this.continentCode = continentCode;\n  }\n  //all logic will work but does that violate design principles since Continent technically has no country code, adm1code or adm2code - blank strings returned for these cases?\n</code></pre>\n\n<p>Thanks.</p>\n"
        },
        {
            "tags": [
                "actionscript-3",
                "events"
            ],
            "owner": {
                "user_type": "does_not_exist",
                "display_name": "trent"
            },
            "is_answered": true,
            "view_count": 5835,
            "answer_count": 7,
            "score": 1,
            "last_activity_date": 1524166334,
            "creation_date": 1254643137,
            "last_edit_date": 1524166334,
            "question_id": 1515869,
            "body_markdown": "Ok, maybe I&#39;ve just had too much beer at this point but - I&#39;m just trying to listen for a custom event from an SWF I&#39;ve loaded and I&#39;m just NOT able to capture it. The loading code right now is just:\r\n\r\n\r\n    public function loadGame(gameSrc:String,gX:Number,gY:Number):void {\r\n        var loader = new Loader();\r\n        var addedDefinitions:LoaderContext = new LoaderContext();\r\n        addedDefinitions.applicationDomain = new ApplicationDomain();   \r\n        loader.load(new URLRequest(gameSrc));\r\n        loader.contentLoaderInfo.addEventListener(Event.COMPLETE,onLoaded);\r\n   \r\n    function onLoaded(evt:Event):void {   \r\n        var game:MovieClip = MovieClip(evt.target.content);\r\n    \r\n        game.x = gX;\r\n        game.y = gY;    \r\n\r\n        chamber.mc_gameHolder.addChild(game);    \r\n        Tweener.addTween(chamber.mc_gameTitle,{alpha:1,time:.75});  \r\n    \r\n        game.addEventListener(&quot;showQuiz&quot;,showQuiz);  \r\n    }\r\n  \r\n    }\r\n\r\n\r\nI&#39;ve tried like a ton of ways to do this and NONE of them work. I know the event is being fired from my loaded SWF because I also have a listener in there that traces out a &quot;hello&quot; when it&#39;s fired. \r\n\r\nAnyone? And apologies if this has been posted before - search didn&#39;t turn up anything specific. ",
            "link": "https://stackoverflow.com/questions/1515869/as3-add-event-listener-to-loaded-swf",
            "title": "AS3: add event listener to loaded swf",
            "body": "<p>I'm trying to listen for a custom event from an SWF I've loaded and I'm just not able to capture it. The loading code right now is just:</p>\n\n<pre><code>public function loadGame(gameSrc:String,gX:Number,gY:Number):void {\n    var loader = new Loader();\n    var addedDefinitions:LoaderContext = new LoaderContext();\n    addedDefinitions.applicationDomain = new ApplicationDomain();   \n    loader.load(new URLRequest(gameSrc));\n    loader.contentLoaderInfo.addEventListener(Event.COMPLETE,onLoaded);\n\nfunction onLoaded(evt:Event):void {   \n    var game:MovieClip = MovieClip(evt.target.content);\n\n    game.x = gX;\n    game.y = gY;    \n\n    chamber.mc_gameHolder.addChild(game);    \n    Tweener.addTween(chamber.mc_gameTitle,{alpha:1,time:.75});  \n\n    game.addEventListener(\"showQuiz\",showQuiz);  \n}\n\n}\n</code></pre>\n\n<p>I know the event is being fired from my loaded SWF because I also have a listener in there that traces out a \"hello\" when it's fired. </p>\n\n<p>Anyone? And apologies if this has been posted before - search didn't turn up anything specific. </p>\n"
        },
        {
            "tags": [
                "python",
                "odoo",
                "odoo-10"
            ],
            "owner": {
                "reputation": 4398,
                "user_id": 5906918,
                "user_type": "registered",
                "accept_rate": 100,
                "profile_image": "https://i.stack.imgur.com/OU5vg.jpg?s=128&g=1",
                "display_name": "Begueradj",
                "link": "https://stackoverflow.com/users/5906918/begueradj"
            },
            "is_answered": false,
            "view_count": 17,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524166328,
            "creation_date": 1524166328,
            "question_id": 49928888,
            "body_markdown": "I created a simple module for Odoo and added it to the addons path:\r\n\r\n    ./odoo-bin -d mymodule --addons-path=&quot;addons&quot; --save\r\n\r\nI then installed it through the web interface and all works fine.\r\n\r\nNow I do not need the module anymore, I uninstalled it from the web interface but still I must undo the command above, how to achieve that from the command line?",
            "link": "https://stackoverflow.com/questions/49928888/odoo-how-to-remove-a-module-from-the-addons-path",
            "title": "Odoo: How to remove a module from the addons path?",
            "body": "<p>I created a simple module for Odoo and added it to the addons path:</p>\n\n<pre><code>./odoo-bin -d mymodule --addons-path=\"addons\" --save\n</code></pre>\n\n<p>I then installed it through the web interface and all works fine.</p>\n\n<p>Now I do not need the module anymore, I uninstalled it from the web interface but still I must undo the command above, how to achieve that from the command line?</p>\n"
        },
        {
            "tags": [
                "docker-image"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 8269040,
                "user_type": "registered",
                "profile_image": "https://lh6.googleusercontent.com/-1jPGpKjuQE8/AAAAAAAAAAI/AAAAAAAAA0M/DnAuFaXVeCg/photo.jpg?sz=128",
                "display_name": "Ramesh Ganesh",
                "link": "https://stackoverflow.com/users/8269040/ramesh-ganesh"
            },
            "is_answered": false,
            "view_count": 16,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524166326,
            "creation_date": 1524165359,
            "last_edit_date": 1524166326,
            "question_id": 49928615,
            "body_markdown": "Job for docker.service failed because the control process exited with error code. See &quot;systemctl status docker.service&quot; and &quot;journalctl -xe&quot; for details.\r\n\r\n**systemctl status docker.service:**\r\n\r\n    ● docker.service - Docker Application Container Engine\r\n       Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)\r\n       Active: inactive (dead) (Result: exit-code) since Fri 2018-04-20 00:30:30 IST; 22s ago\r\n         Docs: https://docs.docker.com\r\n      Process: 16941 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)\r\n     Main PID: 16941 (code=exited, status=1/FAILURE)\r\n    \r\n    Apr 20 00:30:30 cookie2 systemd[1]: Failed to start Docker Application Container Engine.\r\n    Apr 20 00:30:30 cookie2 systemd[1]: docker.service: Unit entered failed state.\r\n    Apr 20 00:30:30 cookie2 systemd[1]: docker.service: Failed with result &#39;exit-code&#39;.\r\n    Apr 20 00:30:30 cookie2 systemd[1]: docker.service: Service hold-off time over, scheduling restart.\r\n    Apr 20 00:30:30 cookie2 systemd[1]: Stopped Docker Application Container Engine.\r\n    Apr 20 00:30:30 cookie2 systemd[1]: docker.service: Start request repeated too quickly.\r\n    Apr 20 00:30:30 cookie2 systemd[1]: Failed to start Docker Application Container Engine.\r\n\r\n",
            "link": "https://stackoverflow.com/questions/49928615/failed-to-start-docker-service-ubuntu-16-04-lts",
            "title": "Failed to start Docker Service.( Ubuntu 16.04 LTS)",
            "body": "<p>Job for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.</p>\n\n<p><strong>systemctl status docker.service:</strong></p>\n\n<pre><code>● docker.service - Docker Application Container Engine\n   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)\n   Active: inactive (dead) (Result: exit-code) since Fri 2018-04-20 00:30:30 IST; 22s ago\n     Docs: https://docs.docker.com\n  Process: 16941 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)\n Main PID: 16941 (code=exited, status=1/FAILURE)\n\nApr 20 00:30:30 cookie2 systemd[1]: Failed to start Docker Application Container Engine.\nApr 20 00:30:30 cookie2 systemd[1]: docker.service: Unit entered failed state.\nApr 20 00:30:30 cookie2 systemd[1]: docker.service: Failed with result 'exit-code'.\nApr 20 00:30:30 cookie2 systemd[1]: docker.service: Service hold-off time over, scheduling restart.\nApr 20 00:30:30 cookie2 systemd[1]: Stopped Docker Application Container Engine.\nApr 20 00:30:30 cookie2 systemd[1]: docker.service: Start request repeated too quickly.\nApr 20 00:30:30 cookie2 systemd[1]: Failed to start Docker Application Container Engine.\n</code></pre>\n"
        },
        {
            "tags": [
                "excel",
                "excel-vba",
                "validation"
            ],
            "owner": {
                "reputation": 42,
                "user_id": 7885268,
                "user_type": "registered",
                "accept_rate": 100,
                "profile_image": "https://www.gravatar.com/avatar/dd5321500837661a0acfab6a34794919?s=128&d=identicon&r=PG&f=1",
                "display_name": "MSauce",
                "link": "https://stackoverflow.com/users/7885268/msauce"
            },
            "is_answered": false,
            "view_count": 15,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524166323,
            "creation_date": 1524166323,
            "question_id": 49928886,
            "body_markdown": "Is there a way to get cell validation to trigger when pasting to a cell in Excel?\r\n\r\nFor example I have a cell that only accepts an input of 10 characters, and if it goes beyond you can&#39;t enter.\r\n\r\n1234A12345\r\n\r\nBut if I paste, it overrides the validation rule.\r\n\r\n1234A12345/001\r\n\r\nI&#39;d ideally like to keep the ability to paste for this specific column table, as I have users entering 10s of rows of data, and i don&#39;t want them to manually input them every time. \r\n\r\nThanks!",
            "link": "https://stackoverflow.com/questions/49928886/ms-excel-apply-validation-to-cell-after-user-has-pasted",
            "title": "MS Excel - Apply Validation To Cell After User has Pasted",
            "body": "<p>Is there a way to get cell validation to trigger when pasting to a cell in Excel?</p>\n\n<p>For example I have a cell that only accepts an input of 10 characters, and if it goes beyond you can't enter.</p>\n\n<p>1234A12345</p>\n\n<p>But if I paste, it overrides the validation rule.</p>\n\n<p>1234A12345/001</p>\n\n<p>I'd ideally like to keep the ability to paste for this specific column table, as I have users entering 10s of rows of data, and i don't want them to manually input them every time. </p>\n\n<p>Thanks!</p>\n"
        },
        {
            "tags": [
                "c++",
                "portability",
                "bit-fields"
            ],
            "owner": {
                "reputation": 8058,
                "user_id": 193903,
                "user_type": "registered",
                "accept_rate": 83,
                "profile_image": "https://www.gravatar.com/avatar/f4305fec7fd7cd7389244122df912d16?s=128&d=identicon&r=PG",
                "display_name": "unkulunkulu",
                "link": "https://stackoverflow.com/users/193903/unkulunkulu"
            },
            "is_answered": true,
            "view_count": 390,
            "answer_count": 5,
            "score": 0,
            "last_activity_date": 1524166318,
            "creation_date": 1458302219,
            "last_edit_date": 1458305211,
            "question_id": 36083751,
            "body_markdown": "Say I have a bitfield like this:\r\n\r\n    struct SomeStruct {\r\n        uint32_t first : 12;\r\n        uint32_t second : 2;\r\n        uint32_t third : 18;\r\n    };\r\n\r\n    SomeStruct obj;\r\n\r\nI want to assign\r\n\r\n    obj.second = 3;  // Actually, the maximum allowed value\r\n\r\nWhat is the portable way to achieve this?\r\nI also don&#39;t want to use known bit field width explicitly, because that would require shotgun surgery should the field width change in the future.\r\n\r\nMy code used\r\n\r\n    obj.second = std::numeric_limits&lt;uint32_t&gt;::max()\r\n\r\nbut clang with `-Wbitfield-constant-conversion` gives a warning about it and [cpp reference states:](http://en.cppreference.com/w/cpp/language/bit_field)\r\n\r\n&gt; The following properties of bit fields are implementation-defined The\r\n&gt; value that results from assigning or initializing a bit field with a\r\n&gt; value out of range, or from incrementing a bit field past its range.\r\n\r\nSo is assigning `-1` or `numeric_limits&lt;uint32_t&gt;::max()` actually portable or is there any other way?",
            "link": "https://stackoverflow.com/questions/36083751/portable-way-to-assign-maximum-value-to-a-bitfield",
            "title": "Portable way to assign maximum value to a bitfield",
            "body": "<p>Say I have a bitfield like this:</p>\n\n<pre><code>struct SomeStruct {\n    uint32_t first : 12;\n    uint32_t second : 2;\n    uint32_t third : 18;\n};\n\nSomeStruct obj;\n</code></pre>\n\n<p>I want to assign</p>\n\n<pre><code>obj.second = 3;  // Actually, the maximum allowed value\n</code></pre>\n\n<p>What is the portable way to achieve this?\nI also don't want to use known bit field width explicitly, because that would require shotgun surgery should the field width change in the future.</p>\n\n<p>My code used</p>\n\n<pre><code>obj.second = std::numeric_limits&lt;uint32_t&gt;::max()\n</code></pre>\n\n<p>but clang with <code>-Wbitfield-constant-conversion</code> gives a warning about it and <a href=\"http://en.cppreference.com/w/cpp/language/bit_field\" rel=\"nofollow\">cpp reference states:</a></p>\n\n<blockquote>\n  <p>The following properties of bit fields are implementation-defined The\n  value that results from assigning or initializing a bit field with a\n  value out of range, or from incrementing a bit field past its range.</p>\n</blockquote>\n\n<p>So is assigning <code>-1</code> or <code>numeric_limits&lt;uint32_t&gt;::max()</code> actually portable or is there any other way?</p>\n"
        },
        {
            "tags": [
                "css",
                "reactjs",
                "webpack"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 9500377,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/64f61abaaf66d98351c70c18f39b5645?s=128&d=identicon&r=PG&f=1",
                "display_name": "kris1011",
                "link": "https://stackoverflow.com/users/9500377/kris1011"
            },
            "is_answered": false,
            "view_count": 30,
            "answer_count": 4,
            "score": 0,
            "last_activity_date": 1524166312,
            "creation_date": 1524158475,
            "last_edit_date": 1524160879,
            "question_id": 49926796,
            "body_markdown": "Hello I have problem with import css in React application and I don&#39;t know what is wrong in my code:\r\n\r\nError:\r\n\r\n133:1 Uncaught Error: Module parse failed: D:\\src\\styles\\styles.css Unexpected token (1:0)\r\nYou may need an appropriate loader to handle this file type.\r\n\r\n    |*{\r\n    |     color:red;\r\n    | }\r\n        at eval (133:1)\r\n        at Object.&lt;anonymous&gt; (bundle.js:979)\r\n        at __webpack_require__ (bundle.js:20)\r\n        at eval (app.js?bd9c:4)\r\n        at Object.&lt;anonymous&gt; (bundle.js:737)\r\n        at __webpack_require__ (bundle.js:20)\r\n        at Object.&lt;anonymous&gt; (bundle.js:405)\r\n        at __webpack_require__ (bundle.js:20)\r\n        at bundle.js:63\r\n        at bundle.js:66\r\n\r\nstyles.css (only test file):\r\n\r\n    *{\r\n    color:red;\r\n    } \r\n\r\nwebpack config.js:\r\n\r\n    const path = require(&#39;path&#39;);\r\n    \r\n    module.exports={\r\n        entry: &#39;./src/app.js&#39;,\r\n        output: {\r\n            path: path.join(__dirname, &#39;public&#39;),\r\n            filename: &#39;bundle.js&#39;\r\n        },\r\n        module:{\r\n            rules: [{\r\n                loader: &#39;babel-loader&#39;,\r\n                test: /\\.js$/,\r\n                exclude: /node_modules/\r\n            }, {\r\n                test: /\\.css$/,\r\n                use: [\r\n                    &#39;style-loader&#39;,\r\n                    &#39;css-loader&#39;\r\n                ]\r\n            }]\r\n        },\r\n        devtool: &#39;cheap-module-eval-source-map&#39;,\r\n        devServer:{\r\n            contentBase: path.join(__dirname, &#39;public&#39;)\r\n        }\r\n    };\r\n\r\npackage.json:\r\n\r\n    {\r\n      &quot;name&quot;: &quot;&quot;,\r\n      &quot;version&quot;: &quot;1.0.0&quot;,\r\n      &quot;main&quot;: &quot;index.js&quot;,\r\n      &quot;author&quot;: &quot;&quot;,\r\n      &quot;license&quot;: &quot;&quot;,\r\n      &quot;scripts&quot;: {\r\n        &quot;serve&quot;: &quot;live-server public/&quot;,\r\n        &quot;build&quot;: &quot;webpack&quot;,\r\n        &quot;dev-server&quot;: &quot;webpack-dev-server&quot;\r\n      },\r\n      &quot;dependencies&quot;: {\r\n        &quot;babel-cli&quot;: &quot;6.24.1&quot;,\r\n        &quot;babel-core&quot;: &quot;6.25.0&quot;,\r\n        &quot;babel-loader&quot;: &quot;7.1.1&quot;,\r\n        &quot;babel-plugin-transform-class-properties&quot;: &quot;6.24.1&quot;,\r\n        &quot;babel-preset-env&quot;: &quot;1.5.2&quot;,\r\n        &quot;babel-preset-react&quot;: &quot;6.24.1&quot;,\r\n        &quot;css-loader&quot;: &quot;0.28.4&quot;,\r\n        &quot;live-server&quot;: &quot;^1.2.0&quot;,\r\n        &quot;react&quot;: &quot;16.0.0&quot;,\r\n        &quot;react-dom&quot;: &quot;16.0.0&quot;,\r\n        &quot;react-modal&quot;: &quot;2.2.2&quot;,\r\n        &quot;style-loader&quot;: &quot;0.18.2&quot;,\r\n        &quot;validator&quot;: &quot;8.0.0&quot;,\r\n        &quot;webpack&quot;: &quot;3.1.0&quot;,\r\n        &quot;webpack-dev-server&quot;: &quot;2.5.1&quot;\r\n      }\r\n    }\r\n.babelrc :\r\n\r\n    {\r\n        &quot;presets&quot;:[\r\n            &quot;env&quot;,\r\n            &quot;react&quot;\r\n        ],\r\n        &quot;plugins&quot;:[\r\n            &quot;transform-class-properties&quot;   \r\n        ]\r\n    }\r\n\r\n\r\napp.js:\r\n\r\n    import React from &#39;react&#39;;\r\n    import ReactDOM from &#39;react-dom&#39;;\r\n    import &#39;./styles/styles.css&#39;;\r\n    ReactDOM.render(&lt;App/&gt;, document.getElementById(&#39;app&#39;));\r\n\r\nI dont have idea what is wrong ;?\r\n",
            "link": "https://stackoverflow.com/questions/49926796/cant-import-css-style-in-react-application",
            "title": "Can&#39;t import css style in React application",
            "body": "<p>Hello I have problem with import css in React application and I don't know what is wrong in my code:</p>\n\n<p>Error:</p>\n\n<p>133:1 Uncaught Error: Module parse failed: D:\\src\\styles\\styles.css Unexpected token (1:0)\nYou may need an appropriate loader to handle this file type.</p>\n\n<pre><code>|*{\n|     color:red;\n| }\n    at eval (133:1)\n    at Object.&lt;anonymous&gt; (bundle.js:979)\n    at __webpack_require__ (bundle.js:20)\n    at eval (app.js?bd9c:4)\n    at Object.&lt;anonymous&gt; (bundle.js:737)\n    at __webpack_require__ (bundle.js:20)\n    at Object.&lt;anonymous&gt; (bundle.js:405)\n    at __webpack_require__ (bundle.js:20)\n    at bundle.js:63\n    at bundle.js:66\n</code></pre>\n\n<p>styles.css (only test file):</p>\n\n<pre><code>*{\ncolor:red;\n} \n</code></pre>\n\n<p>webpack config.js:</p>\n\n<pre><code>const path = require('path');\n\nmodule.exports={\n    entry: './src/app.js',\n    output: {\n        path: path.join(__dirname, 'public'),\n        filename: 'bundle.js'\n    },\n    module:{\n        rules: [{\n            loader: 'babel-loader',\n            test: /\\.js$/,\n            exclude: /node_modules/\n        }, {\n            test: /\\.css$/,\n            use: [\n                'style-loader',\n                'css-loader'\n            ]\n        }]\n    },\n    devtool: 'cheap-module-eval-source-map',\n    devServer:{\n        contentBase: path.join(__dirname, 'public')\n    }\n};\n</code></pre>\n\n<p>package.json:</p>\n\n<pre><code>{\n  \"name\": \"\",\n  \"version\": \"1.0.0\",\n  \"main\": \"index.js\",\n  \"author\": \"\",\n  \"license\": \"\",\n  \"scripts\": {\n    \"serve\": \"live-server public/\",\n    \"build\": \"webpack\",\n    \"dev-server\": \"webpack-dev-server\"\n  },\n  \"dependencies\": {\n    \"babel-cli\": \"6.24.1\",\n    \"babel-core\": \"6.25.0\",\n    \"babel-loader\": \"7.1.1\",\n    \"babel-plugin-transform-class-properties\": \"6.24.1\",\n    \"babel-preset-env\": \"1.5.2\",\n    \"babel-preset-react\": \"6.24.1\",\n    \"css-loader\": \"0.28.4\",\n    \"live-server\": \"^1.2.0\",\n    \"react\": \"16.0.0\",\n    \"react-dom\": \"16.0.0\",\n    \"react-modal\": \"2.2.2\",\n    \"style-loader\": \"0.18.2\",\n    \"validator\": \"8.0.0\",\n    \"webpack\": \"3.1.0\",\n    \"webpack-dev-server\": \"2.5.1\"\n  }\n}\n</code></pre>\n\n<p>.babelrc :</p>\n\n<pre><code>{\n    \"presets\":[\n        \"env\",\n        \"react\"\n    ],\n    \"plugins\":[\n        \"transform-class-properties\"   \n    ]\n}\n</code></pre>\n\n<p>app.js:</p>\n\n<pre><code>import React from 'react';\nimport ReactDOM from 'react-dom';\nimport './styles/styles.css';\nReactDOM.render(&lt;App/&gt;, document.getElementById('app'));\n</code></pre>\n\n<p>I dont have idea what is wrong ;?</p>\n"
        },
        {
            "tags": [
                "macos",
                "apache",
                "codeigniter",
                "mamp",
                "vhosts"
            ],
            "owner": {
                "reputation": 15,
                "user_id": 3416624,
                "user_type": "registered",
                "profile_image": "https://i.stack.imgur.com/d8nLu.jpg?s=128&g=1",
                "display_name": "PtiSinge",
                "link": "https://stackoverflow.com/users/3416624/ptisinge"
            },
            "is_answered": true,
            "view_count": 27,
            "accepted_answer_id": 49927179,
            "answer_count": 1,
            "score": 1,
            "last_activity_date": 1524166306,
            "creation_date": 1524159373,
            "question_id": 49927022,
            "body_markdown": "I’m keen to find out if there is a way of properly run virtual hosts on a Mac with apache without having to use things like MAMP or WAMP.\r\nI have managed to get it to work for a small single page site and it worked seemlessly - However I am having no luck with trying to run a CodeIgniter frameworked site that way.\r\n\r\nI would love to hear from anyone who has managed to carry this out successfully. Please let me know! \r\n\r\nThanks a lot. ",
            "link": "https://stackoverflow.com/questions/49927022/codeigniter-site-on-virtual-host-on-mac-without-mamp",
            "title": "CodeIgniter site on Virtual Host on Mac without MAMP",
            "body": "<p>I’m keen to find out if there is a way of properly run virtual hosts on a Mac with apache without having to use things like MAMP or WAMP.\nI have managed to get it to work for a small single page site and it worked seemlessly - However I am having no luck with trying to run a CodeIgniter frameworked site that way.</p>\n\n<p>I would love to hear from anyone who has managed to carry this out successfully. Please let me know! </p>\n\n<p>Thanks a lot. </p>\n"
        },
        {
            "tags": [
                "c#",
                "visual-studio",
                "mstest"
            ],
            "owner": {
                "reputation": 16,
                "user_id": 8629143,
                "user_type": "registered",
                "profile_image": "https://i.stack.imgur.com/fvDEA.png?s=128&g=1",
                "display_name": "Geoffrey Wadsworth",
                "link": "https://stackoverflow.com/users/8629143/geoffrey-wadsworth"
            },
            "is_answered": true,
            "view_count": 19,
            "answer_count": 1,
            "score": 1,
            "last_activity_date": 1524166293,
            "creation_date": 1524160097,
            "question_id": 49927215,
            "body_markdown": "I have a VS2017 solution with three projects:\r\n\r\nSolution\r\n\r\n - Project A\r\n - Project B\r\n - Project Test\r\n\r\nSo I have a test that calls a method in Project A.  This method has a call that goes into Project B.  When I debug the test I am able to step into Project A.  When it comes time to step into Project B the debugger just steps over and not into the project.\r\n\r\nThe project configuration for all three projects is set to Debug.  At this point I have been unable to see why I am not able to debug into Project B.  ",
            "link": "https://stackoverflow.com/questions/49927215/mstest-does-not-debug-into-a-child-project",
            "title": "MsTest does not Debug into a child project",
            "body": "<p>I have a VS2017 solution with three projects:</p>\n\n<p>Solution</p>\n\n<ul>\n<li>Project A</li>\n<li>Project B</li>\n<li>Project Test</li>\n</ul>\n\n<p>So I have a test that calls a method in Project A.  This method has a call that goes into Project B.  When I debug the test I am able to step into Project A.  When it comes time to step into Project B the debugger just steps over and not into the project.</p>\n\n<p>The project configuration for all three projects is set to Debug.  At this point I have been unable to see why I am not able to debug into Project B.  </p>\n"
        },
        {
            "tags": [
                "ios",
                "css",
                "iphone",
                "iframe"
            ],
            "owner": {
                "reputation": 15,
                "user_id": 7109303,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/3b1d54a5de32f5d9bd0dbf2fcfe1cffe?s=128&d=identicon&r=PG&f=1",
                "display_name": "P-Dun-can",
                "link": "https://stackoverflow.com/users/7109303/p-dun-can"
            },
            "is_answered": false,
            "view_count": 82,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524166291,
            "creation_date": 1510137898,
            "last_edit_date": 1524166291,
            "question_id": 47177626,
            "body_markdown": "I am experiencing a weird issue with iframes displayng on some phones and not displaying on some phones. \r\n(Displays on all androids)\r\n(Does not work on iphone 6,7 but works on 7 plus and the 7S and a few other iphones)\r\n\r\n    &lt;div class=&quot;col-lg-6 col-md-6&quot;&gt;\r\n     &lt;iframe src=&#39;http://app.brandyourcar.com/signup/index/form-main-display-group-thingy&#39; style=&#39;border: 0;&#39; width=&#39;100%&#39; height=&#39;770px&#39; scrolling=&#39;no&#39;&gt;&lt;/iframe&gt;\r\n    &lt;/div&gt;enter code here\r\n\r\nI have tried a lot of the solutions on Stack and none seem to work for me.\r\n\r\nfew examples :1.) `&lt;div id=&quot;scroller&quot; style=&quot;height: 400px; width: 100%; overflow: auto;&quot;&gt;\r\n&lt;iframe height=&quot;100%&quot; id=&quot;iframe&quot; scrolling=&quot;no&quot; width=&quot;100%&quot; id=&quot;iframe&quot; src=&quot;url&quot; /&gt;\r\n&lt;/div&gt;`\r\n2.) `&lt;div id=&quot;scroller&quot; style=&quot;height: 400px; width: 100%; overflow: auto;&quot;&gt;\r\n&lt;iframe height=&quot;100%&quot; id=&quot;iframe&quot; scrolling=&quot;no&quot; width=&quot;100%&quot; id=&quot;iframe&quot; src=&quot;data/testdocument.pdf&quot; /&gt;\r\n&lt;/div&gt;\r\n`\r\nand many other Java script solutions.",
            "link": "https://stackoverflow.com/questions/47177626/iframe-display-issues-on-ios-iphones",
            "title": "Iframe display issues on iOS iPhones",
            "body": "<p>I am experiencing a weird issue with iframes displayng on some phones and not displaying on some phones. \n(Displays on all androids)\n(Does not work on iphone 6,7 but works on 7 plus and the 7S and a few other iphones)</p>\n\n<pre><code>&lt;div class=\"col-lg-6 col-md-6\"&gt;\n &lt;iframe src='http://app.brandyourcar.com/signup/index/form-main-display-group-thingy' style='border: 0;' width='100%' height='770px' scrolling='no'&gt;&lt;/iframe&gt;\n&lt;/div&gt;enter code here\n</code></pre>\n\n<p>I have tried a lot of the solutions on Stack and none seem to work for me.</p>\n\n<p>few examples :1.) <code>&lt;div id=\"scroller\" style=\"height: 400px; width: 100%; overflow: auto;\"&gt;\n&lt;iframe height=\"100%\" id=\"iframe\" scrolling=\"no\" width=\"100%\" id=\"iframe\" src=\"url\" /&gt;\n&lt;/div&gt;</code>\n2.) <code>&lt;div id=\"scroller\" style=\"height: 400px; width: 100%; overflow: auto;\"&gt;\n&lt;iframe height=\"100%\" id=\"iframe\" scrolling=\"no\" width=\"100%\" id=\"iframe\" src=\"data/testdocument.pdf\" /&gt;\n&lt;/div&gt;\n</code>\nand many other Java script solutions.</p>\n"
        },
        {
            "tags": [
                "python",
                "pandas"
            ],
            "owner": {
                "reputation": 707,
                "user_id": 7220459,
                "user_type": "registered",
                "accept_rate": 92,
                "profile_image": "https://www.gravatar.com/avatar/1501bfbbdc3e821d9ac7bdd9468796bb?s=128&d=identicon&r=PG",
                "display_name": "Codutie",
                "link": "https://stackoverflow.com/users/7220459/codutie"
            },
            "is_answered": true,
            "view_count": 150,
            "accepted_answer_id": 42659309,
            "answer_count": 3,
            "score": 0,
            "last_activity_date": 1524166290,
            "creation_date": 1488922665,
            "last_edit_date": 1488923021,
            "question_id": 42658809,
            "body_markdown": "This question has a big chance to be duplicated but I haven&#39;t found an answer yet. However, I&#39;m trying to apply a function to a pandas DataFrame and I want to have a DataFrame back. Followed example is reproducible:\r\n\r\n    df = pd.DataFrame({&#39;ID&#39;: [&quot;1&quot;,&quot;2&quot;],\r\n                       &#39;Start&#39;: datetime.strptime(&#39;20160701&#39;, &#39;%Y%m%d&#39;),\r\n                       &#39;End&#39;: datetime.strptime(&#39;20170701&#39;, &#39;%Y%m%d&#39;),\r\n                       &#39;Value&#39;: [100, 200],\r\n                       &#39;CreditNote&#39;: [-20, -30]})\r\n    \r\nMy function:\r\n\r\n    def act_value_calc(x):\r\n        start_delta = (x.Start.replace(day=31,month=12) - x.Start).days\r\n        full_delta = (x.End - x.Start).days\r\n        result1 = round( (x.Value + x.CreditNote) / full_delta * start_delta, 2)\r\n        result2 = round( (x.Value + x.CreditNote) - result1, 2)\r\n        return(pd.DataFrame({&#39;r1&#39;: [result1],&#39;r2&#39;: [result2]}))\r\n\r\nWhy I can not run the following code ...\r\n\r\n    df.apply(act_value_calc, 1)\r\n\r\nand what should be done to let it run? I mean to get a DataFrame or a list back with `result1` and `result2`?",
            "link": "https://stackoverflow.com/questions/42658809/python-how-to-return-a-dataframe-or-a-list-from-a-function",
            "title": "python: how to return a DataFrame or a list from a function?",
            "body": "<p>This question has a big chance to be duplicated but I haven't found an answer yet. However, I'm trying to apply a function to a pandas DataFrame and I want to have a DataFrame back. Followed example is reproducible:</p>\n\n<pre><code>df = pd.DataFrame({'ID': [\"1\",\"2\"],\n                   'Start': datetime.strptime('20160701', '%Y%m%d'),\n                   'End': datetime.strptime('20170701', '%Y%m%d'),\n                   'Value': [100, 200],\n                   'CreditNote': [-20, -30]})\n</code></pre>\n\n<p>My function:</p>\n\n<pre><code>def act_value_calc(x):\n    start_delta = (x.Start.replace(day=31,month=12) - x.Start).days\n    full_delta = (x.End - x.Start).days\n    result1 = round( (x.Value + x.CreditNote) / full_delta * start_delta, 2)\n    result2 = round( (x.Value + x.CreditNote) - result1, 2)\n    return(pd.DataFrame({'r1': [result1],'r2': [result2]}))\n</code></pre>\n\n<p>Why I can not run the following code ...</p>\n\n<pre><code>df.apply(act_value_calc, 1)\n</code></pre>\n\n<p>and what should be done to let it run? I mean to get a DataFrame or a list back with <code>result1</code> and <code>result2</code>?</p>\n"
        },
        {
            "tags": [
                "javascript",
                "node.js",
                "npm",
                "port"
            ],
            "owner": {
                "reputation": 533,
                "user_id": 2573690,
                "user_type": "registered",
                "accept_rate": 50,
                "profile_image": "https://www.gravatar.com/avatar/27f107da6213340c5fe9539465284fd4?s=128&d=identicon&r=PG",
                "display_name": "user2573690",
                "link": "https://stackoverflow.com/users/2573690/user2573690"
            },
            "is_answered": true,
            "view_count": 19037,
            "answer_count": 5,
            "score": 6,
            "last_activity_date": 1524166290,
            "creation_date": 1473028704,
            "last_edit_date": 1473029531,
            "question_id": 39322089,
            "body_markdown": "I have been working with a node.js project for a few weeks and it has been working great. Usually I use &#39;npm start&#39; to run my app and view it in a browser at on localhost, port 3000.\r\n\r\nToday, I started to get the following error while using npm start:\r\n\r\n&lt;!-- language: lang-none --&gt;\r\n\r\n    Server started on port 3000                                                                                                                                                                                         \r\n    Port 3000 is already in use \r\n\r\nI have checked the resource monitor and I have no other process running on port 3000. Why would I be getting this error message?\r\n\r\nIn my app.js I have the following code to set the port...is this incorrect? It worked fine before so I&#39;m not sure what I am doing wrong.\r\n\r\n    // Set Port\r\n    app.set(&#39;port&#39;, (process.env.PORT || 3000));\r\n    app.listen(app.get(&#39;port&#39;), function() {\r\n        console.log(&#39;Server started on port &#39;+app.get(&#39;port&#39;));\r\n    });\r\n\r\nThanks for the help! \r\n\r\nEDIT:\r\nI have tried running netstat and TCPView to check what process is using the port, but there is nothing using that port. I also tried restarting my laptop but I still get the same error. ",
            "link": "https://stackoverflow.com/questions/39322089/node-js-port-3000-already-in-use-but-it-actually-isnt",
            "title": "Node.js Port 3000 already in use but it actually isn&#39;t?",
            "body": "<p>I have been working with a node.js project for a few weeks and it has been working great. Usually I use 'npm start' to run my app and view it in a browser at on localhost, port 3000.</p>\n\n<p>Today, I started to get the following error while using npm start:</p>\n\n<pre class=\"lang-none prettyprint-override\"><code>Server started on port 3000                                                                                                                                                                                         \nPort 3000 is already in use \n</code></pre>\n\n<p>I have checked the resource monitor and I have no other process running on port 3000. Why would I be getting this error message?</p>\n\n<p>In my app.js I have the following code to set the port...is this incorrect? It worked fine before so I'm not sure what I am doing wrong.</p>\n\n<pre><code>// Set Port\napp.set('port', (process.env.PORT || 3000));\napp.listen(app.get('port'), function() {\n    console.log('Server started on port '+app.get('port'));\n});\n</code></pre>\n\n<p>Thanks for the help! </p>\n\n<p>EDIT:\nI have tried running netstat and TCPView to check what process is using the port, but there is nothing using that port. I also tried restarting my laptop but I still get the same error. </p>\n"
        },
        {
            "tags": [
                "android",
                "unit-testing",
                "communication",
                "accessory"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 7727721,
                "user_type": "registered",
                "profile_image": "https://lh5.googleusercontent.com/-nILQirep2TI/AAAAAAAAAAI/AAAAAAAAK9U/iZjDjDMul_I/photo.jpg?sz=128",
                "display_name": "gpat",
                "link": "https://stackoverflow.com/users/7727721/gpat"
            },
            "is_answered": false,
            "view_count": 17,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524166282,
            "creation_date": 1524161492,
            "question_id": 49927578,
            "body_markdown": "I have USB communication in accessory mode in android application project.\r\nDo you guys have suggestion for approach to do unit test for functionality of communication with external device (It is Ubuntu in real implementation).\r\n\r\nAlso, if I make entirely different class for service to mock the communication, is it worthy unit test (As completely different class will work in real)?\r\n\r\nThank you!",
            "link": "https://stackoverflow.com/questions/49927578/unit-test-in-android-usb-communication-in-accessory-mode",
            "title": "Unit test in Android USB Communication in Accessory mode",
            "body": "<p>I have USB communication in accessory mode in android application project.\nDo you guys have suggestion for approach to do unit test for functionality of communication with external device (It is Ubuntu in real implementation).</p>\n\n<p>Also, if I make entirely different class for service to mock the communication, is it worthy unit test (As completely different class will work in real)?</p>\n\n<p>Thank you!</p>\n"
        },
        {
            "tags": [
                "javascript",
                "reactjs",
                "storybook"
            ],
            "owner": {
                "reputation": 16,
                "user_id": 4871041,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/6c4fe2e0ebdaae2c3f0da38013791942?s=128&d=identicon&r=PG&f=1",
                "display_name": "Josh Greenhalgh",
                "link": "https://stackoverflow.com/users/4871041/josh-greenhalgh"
            },
            "is_answered": false,
            "view_count": 16,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524166270,
            "creation_date": 1524166270,
            "question_id": 49928874,
            "body_markdown": "I am trying to start using storybook on a fresh create-react-app project and I am running into an error (at end of this issue). I know that this is not a bug since I can successfully get things working in a node:alpine container. It is therefore an issue with my local setup but I am at a loss to see what it may be! Any help would be much appreciated. Some information;\r\n\r\n    $ which node\r\n    ~/.nvm/versions/node/v9.11.1/bin/node\r\n    $ which npm\r\n    ~/.nvm/versions/node/v9.11.1/bin/npm\r\n\r\nI am using the most recent (I think) node installed using nvm.\r\n\r\n    $ create-react-app --version\r\n    1.5.2\r\n    $ getstorybook --version\r\n    3.4.2\r\n\r\nI run the following commands;\r\n\r\n    create-react-app app --use-npm\r\n    cd app\r\n    getstorybook -N\r\n    npm run storybook\r\n\r\nThe resulting error is the following;\r\n    \r\n    ERROR in ./.storybook/addons.js\r\n    Module build failed: Error: Cannot find module &#39;@babel/core&#39;\r\n        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)\r\n        at Function.Module._load (internal/modules/cjs/loader.js:475:25)\r\n        at Module.require (internal/modules/cjs/loader.js:598:17)\r\n        at require (internal/modules/cjs/helpers.js:11:18)\r\n        at Object.&lt;anonymous&gt; (/Users/joshuagreenhalgh/scratch/app/node_modules/babel-core/index.js:2:18)\r\n        at Module._compile (internal/modules/cjs/loader.js:654:30)\r\n        at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)\r\n        at Module.load (internal/modules/cjs/loader.js:566:32)\r\n        at tryModuleLoad (internal/modules/cjs/loader.js:506:12)\r\n        at Function.Module._load (internal/modules/cjs/loader.js:498:3)\r\n     @ multi ./.storybook/addons.js ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js\r\n    \r\n    ERROR in ./.storybook/config.js\r\n    Module build failed: Error: Cannot find module &#39;@babel/core&#39;\r\n        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)\r\n        at Function.Module._load (internal/modules/cjs/loader.js:475:25)\r\n        at Module.require (internal/modules/cjs/loader.js:598:17)\r\n        at require (internal/modules/cjs/helpers.js:11:18)\r\n        at Object.&lt;anonymous&gt; (/Users/joshuagreenhalgh/scratch/app/node_modules/babel-core/index.js:2:18)\r\n        at Module._compile (internal/modules/cjs/loader.js:654:30)\r\n        at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)\r\n        at Module.load (internal/modules/cjs/loader.js:566:32)\r\n        at tryModuleLoad (internal/modules/cjs/loader.js:506:12)\r\n        at Function.Module._load (internal/modules/cjs/loader.js:498:3)\r\n     @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js\r\n\r\n\r\nAny help in understanding what may be wrong with my local setup would be of great use! ",
            "link": "https://stackoverflow.com/questions/49928874/i-need-help-understanding-why-storybook-is-borking-about-babel-dependency",
            "title": "I need help understanding why storybook is borking about babel dependency",
            "body": "<p>I am trying to start using storybook on a fresh create-react-app project and I am running into an error (at end of this issue). I know that this is not a bug since I can successfully get things working in a node:alpine container. It is therefore an issue with my local setup but I am at a loss to see what it may be! Any help would be much appreciated. Some information;</p>\n\n<pre><code>$ which node\n~/.nvm/versions/node/v9.11.1/bin/node\n$ which npm\n~/.nvm/versions/node/v9.11.1/bin/npm\n</code></pre>\n\n<p>I am using the most recent (I think) node installed using nvm.</p>\n\n<pre><code>$ create-react-app --version\n1.5.2\n$ getstorybook --version\n3.4.2\n</code></pre>\n\n<p>I run the following commands;</p>\n\n<pre><code>create-react-app app --use-npm\ncd app\ngetstorybook -N\nnpm run storybook\n</code></pre>\n\n<p>The resulting error is the following;</p>\n\n<pre><code>ERROR in ./.storybook/addons.js\nModule build failed: Error: Cannot find module '@babel/core'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:475:25)\n    at Module.require (internal/modules/cjs/loader.js:598:17)\n    at require (internal/modules/cjs/helpers.js:11:18)\n    at Object.&lt;anonymous&gt; (/Users/joshuagreenhalgh/scratch/app/node_modules/babel-core/index.js:2:18)\n    at Module._compile (internal/modules/cjs/loader.js:654:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)\n    at Module.load (internal/modules/cjs/loader.js:566:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:498:3)\n @ multi ./.storybook/addons.js ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js\n\nERROR in ./.storybook/config.js\nModule build failed: Error: Cannot find module '@babel/core'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:475:25)\n    at Module.require (internal/modules/cjs/loader.js:598:17)\n    at require (internal/modules/cjs/helpers.js:11:18)\n    at Object.&lt;anonymous&gt; (/Users/joshuagreenhalgh/scratch/app/node_modules/babel-core/index.js:2:18)\n    at Module._compile (internal/modules/cjs/loader.js:654:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)\n    at Module.load (internal/modules/cjs/loader.js:566:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:498:3)\n @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js\n</code></pre>\n\n<p>Any help in understanding what may be wrong with my local setup would be of great use! </p>\n"
        },
        {
            "tags": [
                "haskell",
                "combinatorics",
                "powerset"
            ],
            "owner": {
                "reputation": 884,
                "user_id": 1747134,
                "user_type": "registered",
                "accept_rate": 93,
                "profile_image": "https://www.gravatar.com/avatar/696bad3bd2c5e16ded04f3cdf436623f?s=128&d=identicon&r=PG",
                "display_name": "user1747134",
                "link": "https://stackoverflow.com/users/1747134/user1747134"
            },
            "is_answered": true,
            "view_count": 123,
            "accepted_answer_id": 47755490,
            "answer_count": 3,
            "score": 8,
            "last_activity_date": 1524166270,
            "creation_date": 1513003022,
            "last_edit_date": 1513003519,
            "question_id": 47755231,
            "body_markdown": "I would like to have a function\r\n\r\n    powersetWithComplements :: [a] -&gt; [([a], [a])]\r\n\r\nSuch that for example:\r\n\r\n    powersetWithComplements [1,2,3] = [([],[1,2,3]),([3],[1,2]),([2],[1,3]),([2,3],[1]),([1],[2,3]),([1,3],[2]),([1,2],[3]),([1,2,3],[])]\r\n\r\nIt is easy to obtain some implementation, for example\r\n    \r\n    powerset :: [a] -&gt; [[a]]\r\n    powerset = filterM (const [False, True])\r\n    \r\n    powersetWithComplements s = let p = powerset s in zip p (reverse p)\r\n\r\nOr\r\n\r\n    powersetWithComplements s = [ (x, s \\\\ x) | x &lt;- powerset s]\r\n\r\nBut I estimate that the performance of both these would be really poor. What would be an optimal approach? It is possible to use different data structure than the `[]` list.",
            "link": "https://stackoverflow.com/questions/47755231/fast-powerset-implementation-with-complement-set",
            "title": "Fast powerset implementation with complement set",
            "body": "<p>I would like to have a function</p>\n\n<pre><code>powersetWithComplements :: [a] -&gt; [([a], [a])]\n</code></pre>\n\n<p>Such that for example:</p>\n\n<pre><code>powersetWithComplements [1,2,3] = [([],[1,2,3]),([3],[1,2]),([2],[1,3]),([2,3],[1]),([1],[2,3]),([1,3],[2]),([1,2],[3]),([1,2,3],[])]\n</code></pre>\n\n<p>It is easy to obtain some implementation, for example</p>\n\n<pre><code>powerset :: [a] -&gt; [[a]]\npowerset = filterM (const [False, True])\n\npowersetWithComplements s = let p = powerset s in zip p (reverse p)\n</code></pre>\n\n<p>Or</p>\n\n<pre><code>powersetWithComplements s = [ (x, s \\\\ x) | x &lt;- powerset s]\n</code></pre>\n\n<p>But I estimate that the performance of both these would be really poor. What would be an optimal approach? It is possible to use different data structure than the <code>[]</code> list.</p>\n"
        },
        {
            "tags": [
                "arrays",
                "wordpress",
                "taxonomy"
            ],
            "owner": {
                "reputation": 84,
                "user_id": 6635618,
                "user_type": "registered",
                "accept_rate": 76,
                "profile_image": "https://www.gravatar.com/avatar/76313652b1cf177e25faaa54fa1be515?s=128&d=identicon&r=PG&f=1",
                "display_name": "Chris",
                "link": "https://stackoverflow.com/users/6635618/chris"
            },
            "is_answered": false,
            "view_count": 24,
            "answer_count": 1,
            "score": -1,
            "last_activity_date": 1524166263,
            "creation_date": 1524133183,
            "last_edit_date": 1524166263,
            "question_id": 49918605,
            "body_markdown": "I have set up a custom post type in wordpress called &quot;Portfolio&quot;. The custom post type then has two taxonomy&#39;s set up. They are named &#39;portfolio_categories&#39; and &#39;portfolio_sector&#39;.\r\n\r\nCurrently i am using the following code to gather all my &#39;portfolio_categories&#39; and store them so they can then be outputted as CSS class to be used for filtering.\r\n\r\n    &lt;?php while ( $the_query-&gt;have_posts() ) : $the_query-&gt;the_post(); \r\n     $termsArray = get_the_terms( $post-&gt;ID, &quot;portfolio_categories&quot; );  //Get the terms for this particular item\r\n     $termsString = &quot;&quot;; //initialize the string that will contain the terms\r\n     foreach ( $termsArray as $term ) { // for each term \r\n     $termsString .= $term-&gt;slug.&#39; &#39;; //create a string that has all the slugs \r\n    }\r\n    ?&gt; \r\n\r\nThen the code to output the terms as classes is as follows:\r\n\r\n    &lt;div class=&quot;&lt;?php echo $termsString; ?&gt;&quot;&gt;\r\n    Content goes here\r\n    &lt;/div&gt;\r\n\r\nHow would i need to edit my code in order to store the taxonomy &#39;portfolio_sector&#39; and output them as classes also?",
            "link": "https://stackoverflow.com/questions/49918605/wp-custom-post-type-display-taxonomy-as-css-class",
            "title": "WP Custom Post Type - Display taxonomy as CSS class",
            "body": "<p>I have set up a custom post type in wordpress called \"Portfolio\". The custom post type then has two taxonomy's set up. They are named 'portfolio_categories' and 'portfolio_sector'.</p>\n\n<p>Currently i am using the following code to gather all my 'portfolio_categories' and store them so they can then be outputted as CSS class to be used for filtering.</p>\n\n<pre><code>&lt;?php while ( $the_query-&gt;have_posts() ) : $the_query-&gt;the_post(); \n $termsArray = get_the_terms( $post-&gt;ID, \"portfolio_categories\" );  //Get the terms for this particular item\n $termsString = \"\"; //initialize the string that will contain the terms\n foreach ( $termsArray as $term ) { // for each term \n $termsString .= $term-&gt;slug.' '; //create a string that has all the slugs \n}\n?&gt; \n</code></pre>\n\n<p>Then the code to output the terms as classes is as follows:</p>\n\n<pre><code>&lt;div class=\"&lt;?php echo $termsString; ?&gt;\"&gt;\nContent goes here\n&lt;/div&gt;\n</code></pre>\n\n<p>How would i need to edit my code in order to store the taxonomy 'portfolio_sector' and output them as classes also?</p>\n"
        },
        {
            "tags": [
                "javascript",
                "d3.js",
                "graph"
            ],
            "owner": {
                "reputation": 44,
                "user_id": 9007768,
                "user_type": "registered",
                "accept_rate": 71,
                "profile_image": "https://www.gravatar.com/avatar/7ab2ca87ab933e06bbabfb5b6810dd14?s=128&d=identicon&r=PG&f=1",
                "display_name": "KT Works",
                "link": "https://stackoverflow.com/users/9007768/kt-works"
            },
            "is_answered": false,
            "view_count": 79,
            "bounty_amount": 50,
            "bounty_closes_date": 1524676389,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524166254,
            "creation_date": 1523884130,
            "last_edit_date": 1524073680,
            "question_id": 49858153,
            "body_markdown": "i want to update the circles and the paths in this graph with a transition. However it does not work. \r\n\r\nI am not very experienced with D3. How can i make my code better? Changing data structure is no problem. I want bind the data to graph with exit() remove() and enter() without deleting whole graph and add the data everytime i update again. I dont know how to use enter() exit() and remove() for nested data. One time for the whole group and the other side updating the circle and paths. The id should be fixed.\r\n\r\nhere i a little single line example from d3noob. [link][1]\r\n\r\n----------\r\n\r\n\r\nhere is a [JS Fiddle][2]\r\n\r\n\r\n    var data = [{\r\n        id: &#39;p1&#39;,\r\n        points: [{\r\n          point: {\r\n            x: 10,\r\n            y: 10\r\n          }\r\n        }, {\r\n          point: {\r\n            x: 100,\r\n            y: 30\r\n          }\r\n        }]\r\n      },\r\n      {\r\n        id: &#39;p2&#39;,\r\n        points: [{\r\n            point: {\r\n              x: 30,\r\n              y: 100\r\n            }\r\n          }, {\r\n            point: {\r\n              x: 230,\r\n              y: 30\r\n            }\r\n          },\r\n          {\r\n            point: {\r\n              x: 50,\r\n              y: 200\r\n            }\r\n          },\r\n          {\r\n            point: {\r\n              x: 50,\r\n              y: 300\r\n            }\r\n          },\r\n        ]\r\n      }\r\n    ];\r\n    \r\n    var svg = d3.select(&quot;svg&quot;);\r\n    \r\n    var line = d3.line()\r\n      .x((d) =&gt; d.point.x)\r\n      .y((d) =&gt; d.point.y);\r\n    \r\n    function updateGraph() {\r\n      console.log(&#39;dataset contains&#39;, data.length, &#39;item(s)&#39;)\r\n      var allGroup = svg.selectAll(&quot;.pathGroup&quot;).data(data, function(d) {\r\n        return d.id\r\n      });\r\n      var g = allGroup.enter()\r\n        .append(&quot;g&quot;)\r\n        .attr(&quot;class&quot;, &quot;pathGroup&quot;)\r\n      allGroup.exit().remove()\r\n    \r\n      g.append(&quot;path&quot;)\r\n        .attr(&quot;class&quot;, &quot;line&quot;)\r\n        .attr(&quot;stroke&quot;, &quot;red&quot;)\r\n        .attr(&quot;stroke-width&quot;, &quot;1px&quot;)\r\n        .transition()\r\n        .duration(500)\r\n        .attr(&quot;d&quot;, function(d) {\r\n          return line(d.points)\r\n        });\r\n    \r\n      g.selectAll(&quot;path&quot;)\r\n      .transition()\r\n      .duration(500)\r\n      .attr(&quot;d&quot;, function(d) {\r\n        return line(d.points)\r\n      });\r\n    \r\n      g.selectAll(&quot;circle&quot;)\r\n        .data(d =&gt; d.points)\r\n        .enter()\r\n        .append(&quot;circle&quot;)\r\n        .attr(&quot;r&quot;, 4)\r\n        .attr(&quot;fill&quot;, &quot;teal&quot;)\r\n        .attr(&quot;cx&quot;, function(d) {\r\n          return d.point.x\r\n        })\r\n        .attr(&quot;cy&quot;, function(d) {\r\n          return d.point.y\r\n        })\r\n        .exit().remove()\r\n    \r\n    }\r\n    updateGraph()\r\n    \r\n    document.getElementById(&#39;update&#39;).onclick = function(e) {\r\n    \r\n      data = [{\r\n          id: &#39;p1&#39;,\r\n          points: [{\r\n            point: {\r\n              x: 10,\r\n              y: 10\r\n            }\r\n          }, {\r\n            point: {\r\n              x: 100,\r\n              y: 30\r\n            }\r\n          }]\r\n        },\r\n        {\r\n          id: &#39;p2&#39;,\r\n          points: [{\r\n              point: {\r\n                x: 30,\r\n                y: 100\r\n              }\r\n            }, {\r\n              point: {\r\n                x: 230,\r\n                y: 30\r\n              }\r\n            },\r\n            {\r\n              point: {\r\n                x: 50,\r\n                y: 300\r\n              }\r\n            },\r\n          ]\r\n        }\r\n      ];\r\n      updateGraph()\r\n    }\r\n    \r\n    \r\n    $(&#39;#cb1&#39;).click(function() {\r\n      if ($(this).is(&#39;:checked&#39;)) {\r\n        data = [{\r\n            id: &#39;p1&#39;,\r\n            points: [{\r\n              point: {\r\n                x: 10,\r\n                y: 10\r\n              }\r\n            }, {\r\n              point: {\r\n                x: 100,\r\n                y: 30\r\n              }\r\n            }]\r\n          },\r\n          {\r\n            id: &#39;p2&#39;,\r\n            points: [{\r\n                point: {\r\n                  x: 30,\r\n                  y: 100\r\n                }\r\n              }, {\r\n                point: {\r\n                  x: 230,\r\n                  y: 30\r\n                }\r\n              },\r\n              {\r\n                point: {\r\n                  x: 50,\r\n                  y: 200\r\n                }\r\n              },\r\n              {\r\n                point: {\r\n                  x: 50,\r\n                  y: 300\r\n                }\r\n              },\r\n            ]\r\n          }\r\n        ];\r\n    \r\n      } else {\r\n        data = [{\r\n          id: &#39;p1&#39;,\r\n          points: [{\r\n            point: {\r\n              x: 10,\r\n              y: 10\r\n            }\r\n          }, {\r\n            point: {\r\n              x: 100,\r\n              y: 30\r\n            }\r\n          }]\r\n        }];\r\n      }\r\n      updateGraph()\r\n    });\r\n\r\n\r\n  [1]: http://bl.ocks.org/d3noob/7030f35b72de721622b8\r\n  [2]: https://jsfiddle.net/wj266kmx/",
            "link": "https://stackoverflow.com/questions/49858153/d3-multiline-update-path-and-transition-path-does-not-work-with-nested-data",
            "title": "d3 multiline update path and transition path does not work with nested data",
            "body": "<p>i want to update the circles and the paths in this graph with a transition. However it does not work. </p>\n\n<p>I am not very experienced with D3. How can i make my code better? Changing data structure is no problem. I want bind the data to graph with exit() remove() and enter() without deleting whole graph and add the data everytime i update again. I dont know how to use enter() exit() and remove() for nested data. One time for the whole group and the other side updating the circle and paths. The id should be fixed.</p>\n\n<p>here i a little single line example from d3noob. <a href=\"http://bl.ocks.org/d3noob/7030f35b72de721622b8\" rel=\"nofollow noreferrer\">link</a></p>\n\n<hr>\n\n<p>here is a <a href=\"https://jsfiddle.net/wj266kmx/\" rel=\"nofollow noreferrer\">JS Fiddle</a></p>\n\n<pre><code>var data = [{\n    id: 'p1',\n    points: [{\n      point: {\n        x: 10,\n        y: 10\n      }\n    }, {\n      point: {\n        x: 100,\n        y: 30\n      }\n    }]\n  },\n  {\n    id: 'p2',\n    points: [{\n        point: {\n          x: 30,\n          y: 100\n        }\n      }, {\n        point: {\n          x: 230,\n          y: 30\n        }\n      },\n      {\n        point: {\n          x: 50,\n          y: 200\n        }\n      },\n      {\n        point: {\n          x: 50,\n          y: 300\n        }\n      },\n    ]\n  }\n];\n\nvar svg = d3.select(\"svg\");\n\nvar line = d3.line()\n  .x((d) =&gt; d.point.x)\n  .y((d) =&gt; d.point.y);\n\nfunction updateGraph() {\n  console.log('dataset contains', data.length, 'item(s)')\n  var allGroup = svg.selectAll(\".pathGroup\").data(data, function(d) {\n    return d.id\n  });\n  var g = allGroup.enter()\n    .append(\"g\")\n    .attr(\"class\", \"pathGroup\")\n  allGroup.exit().remove()\n\n  g.append(\"path\")\n    .attr(\"class\", \"line\")\n    .attr(\"stroke\", \"red\")\n    .attr(\"stroke-width\", \"1px\")\n    .transition()\n    .duration(500)\n    .attr(\"d\", function(d) {\n      return line(d.points)\n    });\n\n  g.selectAll(\"path\")\n  .transition()\n  .duration(500)\n  .attr(\"d\", function(d) {\n    return line(d.points)\n  });\n\n  g.selectAll(\"circle\")\n    .data(d =&gt; d.points)\n    .enter()\n    .append(\"circle\")\n    .attr(\"r\", 4)\n    .attr(\"fill\", \"teal\")\n    .attr(\"cx\", function(d) {\n      return d.point.x\n    })\n    .attr(\"cy\", function(d) {\n      return d.point.y\n    })\n    .exit().remove()\n\n}\nupdateGraph()\n\ndocument.getElementById('update').onclick = function(e) {\n\n  data = [{\n      id: 'p1',\n      points: [{\n        point: {\n          x: 10,\n          y: 10\n        }\n      }, {\n        point: {\n          x: 100,\n          y: 30\n        }\n      }]\n    },\n    {\n      id: 'p2',\n      points: [{\n          point: {\n            x: 30,\n            y: 100\n          }\n        }, {\n          point: {\n            x: 230,\n            y: 30\n          }\n        },\n        {\n          point: {\n            x: 50,\n            y: 300\n          }\n        },\n      ]\n    }\n  ];\n  updateGraph()\n}\n\n\n$('#cb1').click(function() {\n  if ($(this).is(':checked')) {\n    data = [{\n        id: 'p1',\n        points: [{\n          point: {\n            x: 10,\n            y: 10\n          }\n        }, {\n          point: {\n            x: 100,\n            y: 30\n          }\n        }]\n      },\n      {\n        id: 'p2',\n        points: [{\n            point: {\n              x: 30,\n              y: 100\n            }\n          }, {\n            point: {\n              x: 230,\n              y: 30\n            }\n          },\n          {\n            point: {\n              x: 50,\n              y: 200\n            }\n          },\n          {\n            point: {\n              x: 50,\n              y: 300\n            }\n          },\n        ]\n      }\n    ];\n\n  } else {\n    data = [{\n      id: 'p1',\n      points: [{\n        point: {\n          x: 10,\n          y: 10\n        }\n      }, {\n        point: {\n          x: 100,\n          y: 30\n        }\n      }]\n    }];\n  }\n  updateGraph()\n});\n</code></pre>\n"
        },
        {
            "tags": [
                "r",
                "non-standard-evaluation"
            ],
            "owner": {
                "reputation": 18,
                "user_id": 5272985,
                "user_type": "registered",
                "profile_image": "https://i.stack.imgur.com/z7uxD.jpg?s=128&g=1",
                "display_name": "Jake Oliver Stephen",
                "link": "https://stackoverflow.com/users/5272985/jake-oliver-stephen"
            },
            "is_answered": true,
            "view_count": 33,
            "accepted_answer_id": 49928865,
            "answer_count": 2,
            "score": 1,
            "last_activity_date": 1524166241,
            "creation_date": 1524164907,
            "question_id": 49928500,
            "body_markdown": "I am attempting to use a dynamic string in a `dplyr` `pipe` and a `lapply` function. Where the string is used to name a column which is later used within a `filter`. The issue occurs where attempting filter to remove any rows with a resultant NA (using `!is.na()`) within the `filter`. \r\n\r\nTypically one would use Non-standard evaluation such as `filter_` for such a situation, however due to the called string being within `is.na()`, the `filter_` has no effect. I require the string to be called wrapped using the prime symbol (`) as opposed to quotation marks (&quot;).\r\n\r\nBelow is a minimal example minus the `lapply` function.\r\n\r\n    df &lt;- data.frame(&quot;one&quot;=c(1,2,3,4),&quot;two&quot;=c(4,NA,2,1))\r\n    storeddate &lt;- &quot;Jan17-01-92&quot;\r\n    finaldf &lt;- df %&gt;%\r\n     mutate(!!storeddate := one+two) %&gt;%\r\n     filter(!is.na(storeddate)) #the storeddate string call requires formatting as `Jan17-01-92` as opposed to &quot;Jan17-01-92&quot;.\r\n\r\nI am aware that I could simply reformat the initial string, however I am more curious of finding a way to calls strings wrapped in a different format for use within other scenarios.",
            "link": "https://stackoverflow.com/questions/49928500/r-non-standard-evaluation-of-dynamic-variables-within-pipes-replacing-with",
            "title": "R: Non-standard evaluation of dynamic variables within pipes. Replacing (&quot;) with (`)",
            "body": "<p>I am attempting to use a dynamic string in a <code>dplyr</code> <code>pipe</code> and a <code>lapply</code> function. Where the string is used to name a column which is later used within a <code>filter</code>. The issue occurs where attempting filter to remove any rows with a resultant NA (using <code>!is.na()</code>) within the <code>filter</code>. </p>\n\n<p>Typically one would use Non-standard evaluation such as <code>filter_</code> for such a situation, however due to the called string being within <code>is.na()</code>, the <code>filter_</code> has no effect. I require the string to be called wrapped using the prime symbol (`) as opposed to quotation marks (\").</p>\n\n<p>Below is a minimal example minus the <code>lapply</code> function.</p>\n\n<pre><code>df &lt;- data.frame(\"one\"=c(1,2,3,4),\"two\"=c(4,NA,2,1))\nstoreddate &lt;- \"Jan17-01-92\"\nfinaldf &lt;- df %&gt;%\n mutate(!!storeddate := one+two) %&gt;%\n filter(!is.na(storeddate)) #the storeddate string call requires formatting as `Jan17-01-92` as opposed to \"Jan17-01-92\".\n</code></pre>\n\n<p>I am aware that I could simply reformat the initial string, however I am more curious of finding a way to calls strings wrapped in a different format for use within other scenarios.</p>\n"
        },
        {
            "tags": [
                "php",
                "mysql"
            ],
            "owner": {
                "reputation": 16,
                "user_id": 7874945,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/3ea213719c34b3196f39471f93b945fb?s=128&d=identicon&r=PG&f=1",
                "display_name": "AdamElsbury",
                "link": "https://stackoverflow.com/users/7874945/adamelsbury"
            },
            "is_answered": false,
            "view_count": 28,
            "answer_count": 0,
            "score": -2,
            "last_activity_date": 1524166233,
            "creation_date": 1524160942,
            "last_edit_date": 1524166233,
            "question_id": 49927442,
            "body_markdown": "The while loop inside the if statement works, but if the condition is not met, the error code in the else does not display.\r\n\r\nThis is the fourth iteration of me attempting to display the error message and I cannot get it to work.\r\n\r\n    &lt;?php\r\n    $a = $_GET[&quot;product&quot;];\r\n    $id = $_GET[&quot;ID&quot;];\r\n\r\n    echo &quot;&lt;h1&gt;You are searching for $a &lt;/h1&gt;&quot;;\r\n\r\n    $conn = new PDO (&quot;mysql:host=localhost;dbname=#;&quot;, &quot;#&quot;, &quot;#&quot;);\r\n    $results = $conn-&gt;query(&quot;select * from products where name=&#39;$a&#39;&quot;);\r\n\r\n    if ($row=$results == 1) {\r\n        while ($row=$results-&gt;fetch()) {\r\n            echo &quot;&lt;p&gt;&quot;;\r\n            echo &quot; Name &quot; . $row[&quot;name&quot;] . &quot;&lt;br/&gt; &quot;;\r\n            echo &quot; Manufacturer &quot; .$row[&quot;manufacturer&quot;]. &quot;&lt;br/&gt;&quot;;\r\n            echo &quot; Description &quot; .$row[&quot;description&quot;]. &quot;&lt;br/&gt;&quot;;\r\n            echo &quot; Price &quot; .$row[&quot;price&quot;]. &quot;&lt;br/&gt;&quot;;\r\n            echo &quot; Stock Level &quot; .$row[&quot;stocklevel&quot;]. &quot;&lt;br/&gt;&quot;;\r\n            echo &quot; Age Limit &quot; .$row[&quot;agelimit&quot;]. &quot;&lt;br/&gt;&quot;;\r\n            echo &quot;&lt;a href=&#39;quantity.php?ID=&quot; . $row[&quot;ID&quot;] . &quot;&#39;&gt;Click here to buy more than one&lt;/a&gt;&quot;;\r\n            echo &quot;&lt;a href=&#39;purchase.php?ID=&quot; . $row[&quot;ID&quot;] . &quot;&#39;&gt;Click here to buy one&lt;/a&gt;&quot;;\r\n            echo &quot;&lt;/p&gt;&quot;;\r\n        }\r\n    } else {\r\n        echo (&quot;There are no products matching your search terms!&quot;);\r\n    }\r\n    ?&gt;",
            "link": "https://stackoverflow.com/questions/49927442/else-statement-not-printing-error-message-in-php-with-if-while",
            "title": "Else statement not printing error message in PHP with IF - WHILE",
            "body": "<p>The while loop inside the if statement works, but if the condition is not met, the error code in the else does not display.</p>\n\n<p>This is the fourth iteration of me attempting to display the error message and I cannot get it to work.</p>\n\n<pre><code>&lt;?php\n$a = $_GET[\"product\"];\n$id = $_GET[\"ID\"];\n\necho \"&lt;h1&gt;You are searching for $a &lt;/h1&gt;\";\n\n$conn = new PDO (\"mysql:host=localhost;dbname=#;\", \"#\", \"#\");\n$results = $conn-&gt;query(\"select * from products where name='$a'\");\n\nif ($row=$results == 1) {\n    while ($row=$results-&gt;fetch()) {\n        echo \"&lt;p&gt;\";\n        echo \" Name \" . $row[\"name\"] . \"&lt;br/&gt; \";\n        echo \" Manufacturer \" .$row[\"manufacturer\"]. \"&lt;br/&gt;\";\n        echo \" Description \" .$row[\"description\"]. \"&lt;br/&gt;\";\n        echo \" Price \" .$row[\"price\"]. \"&lt;br/&gt;\";\n        echo \" Stock Level \" .$row[\"stocklevel\"]. \"&lt;br/&gt;\";\n        echo \" Age Limit \" .$row[\"agelimit\"]. \"&lt;br/&gt;\";\n        echo \"&lt;a href='quantity.php?ID=\" . $row[\"ID\"] . \"'&gt;Click here to buy more than one&lt;/a&gt;\";\n        echo \"&lt;a href='purchase.php?ID=\" . $row[\"ID\"] . \"'&gt;Click here to buy one&lt;/a&gt;\";\n        echo \"&lt;/p&gt;\";\n    }\n} else {\n    echo (\"There are no products matching your search terms!\");\n}\n?&gt;\n</code></pre>\n"
        }
    ],
    "has_more": true,
    "quota_max": 300,
    "quota_remaining": 143
}