{
    "items": [
        {
            "tags": [
                "arrays",
                "json",
                "node.js",
                "post",
                "request"
            ],
            "owner": {
                "reputation": 3,
                "user_id": 9561229,
                "user_type": "registered",
                "profile_image": "https://graph.facebook.com/1894524397285423/picture?type=large",
                "display_name": "Felipe Costa Goes",
                "link": "https://stackoverflow.com/users/9561229/felipe-costa-goes"
            },
            "is_answered": false,
            "view_count": 11,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524154399,
            "creation_date": 1524154399,
            "question_id": 49925700,
            "body_markdown": "I&#39;m facing a prolem with my APP, I&#39;m working with json data array and getting this json file from a site, this site need nonce() to complete each post request, the problem is that, sometimes the post request is so fast that one of them return invalid, follow part of the code:\r\n\r\n    var name_var = &#39;John&#39;;\r\n    \r\n    //Collecting all information about &#39;John&#39;\r\n    company.profiles(function (err, data) {\r\n        if (err) { console.log(&#39;ERROR&#39;, err); return; }\r\n            var len_openbalance = data.openbalanceInfo.length;\r\n            for (var i = 0; i &lt; len_openbalance; i++) {\r\n                   if (data.openbalanceInfo[i].ins === name_var) {\r\n                        x = i;\r\n             }\r\n        }\r\n        console.log(data.openbalanceInfo[x]); //Ok until here\r\n       \r\n       //The problem occurs here\r\n       data.openbalanceInfo[x].openDebts.forEach(function (item, index) {\r\n          app_GetAccountInfo().then(({ balance_available_one }) =&gt; {\r\n              if (balance_available_one &lt; item(&#39;Value&#39;) {\r\n                   console.log(name_var + &#39; have enough balance to pay&#39;);\r\n              }\r\n          });\r\n        //The first running app_GetAccountInfo() return ok\r\n        //The next, return parseFloat(debt_one[0][&#39;value&#39;]... undefined, the site not accept the post request, replying invalid session\r\n\r\n       });\r\n    });\r\n\r\n    function app_GetAccountInfo() {\r\n    return new Promise((resolve, reject) =&gt; { company.GetAccountInfo(function (err, data) {\r\n        if (err) { console.log(err); return; }\r\n        var debt_one = data.totalbalance.filter(function (item) {\r\n            return item.name === name_var;\r\n        });\r\n        var balance_available_one = parseFloat(balance_one[0][&#39;value&#39;]) - parseFloat(balance_one[0][&#39;date&#39;]);\r\n        resolve({ balance_available_one });\r\n        });\r\n    });\r\n    }\r\n\r\nI tried use the module delay without success.\r\n\r\nAny help will be welcome!\r\n",
            "link": "https://stackoverflow.com/questions/49925700/nodejs-simultaneous-post-http-with-json",
            "title": "Nodejs - simultaneous Post http with Json",
            "body": "<p>I'm facing a prolem with my APP, I'm working with json data array and getting this json file from a site, this site need nonce() to complete each post request, the problem is that, sometimes the post request is so fast that one of them return invalid, follow part of the code:</p>\n\n<pre><code>var name_var = 'John';\n\n//Collecting all information about 'John'\ncompany.profiles(function (err, data) {\n    if (err) { console.log('ERROR', err); return; }\n        var len_openbalance = data.openbalanceInfo.length;\n        for (var i = 0; i &lt; len_openbalance; i++) {\n               if (data.openbalanceInfo[i].ins === name_var) {\n                    x = i;\n         }\n    }\n    console.log(data.openbalanceInfo[x]); //Ok until here\n\n   //The problem occurs here\n   data.openbalanceInfo[x].openDebts.forEach(function (item, index) {\n      app_GetAccountInfo().then(({ balance_available_one }) =&gt; {\n          if (balance_available_one &lt; item('Value') {\n               console.log(name_var + ' have enough balance to pay');\n          }\n      });\n    //The first running app_GetAccountInfo() return ok\n    //The next, return parseFloat(debt_one[0]['value']... undefined, the site not accept the post request, replying invalid session\n\n   });\n});\n\nfunction app_GetAccountInfo() {\nreturn new Promise((resolve, reject) =&gt; { company.GetAccountInfo(function (err, data) {\n    if (err) { console.log(err); return; }\n    var debt_one = data.totalbalance.filter(function (item) {\n        return item.name === name_var;\n    });\n    var balance_available_one = parseFloat(balance_one[0]['value']) - parseFloat(balance_one[0]['date']);\n    resolve({ balance_available_one });\n    });\n});\n}\n</code></pre>\n\n<p>I tried use the module delay without success.</p>\n\n<p>Any help will be welcome!</p>\n"
        },
        {
            "tags": [
                "javascript"
            ],
            "owner": {
                "reputation": 66,
                "user_id": 8761117,
                "user_type": "registered",
                "accept_rate": 80,
                "profile_image": "https://www.gravatar.com/avatar/16acc432246d077441e7eeb7a2d116cb?s=128&d=identicon&r=PG&f=1",
                "display_name": "HowToGo",
                "link": "https://stackoverflow.com/users/8761117/howtogo"
            },
            "is_answered": true,
            "view_count": 32,
            "accepted_answer_id": 49925686,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524154368,
            "creation_date": 1524153223,
            "question_id": 49925330,
            "body_markdown": "I have been searching on how should `new Map();` be used and how to assign values from both to the object or return the object.\r\n\r\nI have found usage of `new Map();` on the MDN webdocs which is:\r\n\r\n&lt;!-- begin snippet: js hide: false console: true babel: false --&gt;\r\n\r\n&lt;!-- language: lang-js --&gt;\r\n\r\n    let myMap = new Map();\r\n\r\n    myMap.set(&#39;key&#39;, &#39;value&#39;);\r\n\r\n    console.log(myMap.get(&#39;key&#39;))\r\n\r\n&lt;!-- end snippet --&gt;\r\n\r\nI have found in one of the posts it can be used as follows as well:\r\n\r\n&lt;!-- begin snippet: js hide: false console: true babel: false --&gt;\r\n\r\n&lt;!-- language: lang-js --&gt;\r\n\r\n    let myMap = new Map();\r\n\r\n    myMap[&#39;key&#39;] = &#39;value&#39;;\r\n\r\n    console.log(myMap[&#39;key&#39;]);\r\n\r\n&lt;!-- end snippet --&gt;\r\n\r\nI have used `myMap[&#39;key&#39;]` way of of `new Map()` before but as i tried to return the map it seemed different.\r\n\r\nThis is example which shows difference between the two:\r\n&lt;!-- begin snippet: js hide: false console: true babel: false --&gt;\r\n\r\n&lt;!-- language: lang-js --&gt;\r\n\r\n    let myMap0 = new Map();\r\n\r\n    let myMap1 = new Map();\r\n\r\n    myMap0.set(&#39;key&#39;,&#39;value&#39;);\r\n\r\n    myMap1[&#39;key&#39;] = &#39;value&#39;;\r\n\r\n    console.log(myMap0);\r\n\r\n    console.log(myMap1);\r\n\r\n&lt;!-- end snippet --&gt;\r\n\r\nGiven example doesn&#39;t look alike in Google Chrome which is:\r\n[![enter image description here][1]][1]\r\n\r\n\r\n  [1]: https://i.stack.imgur.com/ztQmz.png\r\n\r\nOverall this is really confusing for me as i am unsure which way is the way it is supposed to be used.\r\n\r\nI got used to `myMap[&#39;key&#39;] = &#39;value&#39;;` as this is how it works in Golang.\r\n\r\nAdditionaly i have found more solutions to the `myMap.set(&#39;key&#39;, &#39;value&#39;);`way of usage.",
            "link": "https://stackoverflow.com/questions/49925330/setting-and-getting-values-from-map-in-javascript",
            "title": "Setting and getting values from map in JavaScript",
            "body": "<p>I have been searching on how should <code>new Map();</code> be used and how to assign values from both to the object or return the object.</p>\n\n<p>I have found usage of <code>new Map();</code> on the MDN webdocs which is:</p>\n\n<p><div class=\"snippet\" data-lang=\"js\" data-hide=\"false\" data-console=\"true\" data-babel=\"false\">\r\n<div class=\"snippet-code\">\r\n<pre class=\"snippet-code-js lang-js prettyprint-override\"><code>let myMap = new Map();\r\n\r\nmyMap.set('key', 'value');\r\n\r\nconsole.log(myMap.get('key'))</code></pre>\r\n</div>\r\n</div>\r\n</p>\n\n<p>I have found in one of the posts it can be used as follows as well:</p>\n\n<p><div class=\"snippet\" data-lang=\"js\" data-hide=\"false\" data-console=\"true\" data-babel=\"false\">\r\n<div class=\"snippet-code\">\r\n<pre class=\"snippet-code-js lang-js prettyprint-override\"><code>let myMap = new Map();\r\n\r\nmyMap['key'] = 'value';\r\n\r\nconsole.log(myMap['key']);</code></pre>\r\n</div>\r\n</div>\r\n</p>\n\n<p>I have used <code>myMap['key']</code> way of of <code>new Map()</code> before but as i tried to return the map it seemed different.</p>\n\n<p>This is example which shows difference between the two:\n<div class=\"snippet\" data-lang=\"js\" data-hide=\"false\" data-console=\"true\" data-babel=\"false\">\r\n<div class=\"snippet-code\">\r\n<pre class=\"snippet-code-js lang-js prettyprint-override\"><code>let myMap0 = new Map();\r\n\r\nlet myMap1 = new Map();\r\n\r\nmyMap0.set('key','value');\r\n\r\nmyMap1['key'] = 'value';\r\n\r\nconsole.log(myMap0);\r\n\r\nconsole.log(myMap1);</code></pre>\r\n</div>\r\n</div>\r\n</p>\n\n<p>Given example doesn't look alike in Google Chrome which is:\n<a href=\"https://i.stack.imgur.com/ztQmz.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/ztQmz.png\" alt=\"enter image description here\"></a></p>\n\n<p>Overall this is really confusing for me as i am unsure which way is the way it is supposed to be used.</p>\n\n<p>I got used to <code>myMap['key'] = 'value';</code> as this is how it works in Golang.</p>\n\n<p>Additionaly i have found more solutions to the <code>myMap.set('key', 'value');</code>way of usage.</p>\n"
        },
        {
            "tags": [
                "java",
                "mysql",
                "ssl"
            ],
            "owner": {
                "reputation": 575,
                "user_id": 3251199,
                "user_type": "registered",
                "accept_rate": 73,
                "profile_image": "https://www.gravatar.com/avatar/bf61d317161fc12eb6c9b74c546be321?s=128&d=identicon&r=PG&f=1",
                "display_name": "nicholas79171",
                "link": "https://stackoverflow.com/users/3251199/nicholas79171"
            },
            "is_answered": false,
            "view_count": 89,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524154358,
            "creation_date": 1516478673,
            "question_id": 48360555,
            "body_markdown": "I&#39;m trying to connect to my MySQL instance listening at `luther:3306`. I followed [these instructions](https://www.digitalocean.com/community/tutorials/how-to-configure-ssl-tls-for-mysql-on-ubuntu-16-04) on how to set up SSL for a MySQL instance on Ubuntu and it works great. I can connect to `luther:3306` with user `ford` no problem from the GUI (MySQL Workbench) when I provide it username, password, SSL key, SSL certificate, and SSL CA. \r\n\r\nNow, I&#39;m trying to connect via a Java app and I&#39;m having issues giving Java the correct certificate. Here&#39;s the code:\r\n\r\n    System.setProperty(&quot;javax.net.ssl.keyStore&quot;,&quot;C:/Program Files/Java/jre1.8.0_45/bin/cacerts&quot;);\r\n    System.setProperty(&quot;javax.net.ssl.keyStorePassword&quot;,&quot;changeit&quot;);\r\n    System.setProperty(&quot;javax.net.ssl.trustStore&quot;,&quot;C:/Program Files/Java/jre1.8.0_45/bin/cacerts&quot;);\r\n    System.setProperty(&quot;javax.net.ssl.trustStorePassword&quot;,&quot;changeit&quot;);\r\n    System.setProperty(&quot;javax.net.debug&quot;, &quot;SSL&quot;);\r\n    \r\n    // Create the DB connection\r\n    try {\r\n      String connectionUrl = &quot;jdbc:mysql://luther/ford&quot;;\r\n      Properties dbProps = new Properties();\r\n      dbProps.setProperty(&quot;user&quot;, &quot;ford&quot;);\r\n      dbProps.setProperty(&quot;password&quot;, &quot;&lt;password&gt;&quot;);\r\n      dbProps.setProperty(&quot;useSSL&quot;, &quot;true&quot;);\r\n      dbProps.setProperty(&quot;requreSSL&quot;, &quot;true&quot;);\r\n      \r\n      dbConnection = DriverManager.getConnection(connectionUrl, dbProps);\r\n      log.info(&quot;Connected to DB? &quot; + dbConnection.isValid(5000));\r\n    } catch (SQLException e) {\r\n      log.fatal(&quot;Unable to connect to DB!&quot;);\r\n      e.printStackTrace();\r\n      return;\r\n    }\r\n\r\nHere&#39;s the contents of the CA cert file: \r\n\r\n    C:\\Program Files\\Java\\jre1.8.0_45\\bin&gt;keytool -keystore cacerts -list\r\n    Enter keystore password:\r\n\r\n    Keystore type: JKS\r\n    Keystore provider: SUN\r\n\r\n    Your keystore contains 2 entries\r\n\r\n    mysqlcacert, Jan 20, 2018, trustedCertEntry,\r\n    Certificate fingerprint (SHA1): 71:92:DA:13:02:57:64:49:3D:72:A0:40:1B:B8:55:42:7D:21:0A:CF\r\n    mysqlclientcert, Jan 20, 2018, trustedCertEntry,\r\n    Certificate fingerprint (SHA1): A1:F5:5A:DB:31:78:D9:3C:F7:D7:C6:28:77:AB:DF:0A:58:CC:EA:A7\r\n\r\nIt shows that I have my CA cert and my Client cert. Here&#39;s the top level exception I get when I run my Java program:\r\n\r\n    javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\r\n      at sun.security.ssl.Alerts.getSSLException(Unknown Source)\r\n      at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)\r\n      at sun.security.ssl.Handshaker.fatalSE(Unknown Source)\r\n      at sun.security.ssl.Handshaker.fatalSE(Unknown Source)\r\n      at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)\r\n      at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)\r\n      at sun.security.ssl.Handshaker.processLoop(Unknown Source)\r\n      at sun.security.ssl.Handshaker.process_record(Unknown Source)\r\n      at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)\r\n      at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)\r\n      at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)\r\n      at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)\r\n      at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)\r\n      at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)\r\n      at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)\r\n      at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:512)\r\n      at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:493)\r\n      at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:205)\r\n      at org.jsoup.helper.HttpConnection.get(HttpConnection.java:194)\r\n\r\nDo I also somehow need to add my CA key or my client key to the keystore?",
            "link": "https://stackoverflow.com/questions/48360555/cant-connect-to-mysql-via-ssl-unable-to-find-valid-certification-path-to-reque",
            "title": "Can&#39;t Connect to MySQL via SSL (Unable to find valid certification path to requested target)",
            "body": "<p>I'm trying to connect to my MySQL instance listening at <code>luther:3306</code>. I followed <a href=\"https://www.digitalocean.com/community/tutorials/how-to-configure-ssl-tls-for-mysql-on-ubuntu-16-04\" rel=\"nofollow noreferrer\">these instructions</a> on how to set up SSL for a MySQL instance on Ubuntu and it works great. I can connect to <code>luther:3306</code> with user <code>ford</code> no problem from the GUI (MySQL Workbench) when I provide it username, password, SSL key, SSL certificate, and SSL CA. </p>\n\n<p>Now, I'm trying to connect via a Java app and I'm having issues giving Java the correct certificate. Here's the code:</p>\n\n<pre><code>System.setProperty(\"javax.net.ssl.keyStore\",\"C:/Program Files/Java/jre1.8.0_45/bin/cacerts\");\nSystem.setProperty(\"javax.net.ssl.keyStorePassword\",\"changeit\");\nSystem.setProperty(\"javax.net.ssl.trustStore\",\"C:/Program Files/Java/jre1.8.0_45/bin/cacerts\");\nSystem.setProperty(\"javax.net.ssl.trustStorePassword\",\"changeit\");\nSystem.setProperty(\"javax.net.debug\", \"SSL\");\n\n// Create the DB connection\ntry {\n  String connectionUrl = \"jdbc:mysql://luther/ford\";\n  Properties dbProps = new Properties();\n  dbProps.setProperty(\"user\", \"ford\");\n  dbProps.setProperty(\"password\", \"&lt;password&gt;\");\n  dbProps.setProperty(\"useSSL\", \"true\");\n  dbProps.setProperty(\"requreSSL\", \"true\");\n\n  dbConnection = DriverManager.getConnection(connectionUrl, dbProps);\n  log.info(\"Connected to DB? \" + dbConnection.isValid(5000));\n} catch (SQLException e) {\n  log.fatal(\"Unable to connect to DB!\");\n  e.printStackTrace();\n  return;\n}\n</code></pre>\n\n<p>Here's the contents of the CA cert file: </p>\n\n<pre><code>C:\\Program Files\\Java\\jre1.8.0_45\\bin&gt;keytool -keystore cacerts -list\nEnter keystore password:\n\nKeystore type: JKS\nKeystore provider: SUN\n\nYour keystore contains 2 entries\n\nmysqlcacert, Jan 20, 2018, trustedCertEntry,\nCertificate fingerprint (SHA1): 71:92:DA:13:02:57:64:49:3D:72:A0:40:1B:B8:55:42:7D:21:0A:CF\nmysqlclientcert, Jan 20, 2018, trustedCertEntry,\nCertificate fingerprint (SHA1): A1:F5:5A:DB:31:78:D9:3C:F7:D7:C6:28:77:AB:DF:0A:58:CC:EA:A7\n</code></pre>\n\n<p>It shows that I have my CA cert and my Client cert. Here's the top level exception I get when I run my Java program:</p>\n\n<pre><code>javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\n  at sun.security.ssl.Alerts.getSSLException(Unknown Source)\n  at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)\n  at sun.security.ssl.Handshaker.fatalSE(Unknown Source)\n  at sun.security.ssl.Handshaker.fatalSE(Unknown Source)\n  at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)\n  at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)\n  at sun.security.ssl.Handshaker.processLoop(Unknown Source)\n  at sun.security.ssl.Handshaker.process_record(Unknown Source)\n  at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)\n  at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)\n  at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)\n  at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)\n  at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)\n  at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)\n  at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)\n  at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:512)\n  at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:493)\n  at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:205)\n  at org.jsoup.helper.HttpConnection.get(HttpConnection.java:194)\n</code></pre>\n\n<p>Do I also somehow need to add my CA key or my client key to the keystore?</p>\n"
        },
        {
            "tags": [
                "java",
                "webdriver",
                "kill-process",
                "openprocess"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 8643086,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/2b8f4e3f0617fc77743c3ae50fed33df?s=128&d=identicon&r=PG&f=1",
                "display_name": "BHEEMARAJ UDAPUDI",
                "link": "https://stackoverflow.com/users/8643086/bheemaraj-udapudi"
            },
            "is_answered": false,
            "view_count": 19,
            "closed_date": 1524157161,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524154344,
            "creation_date": 1524151376,
            "last_edit_date": 1524154344,
            "question_id": 49924742,
            "body_markdown": "I am looking for easiest way to kill all browsers processes, driver instances and any open processes using Java. I tried driver.close() and driver.quit(). It did not help much when it is executed on virtual machines.",
            "link": "https://stackoverflow.com/questions/49924742/what-is-the-quick-way-to-kill-all-browsers-driver-instances-and-any-open-proces",
            "closed_reason": "too broad",
            "title": "What is the quick way to kill all browsers, driver instances and any open processes using Java code?",
            "body": "<p>I am looking for easiest way to kill all browsers processes, driver instances and any open processes using Java. I tried driver.close() and driver.quit(). It did not help much when it is executed on virtual machines.</p>\n"
        },
        {
            "tags": [
                "apache",
                "nginx"
            ],
            "owner": {
                "reputation": 10,
                "user_id": 7770185,
                "user_type": "registered",
                "profile_image": "https://lh4.googleusercontent.com/-EnYSwnzZ97E/AAAAAAAAAAI/AAAAAAAADu0/XbKU9FjubZo/photo.jpg?sz=128",
                "display_name": "Arnaud",
                "link": "https://stackoverflow.com/users/7770185/arnaud"
            },
            "is_answered": false,
            "view_count": 17,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524154335,
            "creation_date": 1524154335,
            "question_id": 49925682,
            "body_markdown": "I need have setup a nginx proxy for some Wordpress site under Apache and my nginx conf work only for 12 of my 15 sites.\r\n\r\nThis is the conf file I have for each sites :\r\n\r\n    server {\r\n        listen   80;\r\n        server_name domain.com www.exemple.com;\r\n        return 301 https://www.exemple.com;\r\n    }\r\n\r\n    server {\r\n        listen 443 ssl;\r\n        listen [::]:443 ssl;\r\n        server_name exemple.com www.exemple.com;\r\n\r\n        ssl on;\r\n        ssl_certificate /etc/letsencrypt/live/exemple.com/fullchain.pem;\r\n        ssl_certificate_key /etc/letsencrypt/live/exemple.com/privkey.pem;\r\n        ssl_stapling on;\r\n        ssl_stapling_verify on;\r\n        ssl_trusted_certificate \r\n        /etc/letsencrypt/live/exemple.com/fullchain.pem;\r\n\r\n        ssl_session_cache shared:SSL:100m;\r\n        ssl_session_timeout 24h;\r\n        ssl_session_tickets on;\r\n        ssl_session_ticket_key /etc/nginx/ssl/ticket.key;\r\n\r\n        ssl_dhparam /etc/nginx/ssl/dhparam4.pem;\r\n\r\n        ssl_ecdh_curve secp384r1;\r\n        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;\r\n        ssl_prefer_server_ciphers on;\r\n        ssl_ciphers [SOME CIPHERS]\r\n\r\n        location / {\r\n          proxy_set_header X-Original-Request $request_uri;\r\n          proxy_set_header X-Real-IP $remote_addr;\r\n          proxy_set_header Host $host;\r\n          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\r\n          proxy_set_header X-Forwarded-Proto https;\r\n          proxy_pass http://127.0.0.1:7080;\r\n        }\r\n    }\r\n\r\nAnd apache vhost: \r\n\r\n    &lt;VirtualHost *:7080&gt;\r\n        ServerName exemple.com\r\n        ServerAlias www.exemple.com\r\n\r\n        DocumentRoot /var/www/wp_domain\r\n\r\n        ErrorLog ${APACHE_LOG_DIR}/error.log\r\n        CustomLog ${APACHE_LOG_DIR}/access.log combined\r\n    &lt;/VirtualHost&gt;\r\n\r\nMy apache running on port 7080.\r\nI have tested just with an index.php and no htaccess on my apache webroot but not working too...\r\n\r\nI have not idea why just 3 of my sites not working.\r\n\r\nThanks for help",
            "link": "https://stackoverflow.com/questions/49925682/nginx-proxy-too-many-redirects-ssl-apache2",
            "title": "nginx proxy too many redirects SSL + Apache2",
            "body": "<p>I need have setup a nginx proxy for some Wordpress site under Apache and my nginx conf work only for 12 of my 15 sites.</p>\n\n<p>This is the conf file I have for each sites :</p>\n\n<pre><code>server {\n    listen   80;\n    server_name domain.com www.exemple.com;\n    return 301 https://www.exemple.com;\n}\n\nserver {\n    listen 443 ssl;\n    listen [::]:443 ssl;\n    server_name exemple.com www.exemple.com;\n\n    ssl on;\n    ssl_certificate /etc/letsencrypt/live/exemple.com/fullchain.pem;\n    ssl_certificate_key /etc/letsencrypt/live/exemple.com/privkey.pem;\n    ssl_stapling on;\n    ssl_stapling_verify on;\n    ssl_trusted_certificate \n    /etc/letsencrypt/live/exemple.com/fullchain.pem;\n\n    ssl_session_cache shared:SSL:100m;\n    ssl_session_timeout 24h;\n    ssl_session_tickets on;\n    ssl_session_ticket_key /etc/nginx/ssl/ticket.key;\n\n    ssl_dhparam /etc/nginx/ssl/dhparam4.pem;\n\n    ssl_ecdh_curve secp384r1;\n    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;\n    ssl_prefer_server_ciphers on;\n    ssl_ciphers [SOME CIPHERS]\n\n    location / {\n      proxy_set_header X-Original-Request $request_uri;\n      proxy_set_header X-Real-IP $remote_addr;\n      proxy_set_header Host $host;\n      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n      proxy_set_header X-Forwarded-Proto https;\n      proxy_pass http://127.0.0.1:7080;\n    }\n}\n</code></pre>\n\n<p>And apache vhost: </p>\n\n<pre><code>&lt;VirtualHost *:7080&gt;\n    ServerName exemple.com\n    ServerAlias www.exemple.com\n\n    DocumentRoot /var/www/wp_domain\n\n    ErrorLog ${APACHE_LOG_DIR}/error.log\n    CustomLog ${APACHE_LOG_DIR}/access.log combined\n&lt;/VirtualHost&gt;\n</code></pre>\n\n<p>My apache running on port 7080.\nI have tested just with an index.php and no htaccess on my apache webroot but not working too...</p>\n\n<p>I have not idea why just 3 of my sites not working.</p>\n\n<p>Thanks for help</p>\n"
        },
        {
            "tags": [
                "sql-server",
                "sqlcmd",
                "invoke-sqlcmd"
            ],
            "owner": {
                "reputation": 23,
                "user_id": 6325699,
                "user_type": "registered",
                "accept_rate": 40,
                "profile_image": "https://www.gravatar.com/avatar/943a697d5b7899f56da79006af4d8205?s=128&d=identicon&r=PG&f=1",
                "display_name": "a_m_2016",
                "link": "https://stackoverflow.com/users/6325699/a-m-2016"
            },
            "is_answered": false,
            "view_count": 17,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524154334,
            "creation_date": 1524153735,
            "last_edit_date": 1524154334,
            "question_id": 49925495,
            "body_markdown": "I&#39;m trying to make some changes to backup jobs on a server, I am wondering it&#39;s possible to create a variable and then subsequently call that in the script.\r\n\r\n    sqlcmd -E  -d master -Q &quot;DECLARE @CurrentDate VARCHAR(10);\r\n    SET @CurrentDate = FORMAT(GETDATE(), &#39;ddMMyyyy&#39;, &#39;en-us&#39;) SELECT \r\n    @CurrentDate&quot; -b\r\n\r\nI am basically wanting to create a string and use the @CurrentDate value created above. Not sure how this can be achieved, to be honest. ",
            "link": "https://stackoverflow.com/questions/49925495/assigning-vars-using-sqlcmd",
            "title": "Assigning vars using sqlcmd",
            "body": "<p>I'm trying to make some changes to backup jobs on a server, I am wondering it's possible to create a variable and then subsequently call that in the script.</p>\n\n<pre><code>sqlcmd -E  -d master -Q \"DECLARE @CurrentDate VARCHAR(10);\nSET @CurrentDate = FORMAT(GETDATE(), 'ddMMyyyy', 'en-us') SELECT \n@CurrentDate\" -b\n</code></pre>\n\n<p>I am basically wanting to create a string and use the @CurrentDate value created above. Not sure how this can be achieved, to be honest. </p>\n"
        },
        {
            "tags": [
                "angular",
                "angular-service-worker"
            ],
            "owner": {
                "reputation": 6,
                "user_id": 7135952,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/5256cee0d2f49e25647fe88726f6119d?s=128&d=identicon&r=PG&f=1",
                "display_name": "Coop501",
                "link": "https://stackoverflow.com/users/7135952/coop501"
            },
            "is_answered": false,
            "view_count": 8,
            "answer_count": 0,
            "score": 1,
            "last_activity_date": 1524154334,
            "creation_date": 1524154334,
            "question_id": 49925681,
            "body_markdown": "I have an angular application with a third party tool. I would like to intercept requests generated from the third party tool in order to modify  outgoing header parameters.\r\n\r\nI&#39;ve tried to use http interceptor, but unfortunately, it only intercepts requests outgoing from my own application.\r\n\r\nI&#39;m wondering would I be able to intercept all outgoing requests using a service worker in angular? If so, do I need to modify the code of ngsw-worker.js file or I should integrate my code somewhere else in the app?\r\n\r\nThank you!  ",
            "link": "https://stackoverflow.com/questions/49925681/modify-requests-header-using-service-worker-with-angular",
            "title": "Modify request&#39;s header using service worker with angular",
            "body": "<p>I have an angular application with a third party tool. I would like to intercept requests generated from the third party tool in order to modify  outgoing header parameters.</p>\n\n<p>I've tried to use http interceptor, but unfortunately, it only intercepts requests outgoing from my own application.</p>\n\n<p>I'm wondering would I be able to intercept all outgoing requests using a service worker in angular? If so, do I need to modify the code of ngsw-worker.js file or I should integrate my code somewhere else in the app?</p>\n\n<p>Thank you!  </p>\n"
        },
        {
            "tags": [
                "android",
                "listview",
                "filter"
            ],
            "owner": {
                "reputation": 468,
                "user_id": 3104599,
                "user_type": "registered",
                "profile_image": "https://i.stack.imgur.com/oRGuN.jpg?s=128&g=1",
                "display_name": "Hbibna",
                "link": "https://stackoverflow.com/users/3104599/hbibna"
            },
            "is_answered": true,
            "view_count": 1332,
            "accepted_answer_id": 27943077,
            "answer_count": 3,
            "score": 3,
            "last_activity_date": 1524154320,
            "creation_date": 1398012002,
            "last_edit_date": 1398012640,
            "question_id": 23184931,
            "body_markdown": "I have a listview which displays a list of contacts. I added an EditText to the layout above the listview so i can search using a Filter. I have implemented this using an onTextChanged Listener on the EditText. My listview adapter is a custom adapter which extends BaseAdapter and implements Filterable. My filter works and does the job correctly. The problem is, while i&#39;m typing, the dataset gets refreshed but the listview itself doesn&#39;t refresh until i hide the keyboard or press the return key. If i try to click on the listview after i enter some text into the EditText but before i close the keyboard or press return, I get this error : \r\n    \r\n    java.lang.IllegalStateException: The content of the adapter has changed \r\n    but ListView did not receive a notification. Make sure the content of \r\n    your adapter is not modified from a background thread, but only from the UI thread.\r\n\r\nNow i&#39;m definitely not modifying the content of the adapter from a thread other than the UI thread.\r\n\r\nCould anyone explain what might be causing this problem?\r\n\r\nActually, I&#39;ve found a workaround by calling &lt;code&gt;Activity.onContentChanged()&lt;/code&gt; but i&#39;m still curious as to why i actually need to refresh manually.",
            "link": "https://stackoverflow.com/questions/23184931/listview-with-filter-wont-refresh-until-keyboard-is-hidden-or-return-is-pressed",
            "title": "Listview with Filter won&#39;t refresh until keyboard is hidden or return is pressed",
            "body": "<p>I have a listview which displays a list of contacts. I added an EditText to the layout above the listview so i can search using a Filter. I have implemented this using an onTextChanged Listener on the EditText. My listview adapter is a custom adapter which extends BaseAdapter and implements Filterable. My filter works and does the job correctly. The problem is, while i'm typing, the dataset gets refreshed but the listview itself doesn't refresh until i hide the keyboard or press the return key. If i try to click on the listview after i enter some text into the EditText but before i close the keyboard or press return, I get this error : </p>\n\n<pre><code>java.lang.IllegalStateException: The content of the adapter has changed \nbut ListView did not receive a notification. Make sure the content of \nyour adapter is not modified from a background thread, but only from the UI thread.\n</code></pre>\n\n<p>Now i'm definitely not modifying the content of the adapter from a thread other than the UI thread.</p>\n\n<p>Could anyone explain what might be causing this problem?</p>\n\n<p>Actually, I've found a workaround by calling <code>Activity.onContentChanged()</code> but i'm still curious as to why i actually need to refresh manually.</p>\n"
        },
        {
            "tags": [
                "html",
                "web-scraping",
                "google-spreadsheet"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 9494727,
                "user_type": "registered",
                "profile_image": "https://lh3.googleusercontent.com/-t4BbU7096Fk/AAAAAAAAAAI/AAAAAAAAA74/gRXB0UuPmJ4/photo.jpg?sz=128",
                "display_name": "Potato Toddler",
                "link": "https://stackoverflow.com/users/9494727/potato-toddler"
            },
            "is_answered": true,
            "view_count": 23,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524154320,
            "creation_date": 1524144404,
            "last_edit_date": 1524154320,
            "question_id": 49922303,
            "body_markdown": "I&#39;m trying to import the table of teams at the World Cup into a Sheets file (https://en.wikipedia.org/wiki/2018_FIFA_World_Cup_qualification#Qualified_teams), but it keeps giving me an error. It says #ERROR! and when I hover over it it says:\r\n\r\n&gt; &quot;Formula Parse Error&quot;.\r\n\r\nI&#39;m using:\r\n    \r\n&lt;pre&gt;=importHTML(“https://en.wikipedia.org/wiki/2018_FIFA_World_Cup_qualification#Qualified_teams”,”table”,1)&lt;/pre&gt;",
            "link": "https://stackoverflow.com/questions/49922303/trying-to-import-a-table-from-wikipedia-into-google-sheets-not-working",
            "title": "Trying to import a table from Wikipedia into Google Sheets not working",
            "body": "<p>I'm trying to import the table of teams at the World Cup into a Sheets file (<a href=\"https://en.wikipedia.org/wiki/2018_FIFA_World_Cup_qualification#Qualified_teams\" rel=\"nofollow noreferrer\">https://en.wikipedia.org/wiki/2018_FIFA_World_Cup_qualification#Qualified_teams</a>), but it keeps giving me an error. It says #ERROR! and when I hover over it it says:</p>\n\n<blockquote>\n  <p>\"Formula Parse Error\".</p>\n</blockquote>\n\n<p>I'm using:</p>\n\n<pre>=importHTML(“https://en.wikipedia.org/wiki/2018_FIFA_World_Cup_qualification#Qualified_teams”,”table”,1)</pre>\n"
        },
        {
            "tags": [
                "javascript",
                "momentjs"
            ],
            "owner": {
                "reputation": 980,
                "user_id": 5561875,
                "user_type": "registered",
                "accept_rate": 72,
                "profile_image": "https://i.stack.imgur.com/T1ilq.jpg?s=128&g=1",
                "display_name": "Amit",
                "link": "https://stackoverflow.com/users/5561875/amit"
            },
            "is_answered": true,
            "view_count": 35,
            "accepted_answer_id": 49925675,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524154302,
            "creation_date": 1524153363,
            "question_id": 49925373,
            "body_markdown": "I have a large corpus of texts (18,000 paragraphs long), and I need to extract all of the dates from it.\r\nUnfortunately, dates show up in many forms, and I don&#39;t want to lose any form by doing a manual rule-based regex solution that catches most but not all dates.\r\n\r\nI started by getting all of the substrings for each paragraph, and trying to date parse them both with `Date.parse` and `moment`, but I was unlucky catching most.\r\n\r\nHere is an example of a date I couldn&#39;t parse automatically: `7th of april 2005`\r\n\r\n    Date.parse(&quot;7th of april 2005&quot;)\r\n\r\n&gt; NaN\r\n\r\n\r\nIs there an automatic way to determine if a string is a date?",
            "link": "https://stackoverflow.com/questions/49925373/javascript-is-string-a-valid-date-date-parse-doesnt-catch-it",
            "title": "Javascript - Is string a valid date? Date.parse doesn&#39;t catch it",
            "body": "<p>I have a large corpus of texts (18,000 paragraphs long), and I need to extract all of the dates from it.\nUnfortunately, dates show up in many forms, and I don't want to lose any form by doing a manual rule-based regex solution that catches most but not all dates.</p>\n\n<p>I started by getting all of the substrings for each paragraph, and trying to date parse them both with <code>Date.parse</code> and <code>moment</code>, but I was unlucky catching most.</p>\n\n<p>Here is an example of a date I couldn't parse automatically: <code>7th of april 2005</code></p>\n\n<pre><code>Date.parse(\"7th of april 2005\")\n</code></pre>\n\n<blockquote>\n  <p>NaN</p>\n</blockquote>\n\n<p>Is there an automatic way to determine if a string is a date?</p>\n"
        },
        {
            "tags": [
                "vim"
            ],
            "owner": {
                "reputation": 33,
                "user_id": 3743853,
                "user_type": "registered",
                "accept_rate": 50,
                "profile_image": "https://www.gravatar.com/avatar/a0d353ffc1fe9a37ffe7cabbe9ef83e4?s=128&d=identicon&r=PG&f=1",
                "display_name": "Nikhil",
                "link": "https://stackoverflow.com/users/3743853/nikhil"
            },
            "is_answered": true,
            "view_count": 25,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524154302,
            "creation_date": 1524149256,
            "last_edit_date": 1524151494,
            "question_id": 49923999,
            "body_markdown": "Vim newbie here.\r\nI use :find command to open a file and make some changes.\r\nSuppose I want to open another file without saving the current changes, then how should I do it.\r\nWhat is the best way to list all open files and quickly open them again for editing.\r\nThanks in advance.",
            "link": "https://stackoverflow.com/questions/49923999/find-file-in-vim-switch-to-next-file-without-saving-current-file",
            "title": "Find file in vim, switch to next file without saving current file",
            "body": "<p>Vim newbie here.\nI use :find command to open a file and make some changes.\nSuppose I want to open another file without saving the current changes, then how should I do it.\nWhat is the best way to list all open files and quickly open them again for editing.\nThanks in advance.</p>\n"
        },
        {
            "tags": [
                "mysql",
                "insert"
            ],
            "owner": {
                "reputation": 9,
                "user_id": 8893520,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/c54795c86344216978682667626b50ff?s=128&d=identicon&r=PG&f=1",
                "display_name": "Liam Broughton",
                "link": "https://stackoverflow.com/users/8893520/liam-broughton"
            },
            "is_answered": false,
            "view_count": 21,
            "answer_count": 2,
            "score": 1,
            "last_activity_date": 1524154291,
            "creation_date": 1524153380,
            "last_edit_date": 1524153667,
            "question_id": 49925380,
            "body_markdown": "I am new to MySQL (have just been using SQL Server) and I am wondering how to create multiple rows easily!\r\n\r\nI am looking to create about 300 rows, so the methods I have found online just don&#39;t seem practical enough..\r\n\r\nWhen using SQL Server, you can just use a GO statement, and then enter a number afterwards and it will run the command that many times, such as : GO 50\r\n\r\nIs there anything as simple as this on MySQL? I have read about using a loop statement, but I cannot find any info on it?\r\n\r\nAny help will be really appreciated!\r\n\r\nThanks,\r\n\r\n-Liam.",
            "link": "https://stackoverflow.com/questions/49925380/how-to-insert-multiple-rows-into-mysql",
            "title": "How to insert multiple rows into MySQL",
            "body": "<p>I am new to MySQL (have just been using SQL Server) and I am wondering how to create multiple rows easily!</p>\n\n<p>I am looking to create about 300 rows, so the methods I have found online just don't seem practical enough..</p>\n\n<p>When using SQL Server, you can just use a GO statement, and then enter a number afterwards and it will run the command that many times, such as : GO 50</p>\n\n<p>Is there anything as simple as this on MySQL? I have read about using a loop statement, but I cannot find any info on it?</p>\n\n<p>Any help will be really appreciated!</p>\n\n<p>Thanks,</p>\n\n<p>-Liam.</p>\n"
        },
        {
            "tags": [
                "python",
                "python-unittest"
            ],
            "owner": {
                "reputation": 562,
                "user_id": 5865514,
                "user_type": "registered",
                "accept_rate": 93,
                "profile_image": "https://graph.facebook.com/2998757368247/picture?type=large",
                "display_name": "Yu Chen",
                "link": "https://stackoverflow.com/users/5865514/yu-chen"
            },
            "is_answered": true,
            "view_count": 37,
            "accepted_answer_id": 49919362,
            "answer_count": 1,
            "score": 2,
            "last_activity_date": 1524154286,
            "creation_date": 1524064528,
            "last_edit_date": 1524154286,
            "question_id": 49903336,
            "body_markdown": "I&#39;ve written a bunch of tests for my Python application, but they&#39;ve suddenly appeared to no longer be working properly!\r\n\r\nI&#39;ve created a bunch of tests inside a `tests` module:\r\n\r\n\r\n[![enter image description here][1]][1]\r\n\r\n  [1]: https://i.stack.imgur.com/tcZr1.png\r\n\r\nInside of `tests.__main__.py`, I&#39;ve included the following code to load my test suite:\r\n\r\n    import unittest\r\n    \r\n    if __name__ == &quot;__main__&quot;:\r\n        loader = unittest.TestLoader()\r\n        start_dir = &quot;.&quot;\r\n        suite = loader.discover(start_dir=start_dir, pattern=&#39;*_test.py&#39;)\r\n    \r\n        runner = unittest.TextTestRunner()\r\n        runner.run(suite)\r\n\r\nI know I am going to sound like a complete noob, but these tests were working perfectly for me about an hour ago. I would issue them by typing `python3 -m tests` from my base directory. However, I&#39;m now receiving a really strange `TypeError`:\r\n\r\n    Traceback (most recent call last):\r\n      File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py&quot;, line 193, in _run_module_as_main\r\n        &quot;__main__&quot;, mod_spec)\r\n      File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py&quot;, line 85, in _run_code\r\n        exec(code, run_globals)\r\n      File &quot;/Users/yuchen/Desktop/myproj/myapp/tests/__main__.py&quot;, line 6, in &lt;module&gt;\r\n        suite = loader.discover(start_dir=start_dir, pattern=&#39;*_test.py&#39;)\r\n      File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py&quot;, line 341, in discover\r\n        tests = list(self._find_tests(start_dir, pattern))\r\n      File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py&quot;, line 406, in _find_tests\r\n        yield from self._find_tests(full_path, pattern, namespace)\r\n      File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py&quot;, line 406, in _find_tests\r\n        yield from self._find_tests(full_path, pattern, namespace)\r\n      File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py&quot;, line 398, in _find_tests\r\n        full_path, pattern, namespace)\r\n      File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py&quot;, line 452, in _find_test_path\r\n        return self.loadTestsFromModule(module, pattern=pattern), False\r\n      File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py&quot;, line 123, in loadTestsFromModule\r\n        tests.append(self.loadTestsFromTestCase(obj))\r\n      File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py&quot;, line 92, in loadTestsFromTestCase\r\n        loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))\r\n      File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/suite.py&quot;, line 24, in __init__\r\n        self.addTests(tests)\r\n      File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/suite.py&quot;, line 57, in addTests\r\n        for test in tests:\r\n    TypeError: __init__() takes 0 positional arguments but 2 were given\r\n\r\nI&#39;ve followed the stack trace down to what I believe is the appropriate file causing the issue, the `suite.py` file of `unittest`:\r\n\r\n    &quot;&quot;&quot;TestSuite&quot;&quot;&quot;\r\n      \r\n    import sys\r\n    \r\n    from . import case\r\n    from . import util\r\n    \r\n    __unittest = True\r\n    \r\n    \r\n    def _call_if_exists(parent, attr):\r\n        func = getattr(parent, attr, lambda: None)\r\n        func()\r\n    \r\n    \r\n    class BaseTestSuite(object):\r\n        &quot;&quot;&quot;A simple test suite that doesn&#39;t provide class or module shared fixtures.\r\n        &quot;&quot;&quot;\r\n        _cleanup = True\r\n    \r\n        def __init__(self, tests=()):\r\n            self._tests = []\r\n            self._removed_tests = 0\r\n            print(&quot;Tests&quot;, tests) # &lt;--- this was added by me\r\n            self.addTests(tests) \r\n\r\nHowever, the `__init__()` signature doesn&#39;t appear to require 0 positional arguments. Moreover, it&#39;s clearly executing, since after I added in `print(&quot;Tests&quot;, tests)` in the code above, I saw the following output before the error was thrown:\r\n\r\n    Tests: []\r\n    Tests: &lt;map object at 0x11033c0b8&gt;\r\n    Tests: &lt;map object at 0x11033c0b8&gt;\r\n    Tests: &lt;map object at 0x11033c0b8&gt;\r\n    Tests: [&lt;unittest.suite.TestSuite tests=[... a list of my tests]]\r\n    Tests: &lt;map object at 0x110483978&gt;\r\n    Tests: &lt;map object at 0x110483978&gt;\r\n    Traceback (most recent call last):\r\n\r\nI&#39;m pretty at a loss for what is going on. The error printed in the stack trace doesn&#39;t appear to correspond at all with what I&#39;m seeing in the source code.\r\n\r\n**Edit (Resolution):**\r\n\r\nThe accepted answer was spot on. I had written another test class, and decided to simply add in a stub for the `__init__` method:\r\n\r\n    class MyUnfinishedTest(BaseTest):\r\n    \r\n        def __init__():\r\n            pass\r\n\r\nThen I had forgotten about it and worked on other stuff, and ran the tests. That&#39;s when I started seeing my error. After removing this class from my test module, the tests ran smoothly.",
            "link": "https://stackoverflow.com/questions/49903336/python-unittest-loader-throws-typeerror-during-an-init-call",
            "title": "Python unittest loader throws TypeError during an __init__() call",
            "body": "<p>I've written a bunch of tests for my Python application, but they've suddenly appeared to no longer be working properly!</p>\n\n<p>I've created a bunch of tests inside a <code>tests</code> module:</p>\n\n<p><a href=\"https://i.stack.imgur.com/tcZr1.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/tcZr1.png\" alt=\"enter image description here\"></a></p>\n\n<p>Inside of <code>tests.__main__.py</code>, I've included the following code to load my test suite:</p>\n\n<pre><code>import unittest\n\nif __name__ == \"__main__\":\n    loader = unittest.TestLoader()\n    start_dir = \".\"\n    suite = loader.discover(start_dir=start_dir, pattern='*_test.py')\n\n    runner = unittest.TextTestRunner()\n    runner.run(suite)\n</code></pre>\n\n<p>I know I am going to sound like a complete noob, but these tests were working perfectly for me about an hour ago. I would issue them by typing <code>python3 -m tests</code> from my base directory. However, I'm now receiving a really strange <code>TypeError</code>:</p>\n\n<pre><code>Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/Users/yuchen/Desktop/myproj/myapp/tests/__main__.py\", line 6, in &lt;module&gt;\n    suite = loader.discover(start_dir=start_dir, pattern='*_test.py')\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py\", line 341, in discover\n    tests = list(self._find_tests(start_dir, pattern))\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py\", line 406, in _find_tests\n    yield from self._find_tests(full_path, pattern, namespace)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py\", line 406, in _find_tests\n    yield from self._find_tests(full_path, pattern, namespace)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py\", line 398, in _find_tests\n    full_path, pattern, namespace)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py\", line 452, in _find_test_path\n    return self.loadTestsFromModule(module, pattern=pattern), False\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py\", line 123, in loadTestsFromModule\n    tests.append(self.loadTestsFromTestCase(obj))\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py\", line 92, in loadTestsFromTestCase\n    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/suite.py\", line 24, in __init__\n    self.addTests(tests)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/suite.py\", line 57, in addTests\n    for test in tests:\nTypeError: __init__() takes 0 positional arguments but 2 were given\n</code></pre>\n\n<p>I've followed the stack trace down to what I believe is the appropriate file causing the issue, the <code>suite.py</code> file of <code>unittest</code>:</p>\n\n<pre><code>\"\"\"TestSuite\"\"\"\n\nimport sys\n\nfrom . import case\nfrom . import util\n\n__unittest = True\n\n\ndef _call_if_exists(parent, attr):\n    func = getattr(parent, attr, lambda: None)\n    func()\n\n\nclass BaseTestSuite(object):\n    \"\"\"A simple test suite that doesn't provide class or module shared fixtures.\n    \"\"\"\n    _cleanup = True\n\n    def __init__(self, tests=()):\n        self._tests = []\n        self._removed_tests = 0\n        print(\"Tests\", tests) # &lt;--- this was added by me\n        self.addTests(tests) \n</code></pre>\n\n<p>However, the <code>__init__()</code> signature doesn't appear to require 0 positional arguments. Moreover, it's clearly executing, since after I added in <code>print(\"Tests\", tests)</code> in the code above, I saw the following output before the error was thrown:</p>\n\n<pre><code>Tests: []\nTests: &lt;map object at 0x11033c0b8&gt;\nTests: &lt;map object at 0x11033c0b8&gt;\nTests: &lt;map object at 0x11033c0b8&gt;\nTests: [&lt;unittest.suite.TestSuite tests=[... a list of my tests]]\nTests: &lt;map object at 0x110483978&gt;\nTests: &lt;map object at 0x110483978&gt;\nTraceback (most recent call last):\n</code></pre>\n\n<p>I'm pretty at a loss for what is going on. The error printed in the stack trace doesn't appear to correspond at all with what I'm seeing in the source code.</p>\n\n<p><strong>Edit (Resolution):</strong></p>\n\n<p>The accepted answer was spot on. I had written another test class, and decided to simply add in a stub for the <code>__init__</code> method:</p>\n\n<pre><code>class MyUnfinishedTest(BaseTest):\n\n    def __init__():\n        pass\n</code></pre>\n\n<p>Then I had forgotten about it and worked on other stuff, and ran the tests. That's when I started seeing my error. After removing this class from my test module, the tests ran smoothly.</p>\n"
        },
        {
            "tags": [
                "scrapy"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 9670784,
                "user_type": "registered",
                "profile_image": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=128",
                "display_name": "熊志标",
                "link": "https://stackoverflow.com/users/9670784/%e7%86%8a%e5%bf%97%e6%a0%87"
            },
            "is_answered": false,
            "view_count": 11,
            "closed_date": 1524157883,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524154284,
            "creation_date": 1524154284,
            "question_id": 49925668,
            "body_markdown": "1. i want get kdj data from okex website\r\n2. okex office have not about get kdj data api,so i think i can use scrapy get it\r\n3. when i  refresh web , i can&#39;t get any data from chrome network tool , so i don&#39;t know how to get it\r\n4.OKEX address is: https://www.okex.com/market?product=ltc_btc\r\n5. this is manual get kdj step\r\n[enter image description here][1]\r\n\r\n\r\n  [1]: https://i.stack.imgur.com/pJDMt.png\r\n\r\nanyone can geive me some ideas thans!",
            "link": "https://stackoverflow.com/questions/49925668/scrapyget-kdj-from-okex",
            "closed_reason": "too broad",
            "title": "Scrapy:get kdj from okex",
            "body": "<ol>\n<li>i want get kdj data from okex website</li>\n<li>okex office have not about get kdj data api,so i think i can use scrapy get it</li>\n<li>when i  refresh web , i can't get any data from chrome network tool , so i don't know how to get it\n4.OKEX address is: <a href=\"https://www.okex.com/market?product=ltc_btc\" rel=\"nofollow noreferrer\">https://www.okex.com/market?product=ltc_btc</a></li>\n<li>this is manual get kdj step\n<a href=\"https://i.stack.imgur.com/pJDMt.png\" rel=\"nofollow noreferrer\">enter image description here</a></li>\n</ol>\n\n<p>anyone can geive me some ideas thans!</p>\n"
        },
        {
            "tags": [
                "python",
                "dask"
            ],
            "owner": {
                "reputation": 6,
                "user_id": 9670390,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/16bf8acaeb027cb144d5d8ad4d872839?s=128&d=identicon&r=PG&f=1",
                "display_name": "emitra17",
                "link": "https://stackoverflow.com/users/9670390/emitra17"
            },
            "is_answered": false,
            "view_count": 21,
            "answer_count": 1,
            "score": 1,
            "last_activity_date": 1524154284,
            "creation_date": 1524152573,
            "question_id": 49925130,
            "body_markdown": "I am using Dask to run a pool of tasks, retrieving results in the order they complete by the `as_completed` method, and potentially submitting new tasks to the pool each time one returns:\r\n\r\n&lt;!-- language: python --&gt;\r\n\r\n    # Initial set of jobs\r\n    futures = [client.submit(job.run_simulation) for job in jobs]\r\n    pool = as_completed(futures, with_results=True)\r\n\r\n    while True:\r\n        # Wait for a job to finish\r\n        f, result = next(pool)\r\n\r\n        # Exit condition\r\n        if result == &#39;STOP&#39;:\r\n            break\r\n        \r\n        # Do processing and maybe submit more jobs\r\n        more_jobs = process_result(f, result)\r\n        more_futures = [client.submit(job.run_simulation) for job in more_jobs]\r\n        pool.update(more_futures)\r\n\r\nHere&#39;s my problem: The function `job.run_simulation` that I am submitting can sometimes hang for a long time, and I want to time out this function - kill the task and move on if the run time exceeds a certain time limit.\r\n \r\nIdeally, I&#39;d like to do something like `client.submit(job.run_simulation, timeout=10)`, and have `next(pool)` return `None` if the task ran longer than the timeout. \r\n\r\nIs there any way that Dask can help me time out jobs like this?\r\n\r\n\r\n**What I&#39;ve tried so far**\r\n\r\nMy first instinct was to handle the timeout independently of Dask within the `job.run_simulation` function itself. I&#39;ve seen two types of suggestions (e.g. [here][1]) for generic Python timeouts. \r\n\r\n1) Use two threads, one for the function itself and one for a timer. My impression is this doesn&#39;t actually work because you can&#39;t kill threads. Even if the timer runs out, both threads have to finish before the task is completed. \r\n\r\n2) Use two separate processes (with the `multiprocessing` module), one for the function and one for the timer. This would work, but since I&#39;m already in a daemon subprocess spawned by Dask, I&#39;m not allowed to create new subprocesses.\r\n\r\nA third possibility is to move the code block to a separate script that I run with `subprocess.run` and use the `subprocess.run` built in timeout. I could do this, but it feels like a worst-case fallback scenario because it would take a lot of cumbersome passing of data to and from the subprocess.\r\n\r\nSo it feels like I have to accomplish the timeout at the level of Dask. My one idea here is to create a timer as a subprocess at the same time as I submit the task to Dask. Then if the timer runs out, use `Client.cancel()` to stop the task. The problem with this plan is that Dask might wait for workers to free up before starting the task, and I don&#39;t want the timer running before the task is actually running. \r\n\r\n\r\n  [1]: https://dreamix.eu/blog/webothers/timeout-function-in-python-3",
            "link": "https://stackoverflow.com/questions/49925130/how-do-i-time-out-a-job-submitted-to-dask",
            "title": "How do I time out a job submitted to Dask?",
            "body": "<p>I am using Dask to run a pool of tasks, retrieving results in the order they complete by the <code>as_completed</code> method, and potentially submitting new tasks to the pool each time one returns:</p>\n\n<pre class=\"lang-py prettyprint-override\"><code># Initial set of jobs\nfutures = [client.submit(job.run_simulation) for job in jobs]\npool = as_completed(futures, with_results=True)\n\nwhile True:\n    # Wait for a job to finish\n    f, result = next(pool)\n\n    # Exit condition\n    if result == 'STOP':\n        break\n\n    # Do processing and maybe submit more jobs\n    more_jobs = process_result(f, result)\n    more_futures = [client.submit(job.run_simulation) for job in more_jobs]\n    pool.update(more_futures)\n</code></pre>\n\n<p>Here's my problem: The function <code>job.run_simulation</code> that I am submitting can sometimes hang for a long time, and I want to time out this function - kill the task and move on if the run time exceeds a certain time limit.</p>\n\n<p>Ideally, I'd like to do something like <code>client.submit(job.run_simulation, timeout=10)</code>, and have <code>next(pool)</code> return <code>None</code> if the task ran longer than the timeout. </p>\n\n<p>Is there any way that Dask can help me time out jobs like this?</p>\n\n<p><strong>What I've tried so far</strong></p>\n\n<p>My first instinct was to handle the timeout independently of Dask within the <code>job.run_simulation</code> function itself. I've seen two types of suggestions (e.g. <a href=\"https://dreamix.eu/blog/webothers/timeout-function-in-python-3\" rel=\"nofollow noreferrer\">here</a>) for generic Python timeouts. </p>\n\n<p>1) Use two threads, one for the function itself and one for a timer. My impression is this doesn't actually work because you can't kill threads. Even if the timer runs out, both threads have to finish before the task is completed. </p>\n\n<p>2) Use two separate processes (with the <code>multiprocessing</code> module), one for the function and one for the timer. This would work, but since I'm already in a daemon subprocess spawned by Dask, I'm not allowed to create new subprocesses.</p>\n\n<p>A third possibility is to move the code block to a separate script that I run with <code>subprocess.run</code> and use the <code>subprocess.run</code> built in timeout. I could do this, but it feels like a worst-case fallback scenario because it would take a lot of cumbersome passing of data to and from the subprocess.</p>\n\n<p>So it feels like I have to accomplish the timeout at the level of Dask. My one idea here is to create a timer as a subprocess at the same time as I submit the task to Dask. Then if the timer runs out, use <code>Client.cancel()</code> to stop the task. The problem with this plan is that Dask might wait for workers to free up before starting the task, and I don't want the timer running before the task is actually running. </p>\n"
        },
        {
            "tags": [
                "netbeans"
            ],
            "owner": {
                "reputation": 47,
                "user_id": 1477701,
                "user_type": "registered",
                "accept_rate": 18,
                "profile_image": "https://www.gravatar.com/avatar/5e7449ae5c02049a656e7df3c35d8ac4?s=128&d=identicon&r=PG",
                "display_name": "user1477701",
                "link": "https://stackoverflow.com/users/1477701/user1477701"
            },
            "is_answered": true,
            "view_count": 8351,
            "answer_count": 2,
            "score": 4,
            "last_activity_date": 1524154273,
            "creation_date": 1393691709,
            "question_id": 22117076,
            "body_markdown": "I have a problem with Netbeans that whenever I create a new project I couldn&#39;t find the source tab and I found history tab only. View-&gt;Editors show history option only as well. I try to reinstall the Netbeans but the problem remains..\r\nCould anyone help?",
            "link": "https://stackoverflow.com/questions/22117076/netbeans-source-tab-disappears",
            "title": "Netbeans source tab disappears",
            "body": "<p>I have a problem with Netbeans that whenever I create a new project I couldn't find the source tab and I found history tab only. View->Editors show history option only as well. I try to reinstall the Netbeans but the problem remains..\nCould anyone help?</p>\n"
        },
        {
            "tags": [
                "excel",
                "vba",
                "excel-vba"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 8727460,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/c2ec711f4bc1f74d512c3eeb238daf71?s=128&d=identicon&r=PG&f=1",
                "display_name": "JPPedicino",
                "link": "https://stackoverflow.com/users/8727460/jppedicino"
            },
            "is_answered": true,
            "view_count": 19,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524154266,
            "creation_date": 1524151846,
            "question_id": 49924898,
            "body_markdown": "I have the following VBA code that will delete columns that are entirely blank. I would like to modify the code so that if a range below the first three rows (headers) is blank, then the entire column will be deleted. Can anyone assist please?\r\n\r\n    Sub DeleteBlankColumns()\r\n    &#39;Step1:  Declare your variables.\r\n        Dim MyRange As Range\r\n        Dim iCounter As Long\r\n    &#39;Step 2:  Define the target Range.\r\n        Set MyRange = ActiveSheet.UsedRange\r\n        \r\n    &#39;Step 3:  Start reverse looping through the range.\r\n        For iCounter = MyRange.Columns.Count To 1 Step -1\r\n        \r\n    &#39;Step 4: If entire column is empty then delete it.\r\n           If Application.CountA(Columns(iCounter).EntireColumn) = 0 Then\r\n           Columns(iCounter).Delete\r\n           End If\r\n    &#39;Step 5: Increment the counter down\r\n        Next iCounter\r\n    End Sub",
            "link": "https://stackoverflow.com/questions/49924898/delete-blank-or-empty-columns-use-excel-vba-less-headers",
            "title": "Delete Blank or Empty Columns Use Excel VBA Less Headers",
            "body": "<p>I have the following VBA code that will delete columns that are entirely blank. I would like to modify the code so that if a range below the first three rows (headers) is blank, then the entire column will be deleted. Can anyone assist please?</p>\n\n<pre><code>Sub DeleteBlankColumns()\n'Step1:  Declare your variables.\n    Dim MyRange As Range\n    Dim iCounter As Long\n'Step 2:  Define the target Range.\n    Set MyRange = ActiveSheet.UsedRange\n\n'Step 3:  Start reverse looping through the range.\n    For iCounter = MyRange.Columns.Count To 1 Step -1\n\n'Step 4: If entire column is empty then delete it.\n       If Application.CountA(Columns(iCounter).EntireColumn) = 0 Then\n       Columns(iCounter).Delete\n       End If\n'Step 5: Increment the counter down\n    Next iCounter\nEnd Sub\n</code></pre>\n"
        },
        {
            "tags": [
                "powershell",
                "iis"
            ],
            "owner": {
                "reputation": 749,
                "user_id": 3745837,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/4a462492366d754e692e54a80c6afe76?s=128&d=identicon&r=PG",
                "display_name": "BrettJ",
                "link": "https://stackoverflow.com/users/3745837/brettj"
            },
            "is_answered": false,
            "view_count": 174,
            "answer_count": 1,
            "score": 2,
            "last_activity_date": 1524154263,
            "creation_date": 1477920323,
            "last_edit_date": 1478013185,
            "question_id": 40343112,
            "body_markdown": "Does anyone know of a way to add a new root level &lt;location /&gt; element to the applicationHost.config file via the WebAdministration cmdlets?  There is Get-WebConfigurationLocation (and Remove and Rename versions of the cmdlet), but not an add.  I&#39;ve tried many different ways to do this using Add-WebConfiguration but I have not had any success.\r\n\r\nSome of the things I&#39;ve tried:\r\n  \r\n\r\n      Add-WebConfiguration -Filter &#39;/&#39; -AtIndex 0 -Value @{ location = @{ site=&#39;bobDev&#39; } }\r\n      Add-WebConfiguration -Filter &#39;/&#39; -AtIndex 0 -Value &#39;&lt;location site=&quot;bobDev&quot; /&gt;&#39;\r\n      Add-WebConfiguration -Filter &#39;/&#39; -AtIndex 0 -Value @{value=&quot;bobDev.html&quot; }\r\n\r\n\r\nI know that the Value&#39;s I&#39;m trying aren&#39;t probably correct, but I&#39;d at least like to see *something* get added into my applicationHost.config.",
            "link": "https://stackoverflow.com/questions/40343112/add-a-location-element-to-applicationhost-config-through-powershell",
            "title": "Add a &lt;location /&gt; element to applicationHost.config through PowerShell",
            "body": "<p>Does anyone know of a way to add a new root level  element to the applicationHost.config file via the WebAdministration cmdlets?  There is Get-WebConfigurationLocation (and Remove and Rename versions of the cmdlet), but not an add.  I've tried many different ways to do this using Add-WebConfiguration but I have not had any success.</p>\n\n<p>Some of the things I've tried:</p>\n\n<pre><code>  Add-WebConfiguration -Filter '/' -AtIndex 0 -Value @{ location = @{ site='bobDev' } }\n  Add-WebConfiguration -Filter '/' -AtIndex 0 -Value '&lt;location site=\"bobDev\" /&gt;'\n  Add-WebConfiguration -Filter '/' -AtIndex 0 -Value @{value=\"bobDev.html\" }\n</code></pre>\n\n<p>I know that the Value's I'm trying aren't probably correct, but I'd at least like to see <em>something</em> get added into my applicationHost.config.</p>\n"
        },
        {
            "tags": [
                "javascript",
                "ecmascript-6",
                "module"
            ],
            "owner": {
                "reputation": 148,
                "user_id": 5407319,
                "user_type": "registered",
                "accept_rate": 76,
                "profile_image": "https://www.gravatar.com/avatar/a2853ddc6b0140e204f7858960362af4?s=128&d=identicon&r=PG&f=1",
                "display_name": "interwebjill",
                "link": "https://stackoverflow.com/users/5407319/interwebjill"
            },
            "is_answered": true,
            "view_count": 31,
            "accepted_answer_id": 49888356,
            "answer_count": 3,
            "score": 0,
            "last_activity_date": 1524154260,
            "creation_date": 1523992491,
            "last_edit_date": 1524154260,
            "question_id": 49885861,
            "body_markdown": "I&#39;d like to create an array of the modules I am importing into `Main.js` file. How might I access the object that contains the imported modules?\r\n\r\n**EDIT** To further explain, I am importing multiple classes into a `Main.js` file containing a Main class. Each of these classes comes from their own individual file, giving me import statements like this:\r\n\r\n    import Header from &#39;./features/Header.js&#39;;\r\n    import ImageStrip from &#39;./features/ImageStrip.js&#39;;\r\n    import AreaChart from &#39;./features/AreaChart.js&#39;;\r\n    import Axes from &#39;./features/Axes.js&#39;;\r\n\r\nIs there a JavaScript object that contains the modules that are imported, for example something like `[ Header, ImageStrip, AreaChart, Axes ]`? Or is it possible to create one?",
            "link": "https://stackoverflow.com/questions/49885861/javascript-can-i-access-the-object-that-contains-imported-modules",
            "title": "JavaScript: can I access the object that contains imported modules?",
            "body": "<p>I'd like to create an array of the modules I am importing into <code>Main.js</code> file. How might I access the object that contains the imported modules?</p>\n\n<p><strong>EDIT</strong> To further explain, I am importing multiple classes into a <code>Main.js</code> file containing a Main class. Each of these classes comes from their own individual file, giving me import statements like this:</p>\n\n<pre><code>import Header from './features/Header.js';\nimport ImageStrip from './features/ImageStrip.js';\nimport AreaChart from './features/AreaChart.js';\nimport Axes from './features/Axes.js';\n</code></pre>\n\n<p>Is there a JavaScript object that contains the modules that are imported, for example something like <code>[ Header, ImageStrip, AreaChart, Axes ]</code>? Or is it possible to create one?</p>\n"
        },
        {
            "tags": [
                "tree",
                "binary-tree",
                "binary-search-tree",
                "binary-search",
                "b-tree"
            ],
            "owner": {
                "reputation": 5,
                "user_id": 7618290,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/b8e63b595a6d1eb730940848ea83c67d?s=128&d=identicon&r=PG&f=1",
                "display_name": "John Doe",
                "link": "https://stackoverflow.com/users/7618290/john-doe"
            },
            "is_answered": true,
            "view_count": 26,
            "accepted_answer_id": 49906564,
            "answer_count": 1,
            "score": -1,
            "last_activity_date": 1524154248,
            "creation_date": 1524074636,
            "last_edit_date": 1524154248,
            "question_id": 49906245,
            "body_markdown": "I have been doing some digging around Binary Tree and Binary Source Tree. Ran into this very fundamental question of the Tree (BT) and challenges the properties of a Binary Tree to be proven. \r\n\r\n***\r\nQuestion:  Given a node (the root), check if this is a valid Binary Tree. Not asking to validate if given BT is a BST, but simply asking to check if below is a BT. \r\n\r\n    Valid:\r\n      X1\r\n     /  \\\r\n    X4   X5\r\n     \\    \\\r\n      X3   X7\r\n\r\n    Invalid:\r\n      X1\r\n     /  \\\r\n    X4   X5\r\n     \\  /  \\\r\n      X3   X7\r\n\r\n\r\n    # A Python class that represents an individual node in a BT\r\n    class Node:\r\n        def __init__(self, key):\r\n            self.left = None\r\n            self.right = None\r\n            self.val = key \r\n\r\n        def isNotBinaryTree(root):\r\n            # code here\r\n\r\n    if isNotBinaryTree(root):\r\n       print &quot;True&quot;\r\n    else: \r\n       print &quot;False&quot;\r\n\r\n\r\n\r\nI do know this is NOT a binary tree (in fact, this is **not even** a tree by its definition and properties).\r\nThing is... how do I prove or validate this? Or how do I validate this is not a BT where x4 and x5 -&gt; x3 (multiple parent (nodes) point to a same child node? ***No data provided! What would the algorithm/logic look like if I were to solve this? (Python x.x preferred) \r\n\r\n",
            "link": "https://stackoverflow.com/questions/49906245/how-to-validate-a-binary-tree",
            "title": "How to validate a Binary Tree?",
            "body": "<p>I have been doing some digging around Binary Tree and Binary Source Tree. Ran into this very fundamental question of the Tree (BT) and challenges the properties of a Binary Tree to be proven. </p>\n\n<hr>\n\n<p>Question:  Given a node (the root), check if this is a valid Binary Tree. Not asking to validate if given BT is a BST, but simply asking to check if below is a BT. </p>\n\n<pre><code>Valid:\n  X1\n /  \\\nX4   X5\n \\    \\\n  X3   X7\n\nInvalid:\n  X1\n /  \\\nX4   X5\n \\  /  \\\n  X3   X7\n\n\n# A Python class that represents an individual node in a BT\nclass Node:\n    def __init__(self, key):\n        self.left = None\n        self.right = None\n        self.val = key \n\n    def isNotBinaryTree(root):\n        # code here\n\nif isNotBinaryTree(root):\n   print \"True\"\nelse: \n   print \"False\"\n</code></pre>\n\n<p>I do know this is NOT a binary tree (in fact, this is <strong>not even</strong> a tree by its definition and properties).\nThing is... how do I prove or validate this? Or how do I validate this is not a BT where x4 and x5 -> x3 (multiple parent (nodes) point to a same child node? ***No data provided! What would the algorithm/logic look like if I were to solve this? (Python x.x preferred) </p>\n"
        },
        {
            "tags": [
                "linux",
                "mongodb",
                "ssh"
            ],
            "owner": {
                "reputation": 547,
                "user_id": 9275906,
                "user_type": "registered",
                "accept_rate": 100,
                "profile_image": "https://www.gravatar.com/avatar/462703146b19371e48a5116fed4f23b5?s=128&d=identicon&r=PG&f=1",
                "display_name": "flik",
                "link": "https://stackoverflow.com/users/9275906/flik"
            },
            "is_answered": true,
            "view_count": 30,
            "accepted_answer_id": 49925658,
            "answer_count": 2,
            "score": 1,
            "last_activity_date": 1524154247,
            "creation_date": 1523434466,
            "question_id": 49769885,
            "body_markdown": "\r\nI can connect mongodb on my virtual machine but when I try to access it on Robo 3T. It is not connecting. \r\n\r\nI am using the same user and pass, It is working on ssh or putty but when I try to access db on ide Robo 3T, It is not working. ",
            "link": "https://stackoverflow.com/questions/49769885/mongodb-not-connecting-by-robo-3t",
            "title": "mongodb not connecting by Robo 3T?",
            "body": "<p>I can connect mongodb on my virtual machine but when I try to access it on Robo 3T. It is not connecting. </p>\n\n<p>I am using the same user and pass, It is working on ssh or putty but when I try to access db on ide Robo 3T, It is not working. </p>\n"
        },
        {
            "tags": [
                "ios",
                "swift"
            ],
            "owner": {
                "reputation": 403,
                "user_id": 1438045,
                "user_type": "registered",
                "accept_rate": 59,
                "profile_image": "https://www.gravatar.com/avatar/565aeb8f7f131b9495a7d810040be148?s=128&d=identicon&r=PG",
                "display_name": "Martin Massera",
                "link": "https://stackoverflow.com/users/1438045/martin-massera"
            },
            "is_answered": false,
            "view_count": 20,
            "answer_count": 0,
            "score": 1,
            "last_activity_date": 1524154246,
            "creation_date": 1524153004,
            "last_edit_date": 1524154246,
            "question_id": 49925250,
            "body_markdown": "I&#39;m trying to encrypt some files in my ios app in order to prevent someone with a jailbroken phone to have access to the contents of my app&#39;s files.\r\n\r\nI&#39;m using the `Encrypting Your App&#39;s Files` from Apple docs:\r\nhttps://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy/encrypting_your_app_s_files\r\n\r\nSo I&#39;m using this to write the file\r\n\r\n    let data = &quot;hello&quot;.data(using: .unicode)!\r\n    try! data.write(to: fileURL, options: .completeFileProtection)\r\n\r\nAccording to the docs, this option means: \r\n\r\n&gt; Complete. The file is accessible only when the device is unlocked.\r\n\r\nSo in the `AppDelegate` in the `applicationDidEnterBackground` method, I add this code that waits 5 seconds (to give time for the device to fully lock) and access the file:\r\n\r\n    Thread.sleep(forTimeInterval: 5.0)\r\n    let data = try! Data(contentsOf: fileURL)\r\n    print(String(data: data, encoding: .unicode)!)\r\n\r\nI tried this on the actual device, locked the phone, waited 5 seconds, and the data read OK! I was expecting the reading to fail.\r\n\r\nWhat am I missing?\r\n\r\nPS: does this method actually guarantee that a jailbroken device the file will be unreadable in the filesystem?",
            "link": "https://stackoverflow.com/questions/49925250/ios-not-enforcing-encryption-security-parameters",
            "title": "ios not enforcing encryption security parameters",
            "body": "<p>I'm trying to encrypt some files in my ios app in order to prevent someone with a jailbroken phone to have access to the contents of my app's files.</p>\n\n<p>I'm using the <code>Encrypting Your App's Files</code> from Apple docs:\n<a href=\"https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy/encrypting_your_app_s_files\" rel=\"nofollow noreferrer\">https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy/encrypting_your_app_s_files</a></p>\n\n<p>So I'm using this to write the file</p>\n\n<pre><code>let data = \"hello\".data(using: .unicode)!\ntry! data.write(to: fileURL, options: .completeFileProtection)\n</code></pre>\n\n<p>According to the docs, this option means: </p>\n\n<blockquote>\n  <p>Complete. The file is accessible only when the device is unlocked.</p>\n</blockquote>\n\n<p>So in the <code>AppDelegate</code> in the <code>applicationDidEnterBackground</code> method, I add this code that waits 5 seconds (to give time for the device to fully lock) and access the file:</p>\n\n<pre><code>Thread.sleep(forTimeInterval: 5.0)\nlet data = try! Data(contentsOf: fileURL)\nprint(String(data: data, encoding: .unicode)!)\n</code></pre>\n\n<p>I tried this on the actual device, locked the phone, waited 5 seconds, and the data read OK! I was expecting the reading to fail.</p>\n\n<p>What am I missing?</p>\n\n<p>PS: does this method actually guarantee that a jailbroken device the file will be unreadable in the filesystem?</p>\n"
        },
        {
            "tags": [
                "google-spreadsheet-api"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 9644267,
                "user_type": "registered",
                "profile_image": "https://lh3.googleusercontent.com/-ws4GctkWPR8/AAAAAAAAAAI/AAAAAAAABGw/_c3fMoEsjMY/photo.jpg?sz=128",
                "display_name": "Saichethan Reddy",
                "link": "https://stackoverflow.com/users/9644267/saichethan-reddy"
            },
            "is_answered": false,
            "view_count": 12,
            "answer_count": 1,
            "score": 1,
            "last_activity_date": 1524154231,
            "creation_date": 1524119120,
            "question_id": 49914085,
            "body_markdown": "We generally use databases to save and verify a user login information and authorization, how can we authorize an account from data on spreadsheet \r\n\r\ni.e verifying credentials input with data from database (spreadsheet) and authorize if data is found",
            "link": "https://stackoverflow.com/questions/49914085/authorization-from-google-spreadsheet",
            "title": "Authorization from Google Spreadsheet",
            "body": "<p>We generally use databases to save and verify a user login information and authorization, how can we authorize an account from data on spreadsheet </p>\n\n<p>i.e verifying credentials input with data from database (spreadsheet) and authorize if data is found</p>\n"
        },
        {
            "tags": [
                "facebook",
                "api",
                "facebook-graph-api",
                "checkin"
            ],
            "owner": {
                "reputation": 338,
                "user_id": 1282022,
                "user_type": "registered",
                "accept_rate": 84,
                "profile_image": "https://www.gravatar.com/avatar/189b46eb9c17d2e45bff3ea707f036e4?s=128&d=identicon&r=PG",
                "display_name": "Paweł Skaba",
                "link": "https://stackoverflow.com/users/1282022/pawe%c5%82-skaba"
            },
            "is_answered": true,
            "view_count": 4979,
            "closed_date": 1524206136,
            "accepted_answer_id": 26911316,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524154228,
            "creation_date": 1415888429,
            "last_edit_date": 1524154228,
            "question_id": 26911009,
            "body_markdown": "I&#39;m quite new to the FB API. In fact, I&#39;ve just started. In my simple page I wanted to show a block dedicated to users, who recently (let&#39;s say for last 7 days) checked on my place. Is there any chance to do it through graph api? i have found several maybe not similar topics here but still usually there were no tips/solutions. Mainly i&#39;ve found some issues with this concept. \r\n",
            "link": "https://stackoverflow.com/questions/26911009/facebook-graph-api-get-last-checked-users-to-place-page",
            "closed_reason": "too broad",
            "title": "facebook graph API - get last checked users to place/page",
            "body": "<p>I'm quite new to the FB API. In fact, I've just started. In my simple page I wanted to show a block dedicated to users, who recently (let's say for last 7 days) checked on my place. Is there any chance to do it through graph api? i have found several maybe not similar topics here but still usually there were no tips/solutions. Mainly i've found some issues with this concept. </p>\n"
        },
        {
            "tags": [
                "c#",
                "datatable",
                "sqlcommand"
            ],
            "owner": {
                "reputation": 26,
                "user_id": 8098080,
                "user_type": "registered",
                "accept_rate": 90,
                "profile_image": "https://www.gravatar.com/avatar/7c5443ac2a244df008b66c55997f4d9b?s=128&d=identicon&r=PG&f=1",
                "display_name": "W.Harr",
                "link": "https://stackoverflow.com/users/8098080/w-harr"
            },
            "is_answered": true,
            "view_count": 42,
            "accepted_answer_id": 49907375,
            "answer_count": 1,
            "score": 1,
            "last_activity_date": 1524154221,
            "creation_date": 1524077623,
            "last_edit_date": 1524154221,
            "question_id": 49907041,
            "body_markdown": "I&#39;m having issues with a stored procedure I&#39;m attempting to run from an ASP.NET console application.\r\n\r\nThis is how I&#39;m attempting to get the results in the code:\r\n\r\n    public static DataTable PerformStoredProcedure(int PracticeID, string CommandName)\r\n        {\r\n\r\n            DataTable dt = new DataTable();\r\n\r\n            try\r\n            {\r\n                using (SqlConnection conn = new SqlConnection(System.Configuration.ConfigurationManager.AppSettings[&quot;DbConnString&quot;].ToString()))\r\n                {\r\n                    conn.Open();\r\n\r\n                    using (SqlCommand cmd = conn.CreateCommand())\r\n                    {\r\n                        cmd.CommandType = CommandType.StoredProcedure;\r\n                        cmd.CommandText = CommandName;\r\n                        cmd.Parameters.AddWithValue(&quot;@practiceID&quot;, PracticeID);\r\n\r\n                        using (SqlDataAdapter da = new SqlDataAdapter(cmd))\r\n                        {\r\n                            da.Fill(dt);\r\n                        }\r\n                    }\r\n\r\n                    for (int i = 0; i &lt; dt.Rows.Count; i++)\r\n                    {\r\n                        for (int j = 0; j &lt; dt.Rows[i].ItemArray.Length; j++)\r\n                        {\r\n                            Console.Write(dt.Rows[i].ItemArray[j] + &quot;,&quot;);\r\n                        }\r\n                        Console.WriteLine();\r\n                    }\r\n                }\r\n            }\r\n\r\nAfter the procedure is run I get returned with a blank data set with no errors. However, when I run the procedure in SQL Server Management Studio I works just fine.\r\n\r\nYou may notice I don&#39;t use the `new SqlCommand()` constructor when initiating the `SqlCommand cmd`. That is because the query is enormous and takes a while to run so I figured it was a timeout issue.\r\n\r\nFollowing the suggestion [here][1], I made the following class in order to adjust the execution timeout limit.\r\n\r\n    class CommandFactory\r\n    {\r\n                public static int CommandTimeout\r\n                {\r\n                    get\r\n                    {\r\n                        int commandTimeout = 0;\r\n                        var configValue = ConfigurationManager.AppSettings[&quot;commandTimeout&quot;];\r\n\r\n                        if (int.TryParse(configValue, out commandTimeout))\r\n                            return commandTimeout;\r\n\r\n                        return 120;\r\n                    }\r\n                }\r\n\r\nFigured I&#39;d include that just to avoid confusion about whether the `SqlCommand` was being initialized correctly. After that adjustment, I began getting the issue where the command returns a blank data table. I assumed it could have to do with the minimum capacity of the data table `dt`, so I adjusted that as you can see in the original code.\r\n\r\nI&#39;ve done additional research and made the suggested fixes that are suggested to no avail:\r\n\r\n[1.][2] Set nocount on\r\n\r\n[2.][3] Use data adapter instead of data reader\r\n\r\n[3.][4] This is the most detailed answer. There are several suggestions made with in the forum but the eventual resolution has to do with views being used by the database as a default and blocking access to desired data. I have already confirmed with our DBA that we do not do this.\r\n\r\nLike I mentioned before, the query encompassed in the stored procedure is enormous and I haven&#39;t included it here because of its sheer size and because this post is long enough as it is. Again, I did confirm that the procedure is working in SSMS.\r\n\r\nI also haven&#39;t included an example result set because the data contains restricted information.\r\n\r\nI appreciate any help you can give.\r\n\r\nUPDATE:\r\n\r\nI added another method that calls a stored procedure to see if the problem was particular to the particular procedure being called. That second stored procedure also returned a blank data table so the problem is not specific to either procedure. (I also confirmed the second procedure was working and returning rows in SSMS)\r\n\r\nThat led me to believe there was something wrong with the app.config file for that project. I then added a third method that called a stored procedure on another project in the solution. However, even that returned a blank data table.\r\n\r\nFigured I&#39;d provide clues as I happen upon them.\r\n\r\n  [1]: https://stackoverflow.com/questions/25302038/how-to-set-sqlcommandtimeout-in-app-config\r\n  [2]: https://stackoverflow.com/questions/5511374/my-stored-procedure-returns-something-but-sqldataadapter-fill-leaves-datatable\r\n  [3]: https://www.codeproject.com/Questions/310286/Stored-Procedure-returns-Empty-table-to-DATAREADER\r\n  [4]: https://www.sqlservercentral.com/Forums/1497882/Works-in-Management-Studio-but-not-from-C?PageIndex=1",
            "link": "https://stackoverflow.com/questions/49907041/procedure-returning-blank-data-table-from-asp-net",
            "title": "Procedure Returning Blank Data Table from ASP.NET",
            "body": "<p>I'm having issues with a stored procedure I'm attempting to run from an ASP.NET console application.</p>\n\n<p>This is how I'm attempting to get the results in the code:</p>\n\n<pre><code>public static DataTable PerformStoredProcedure(int PracticeID, string CommandName)\n    {\n\n        DataTable dt = new DataTable();\n\n        try\n        {\n            using (SqlConnection conn = new SqlConnection(System.Configuration.ConfigurationManager.AppSettings[\"DbConnString\"].ToString()))\n            {\n                conn.Open();\n\n                using (SqlCommand cmd = conn.CreateCommand())\n                {\n                    cmd.CommandType = CommandType.StoredProcedure;\n                    cmd.CommandText = CommandName;\n                    cmd.Parameters.AddWithValue(\"@practiceID\", PracticeID);\n\n                    using (SqlDataAdapter da = new SqlDataAdapter(cmd))\n                    {\n                        da.Fill(dt);\n                    }\n                }\n\n                for (int i = 0; i &lt; dt.Rows.Count; i++)\n                {\n                    for (int j = 0; j &lt; dt.Rows[i].ItemArray.Length; j++)\n                    {\n                        Console.Write(dt.Rows[i].ItemArray[j] + \",\");\n                    }\n                    Console.WriteLine();\n                }\n            }\n        }\n</code></pre>\n\n<p>After the procedure is run I get returned with a blank data set with no errors. However, when I run the procedure in SQL Server Management Studio I works just fine.</p>\n\n<p>You may notice I don't use the <code>new SqlCommand()</code> constructor when initiating the <code>SqlCommand cmd</code>. That is because the query is enormous and takes a while to run so I figured it was a timeout issue.</p>\n\n<p>Following the suggestion <a href=\"https://stackoverflow.com/questions/25302038/how-to-set-sqlcommandtimeout-in-app-config\">here</a>, I made the following class in order to adjust the execution timeout limit.</p>\n\n<pre><code>class CommandFactory\n{\n            public static int CommandTimeout\n            {\n                get\n                {\n                    int commandTimeout = 0;\n                    var configValue = ConfigurationManager.AppSettings[\"commandTimeout\"];\n\n                    if (int.TryParse(configValue, out commandTimeout))\n                        return commandTimeout;\n\n                    return 120;\n                }\n            }\n</code></pre>\n\n<p>Figured I'd include that just to avoid confusion about whether the <code>SqlCommand</code> was being initialized correctly. After that adjustment, I began getting the issue where the command returns a blank data table. I assumed it could have to do with the minimum capacity of the data table <code>dt</code>, so I adjusted that as you can see in the original code.</p>\n\n<p>I've done additional research and made the suggested fixes that are suggested to no avail:</p>\n\n<p><a href=\"https://stackoverflow.com/questions/5511374/my-stored-procedure-returns-something-but-sqldataadapter-fill-leaves-datatable\">1.</a> Set nocount on</p>\n\n<p><a href=\"https://www.codeproject.com/Questions/310286/Stored-Procedure-returns-Empty-table-to-DATAREADER\" rel=\"nofollow noreferrer\">2.</a> Use data adapter instead of data reader</p>\n\n<p><a href=\"https://www.sqlservercentral.com/Forums/1497882/Works-in-Management-Studio-but-not-from-C?PageIndex=1\" rel=\"nofollow noreferrer\">3.</a> This is the most detailed answer. There are several suggestions made with in the forum but the eventual resolution has to do with views being used by the database as a default and blocking access to desired data. I have already confirmed with our DBA that we do not do this.</p>\n\n<p>Like I mentioned before, the query encompassed in the stored procedure is enormous and I haven't included it here because of its sheer size and because this post is long enough as it is. Again, I did confirm that the procedure is working in SSMS.</p>\n\n<p>I also haven't included an example result set because the data contains restricted information.</p>\n\n<p>I appreciate any help you can give.</p>\n\n<p>UPDATE:</p>\n\n<p>I added another method that calls a stored procedure to see if the problem was particular to the particular procedure being called. That second stored procedure also returned a blank data table so the problem is not specific to either procedure. (I also confirmed the second procedure was working and returning rows in SSMS)</p>\n\n<p>That led me to believe there was something wrong with the app.config file for that project. I then added a third method that called a stored procedure on another project in the solution. However, even that returned a blank data table.</p>\n\n<p>Figured I'd provide clues as I happen upon them.</p>\n"
        },
        {
            "tags": [
                "c",
                "file"
            ],
            "owner": {
                "reputation": 11,
                "user_id": 9665422,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/7c550c4452119cfc1c43240f31d1e678?s=128&d=identicon&r=PG&f=1",
                "display_name": "Robinson Crusoe",
                "link": "https://stackoverflow.com/users/9665422/robinson-crusoe"
            },
            "is_answered": false,
            "view_count": 74,
            "answer_count": 1,
            "score": 2,
            "last_activity_date": 1524154214,
            "creation_date": 1524069747,
            "last_edit_date": 1524079193,
            "question_id": 49904921,
            "body_markdown": "I had an assignment at school in C language in working with files. I have a file with .dat extension to modify using the following code. In the .dat file there are information about students (which have the Student struct). \r\n\r\nWith this code I have to add some points to one grade that the students have after I input a certain dept(class) number in the console.\r\n\r\n\r\n    #include &lt;stdio.h&gt;\r\n    \r\n    typedef struct { \r\n    \tint code; \r\n    \tchar name[30]; \r\n    \tint year; \r\n    \tint dept; \r\n    \tint number; \r\n    \tint grade[15]; \r\n    }Student;\r\n    \r\n    void main(){ \r\n    \tFILE * f; \r\n    \tchar s1[20]; \r\n    \tStudent s; \r\n    \tint n, i;\r\n    \tprintf(&quot;\\nFile: &quot;); \r\n    \tgets_s(s1);\r\n    \r\n    \tif(!(f = fopen(s1, &quot;rb+&quot;)))  printf(&quot;\\nThe file %s cannot be open&quot;, s1);\r\n    \telse{\r\n    \t\tprintf(&quot;\\nClass: &quot;); scanf(&quot;%d&quot;,&amp;n);\r\n    \t\twhile(!feof(stdin)){\r\n    \t\t\trewind(f);\r\n    \t\t\tfread(&amp;s, sizeof(Student), 1, f);\r\n    \t\t\ti = 0;\r\n    \t\t\twhile(!feof(f)){\r\n    \t\t\t\tif(n == s.dept){\r\n    \t\t\t\t\ti = 1;\r\n    \t\t\t\t\ts.grade[0] = (s.grade[0] == 10) ? s.grade[0] : s.grade[0] + 1;\r\n    \t\t\t\t\tfseek(f, ftell(f) - sizeof(Student), 0);\r\n    \t\t\t\t\tfwrite(&amp;s, sizeof(Student), 1, f);\r\n    \t\t\t\t\tfseek(f, 0, 1);\r\n    \t\t\t\t}\r\n    \t\t\t\tfread(&amp;s, sizeof(Student), 1, f);\r\n    \t\t\t}\r\n    \t\t\tif(!i) printf(&quot;\\n No student found in class %d&quot;, s.dept);\r\n    \t\t\tprintf(&quot;\\nClass: &quot;); scanf(&quot;%d&quot;,&amp;n);\r\n    \t\t}\r\n    \t\tfclose(f);\r\n    \t}\r\n    }\r\n\r\nAll good but in the console I get a strange dept number.\r\n\r\n\r\n    File: stud.dat\r\n    \r\n    Class: 200\r\n    \r\n     No student found in class -858993460\r\n\r\nI think this is happening because there is no conversion from binary to ascii. I searched the internet and I didn`t find anything that can help me. Is there a function I need to insert or something like this?\r\n\r\nThank you!\r\n\r\nstud.dat file\r\n\r\n    e   smith &#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;   1     \t      &#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;f   james &#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;   ,           &#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;g   mike &#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;   &#234;      \t   \r\n       &#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;h   jon &#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;&#254;   m         \r\n       &#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;&#204;",
            "link": "https://stackoverflow.com/questions/49904921/cant-do-the-conversion-from-binary-to-ascii-in-c-language",
            "title": "Can&#39;t do the conversion from binary to ascii in C language",
            "body": "<p>I had an assignment at school in C language in working with files. I have a file with .dat extension to modify using the following code. In the .dat file there are information about students (which have the Student struct). </p>\n\n<p>With this code I have to add some points to one grade that the students have after I input a certain dept(class) number in the console.</p>\n\n<pre><code>#include &lt;stdio.h&gt;\n\ntypedef struct { \n    int code; \n    char name[30]; \n    int year; \n    int dept; \n    int number; \n    int grade[15]; \n}Student;\n\nvoid main(){ \n    FILE * f; \n    char s1[20]; \n    Student s; \n    int n, i;\n    printf(\"\\nFile: \"); \n    gets_s(s1);\n\n    if(!(f = fopen(s1, \"rb+\")))  printf(\"\\nThe file %s cannot be open\", s1);\n    else{\n        printf(\"\\nClass: \"); scanf(\"%d\",&amp;n);\n        while(!feof(stdin)){\n            rewind(f);\n            fread(&amp;s, sizeof(Student), 1, f);\n            i = 0;\n            while(!feof(f)){\n                if(n == s.dept){\n                    i = 1;\n                    s.grade[0] = (s.grade[0] == 10) ? s.grade[0] : s.grade[0] + 1;\n                    fseek(f, ftell(f) - sizeof(Student), 0);\n                    fwrite(&amp;s, sizeof(Student), 1, f);\n                    fseek(f, 0, 1);\n                }\n                fread(&amp;s, sizeof(Student), 1, f);\n            }\n            if(!i) printf(\"\\n No student found in class %d\", s.dept);\n            printf(\"\\nClass: \"); scanf(\"%d\",&amp;n);\n        }\n        fclose(f);\n    }\n}\n</code></pre>\n\n<p>All good but in the console I get a strange dept number.</p>\n\n<pre><code>File: stud.dat\n\nClass: 200\n\n No student found in class -858993460\n</code></pre>\n\n<p>I think this is happening because there is no conversion from binary to ascii. I searched the internet and I didn`t find anything that can help me. Is there a function I need to insert or something like this?</p>\n\n<p>Thank you!</p>\n\n<p>stud.dat file</p>\n\n<pre><code>e   smith þþþþþþþþþþþþ   1            ÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌf   james þþþþþþþþþþþþ   ,           ÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌg   mike þþþþþþþþþþþ   ê            \n   ÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌh   jon þþþþþþþþþþþþþþþþ   m         \n   ÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌ\n</code></pre>\n"
        },
        {
            "tags": [
                "php",
                "sqlite",
                "pdo",
                "phpstorm",
                "driver"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 9670600,
                "user_type": "registered",
                "profile_image": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=128",
                "display_name": "Maksim Nessin",
                "link": "https://stackoverflow.com/users/9670600/maksim-nessin"
            },
            "is_answered": true,
            "view_count": 19,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524154187,
            "creation_date": 1524151795,
            "last_edit_date": 1524154187,
            "question_id": 49924878,
            "body_markdown": "I use PHPStorm to create a web page that saves data to a SQLite database. I have created tables in the DB, installed drivers in PHPStorm and it says, the connection is successful.\r\n\r\nOk, but when I try to open it in Chrome, it says:\n\n&gt; Fatal error: Uncaught PDOException: could not find driver in C:\\Users\\maness\\PhpstormProjects\\icd0007\\index.php:4 Stack trace: #0 C:\\Users\\maness\\PhpstormProjects\\icd0007\\index.php(4): PDO-&gt;__construct(&#39;jdbc:sqlite:db1...&#39;) #1 {main} thrown in C:\\Users\\maness\\PhpstormProjects\\icd0007\\index.php on line 4`\r\n\r\nThe code on line 4 within the index.php file is the following:\r\n \n    $connection = new PDO(&#39;jdbc:sqlite:db1.sqlite&#39;);\r\n\r\nI have turned on every SQL extension in php.ini, tried different options - no result. Can you name the exact extentions needed to launch SQLite, or what am I doing wrong?\r\n\r\nP.S\r\nPHPStorm SQLite Xerial drivers. I use PHP from XAMPP folder",
            "link": "https://stackoverflow.com/questions/49924878/could-not-find-pdo-driver-phpstorm-and-sqlite",
            "title": "Could not find PDO driver (PhpStorm and SQLite)",
            "body": "<p>I use PhpStorm to create a web page that saves data to a SQLite database. I have created tables in the DB, installed drivers in PhpStorm and it says, the connection is successful.</p>\n\n<p>Ok, but when I try to open it in Chrome, it says:</p>\n\n<blockquote>\n  <p>Fatal error: Uncaught PDOException: could not find driver in C:\\Users\\maness\\PhpstormProjects\\icd0007\\index.php:4 Stack trace: #0 C:\\Users\\maness\\PhpstormProjects\\icd0007\\index.php(4): PDO->__construct('jdbc:sqlite:db1...') #1 {main} thrown in C:\\Users\\maness\\PhpstormProjects\\icd0007\\index.php on line 4`</p>\n</blockquote>\n\n<p>The code on line 4 within the index.php file is the following:</p>\n\n<pre><code>$connection = new PDO('jdbc:sqlite:db1.sqlite');\n</code></pre>\n\n<p>I have turned on every SQL extension in php.ini, tried different options - no result. Can you name the exact extensions needed to launch SQLite, or what am I doing wrong?</p>\n\n<p>P.S. \nPhpStorm SQLite Xerial drivers. I use PHP from XAMPP folder.</p>\n"
        },
        {
            "tags": [
                "jquery",
                "html5",
                "css3",
                "sharepoint-2013"
            ],
            "owner": {
                "reputation": 121,
                "user_id": 2396605,
                "user_type": "registered",
                "accept_rate": 57,
                "profile_image": "https://i.stack.imgur.com/fqwba.jpg?s=128&g=1",
                "display_name": "Lowtrux",
                "link": "https://stackoverflow.com/users/2396605/lowtrux"
            },
            "is_answered": true,
            "view_count": 62,
            "bounty_amount": 50,
            "bounty_closes_date": 1524756699,
            "answer_count": 3,
            "score": 0,
            "last_activity_date": 1524154185,
            "creation_date": 1523866665,
            "question_id": 49852579,
            "body_markdown": "In order for you to understand why i can&#39;t cut and paste a lot of code here you need to know that this is a sharepoint app so my action field regarding customize css and specially html is kinda limited. This is the scenario: I have a series of tables that have dropdown menus in some of the TD&#39;s, all the tables have the overflow-x set to auto so the user can scroll horizontally if the table content is wider than the screen width. As you can see in the captures apparently the overflow-x auto is causing the dropdowns to get cutoff even when their z-index is bigger than the tables. I&#39;ve tried everything but can&#39;t get a solution.[![dropdown gets cutoff][1]][1]\r\n\r\nenter image description here\r\n\r\ndiv containing the table css:\r\n\r\n    .ms-webpart-zone.ms-fullWidth .ms-webpartzone-cell {\r\n       display: block;\r\n       overflow-x: auto;\r\n       overflow-y: visible;\r\n       min-height: 220px;\r\n       position: relative;\r\n       z-index: 10;\r\n    }\r\n\r\nDropdown css:\r\n\r\n    top: 10px;\r\n    position: absolute;\r\n    visibility: visible;\r\n    left: 88px;\r\n    width: 226px;\r\n\r\n\r\n[![enter image description here][2]][2]\r\n\r\n\r\n  [1]: https://i.stack.imgur.com/7nqRL.png\r\n  [2]: https://i.stack.imgur.com/NgIMt.png",
            "link": "https://stackoverflow.com/questions/49852579/dropdowns-get-cutoff-inside-table-with-overflow-x-auto",
            "title": "Dropdowns get cutoff inside table with overflow-x auto",
            "body": "<p>In order for you to understand why i can't cut and paste a lot of code here you need to know that this is a sharepoint app so my action field regarding customize css and specially html is kinda limited. This is the scenario: I have a series of tables that have dropdown menus in some of the TD's, all the tables have the overflow-x set to auto so the user can scroll horizontally if the table content is wider than the screen width. As you can see in the captures apparently the overflow-x auto is causing the dropdowns to get cutoff even when their z-index is bigger than the tables. I've tried everything but can't get a solution.<a href=\"https://i.stack.imgur.com/7nqRL.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/7nqRL.png\" alt=\"dropdown gets cutoff\"></a></p>\n\n<p>enter image description here</p>\n\n<p>div containing the table css:</p>\n\n<pre><code>.ms-webpart-zone.ms-fullWidth .ms-webpartzone-cell {\n   display: block;\n   overflow-x: auto;\n   overflow-y: visible;\n   min-height: 220px;\n   position: relative;\n   z-index: 10;\n}\n</code></pre>\n\n<p>Dropdown css:</p>\n\n<pre><code>top: 10px;\nposition: absolute;\nvisibility: visible;\nleft: 88px;\nwidth: 226px;\n</code></pre>\n\n<p><a href=\"https://i.stack.imgur.com/NgIMt.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/NgIMt.png\" alt=\"enter image description here\"></a></p>\n"
        },
        {
            "tags": [
                "c",
                "multithreading"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 8000783,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/d4fec443869fe1e2dd702ba3af859f7c?s=128&d=identicon&r=PG&f=1",
                "display_name": "Kate",
                "link": "https://stackoverflow.com/users/8000783/kate"
            },
            "is_answered": false,
            "view_count": 21,
            "answer_count": 0,
            "score": -4,
            "last_activity_date": 1524154174,
            "creation_date": 1524112642,
            "last_edit_date": 1524114568,
            "question_id": 49912827,
            "body_markdown": "I am trying to print odd and even elements from an array using pthreads but it seem to be not working properly. I am getting wrong output. Odd numbers are getting printed as even and even ones are getting printed as odd  sometimes.  I am guessing my use of condition variable is not correct. However, I am not able to figure out the exact cause. There are no compilation errors just the wrong output. \r\n\r\nThere are some links out there to print odd and even numbers\r\nhttps://stackoverflow.com/questions/29455170/c-threads-to-print-sequence-of-numbers-with-even-and-odd-number-printing-threa\r\n\r\nIt has to print from an array and I tried to build my logic using the same but that is not giving me the correct output.  \r\n\r\nThe command for compilation is \r\ngcc multithreading.c -lpthread -o m.out\r\n\r\n\r\n    #include &lt;pthread.h&gt;\r\n    #include &lt;stdio.h&gt;\r\n    #include &lt;stdlib.h&gt;\r\n    #include &lt;time.h&gt;\r\n    \r\n    pthread_mutex_t count_mutex = PTHREAD_MUTEX_INITIALIZER;\r\n    pthread_cond_t condition_var = PTHREAD_COND_INITIALIZER;\r\n    void *print_even();\r\n    void *print_odd();\r\n    int count = 0;\r\n    int size = 0;\r\n    \r\n    int main(int argc, char *argv[])\r\n    {\r\n      if(argc &lt; 1)\r\n    \texit(0);\r\n    \r\n      //initialize an array of the integers to be passed\r\n      int numSize = atoi(argv[1]); \r\n      srand(time(NULL));\r\n      int *nums = (int*)malloc((numSize - 1)*sizeof(int));\r\n      int i ;\r\n      for(i = 0; i &lt; numSize ; i++)\r\n      {\r\n        nums[i] = (rand() % 100) + i ;\r\n        printf(&quot;%d   &quot; , nums[i]);\r\n        size++;\r\n      }\r\n      printf(&quot;\\n&quot;);\r\n     \r\n      pthread_t even_thread;\r\n      pthread_t odd_thread;\r\n      pthread_create(&amp;even_thread, NULL, print_even , (void*)nums);\r\n      pthread_create(&amp;odd_thread, NULL, print_odd, (void*)nums);\r\n    \r\n      \r\n      pthread_join(even_thread, NULL); \r\n      pthread_join(odd_thread, NULL);\r\n      pthread_mutex_destroy(&amp;count_mutex);\r\n      pthread_cond_destroy(&amp;condition_var);\r\n      free(nums);\r\n    \r\n      return 0;\r\n    \r\n    }\r\n    \r\n    \r\n    // Print odd numbers\r\n    void *print_odd(void *arg)\r\n    {\r\n      int *arr_p = (int *)arg;\r\n      while(count &lt; size)\r\n      {\r\n       \t// Lock mutex and then wait for signal to relase mutex\r\n       \tpthread_mutex_lock( &amp;count_mutex );\r\n       \twhile( arr_p[count] % 2 != 0 ) \r\n       \t{ \r\n         \t\tpthread_cond_wait( &amp;condition_var, &amp;count_mutex );\r\n       \t}\r\n       \tcount++;\r\n    \tprintf(&quot;Array value print_odd: %d\\n&quot;,arr_p[count]);\r\n        pthread_mutex_unlock( &amp;count_mutex );\r\n       \tpthread_cond_signal( &amp;condition_var );\r\n      }\r\n      pthread_exit(0);\r\n    }\r\n    \r\n    \r\n    \r\n    // print even numbers\r\n    void *print_even(void *arg)\r\n    {\r\n      int *arr_p = (int*)arg;\r\n      while(count &lt; size)\r\n      {\r\n     \t // Lock mutex and then wait for signal to relase mutex\r\n      \tpthread_mutex_lock( &amp;count_mutex );\r\n      \twhile( arr_p[count] % 2 == 0 )\r\n    \t{\r\n        \t    pthread_cond_wait( &amp;condition_var, &amp;count_mutex );\r\n      \t}\r\n      \tcount++;\r\n      \tprintf(&quot;Array Value print_even: %d\\n&quot;, arr_p[count]);\r\n    \tpthread_mutex_unlock(&amp;count_mutex);\r\n      \tpthread_cond_signal( &amp;condition_var );\r\n      }\r\n      pthread_exit(0);\r\n    }\r\n\r\n\r\n    output: \r\n    2   62   61   20   91   28   63   74   30   13   64   69   64   108   105   \r\n    Array value print_odd: 62\r\n    Array value print_odd: 61\r\n    Array Value print_even: 20\r\n    Array value print_odd: 91\r\n    Array Value print_even: 28\r\n    Array value print_odd: 63\r\n    Array Value print_even: 74\r\n    Array value print_odd: 30\r\n    Array value print_odd: 13\r\n    Array Value print_even: 64\r\n    Array value print_odd: 69\r\n    Array Value print_even: 64\r\n    Array value print_odd: 108\r\n    Array value print_odd: 105\r\n    Array Value print_even: 0\r\n    Array value print_odd: 538976306\r\n\r\n",
            "link": "https://stackoverflow.com/questions/49912827/how-to-print-odd-and-even-numbers-from-an-array-using-pthreads",
            "title": "How to print odd and even numbers from an array using pthreads",
            "body": "<p>I am trying to print odd and even elements from an array using pthreads but it seem to be not working properly. I am getting wrong output. Odd numbers are getting printed as even and even ones are getting printed as odd  sometimes.  I am guessing my use of condition variable is not correct. However, I am not able to figure out the exact cause. There are no compilation errors just the wrong output. </p>\n\n<p>There are some links out there to print odd and even numbers\n<a href=\"https://stackoverflow.com/questions/29455170/c-threads-to-print-sequence-of-numbers-with-even-and-odd-number-printing-threa\">C Threads to print sequence of numbers : with even and odd number printing threads running parallely</a></p>\n\n<p>It has to print from an array and I tried to build my logic using the same but that is not giving me the correct output.  </p>\n\n<p>The command for compilation is \ngcc multithreading.c -lpthread -o m.out</p>\n\n<pre><code>#include &lt;pthread.h&gt;\n#include &lt;stdio.h&gt;\n#include &lt;stdlib.h&gt;\n#include &lt;time.h&gt;\n\npthread_mutex_t count_mutex = PTHREAD_MUTEX_INITIALIZER;\npthread_cond_t condition_var = PTHREAD_COND_INITIALIZER;\nvoid *print_even();\nvoid *print_odd();\nint count = 0;\nint size = 0;\n\nint main(int argc, char *argv[])\n{\n  if(argc &lt; 1)\n    exit(0);\n\n  //initialize an array of the integers to be passed\n  int numSize = atoi(argv[1]); \n  srand(time(NULL));\n  int *nums = (int*)malloc((numSize - 1)*sizeof(int));\n  int i ;\n  for(i = 0; i &lt; numSize ; i++)\n  {\n    nums[i] = (rand() % 100) + i ;\n    printf(\"%d   \" , nums[i]);\n    size++;\n  }\n  printf(\"\\n\");\n\n  pthread_t even_thread;\n  pthread_t odd_thread;\n  pthread_create(&amp;even_thread, NULL, print_even , (void*)nums);\n  pthread_create(&amp;odd_thread, NULL, print_odd, (void*)nums);\n\n\n  pthread_join(even_thread, NULL); \n  pthread_join(odd_thread, NULL);\n  pthread_mutex_destroy(&amp;count_mutex);\n  pthread_cond_destroy(&amp;condition_var);\n  free(nums);\n\n  return 0;\n\n}\n\n\n// Print odd numbers\nvoid *print_odd(void *arg)\n{\n  int *arr_p = (int *)arg;\n  while(count &lt; size)\n  {\n    // Lock mutex and then wait for signal to relase mutex\n    pthread_mutex_lock( &amp;count_mutex );\n    while( arr_p[count] % 2 != 0 ) \n    { \n            pthread_cond_wait( &amp;condition_var, &amp;count_mutex );\n    }\n    count++;\n    printf(\"Array value print_odd: %d\\n\",arr_p[count]);\n    pthread_mutex_unlock( &amp;count_mutex );\n    pthread_cond_signal( &amp;condition_var );\n  }\n  pthread_exit(0);\n}\n\n\n\n// print even numbers\nvoid *print_even(void *arg)\n{\n  int *arr_p = (int*)arg;\n  while(count &lt; size)\n  {\n     // Lock mutex and then wait for signal to relase mutex\n    pthread_mutex_lock( &amp;count_mutex );\n    while( arr_p[count] % 2 == 0 )\n    {\n            pthread_cond_wait( &amp;condition_var, &amp;count_mutex );\n    }\n    count++;\n    printf(\"Array Value print_even: %d\\n\", arr_p[count]);\n    pthread_mutex_unlock(&amp;count_mutex);\n    pthread_cond_signal( &amp;condition_var );\n  }\n  pthread_exit(0);\n}\n\n\noutput: \n2   62   61   20   91   28   63   74   30   13   64   69   64   108   105   \nArray value print_odd: 62\nArray value print_odd: 61\nArray Value print_even: 20\nArray value print_odd: 91\nArray Value print_even: 28\nArray value print_odd: 63\nArray Value print_even: 74\nArray value print_odd: 30\nArray value print_odd: 13\nArray Value print_even: 64\nArray value print_odd: 69\nArray Value print_even: 64\nArray value print_odd: 108\nArray value print_odd: 105\nArray Value print_even: 0\nArray value print_odd: 538976306\n</code></pre>\n"
        },
        {
            "tags": [
                "python",
                "beautifulsoup"
            ],
            "owner": {
                "reputation": 49,
                "user_id": 3375720,
                "user_type": "registered",
                "accept_rate": 100,
                "profile_image": "https://i.stack.imgur.com/3WbGC.jpg?s=128&g=1",
                "display_name": "Bob Glidewell",
                "link": "https://stackoverflow.com/users/3375720/bob-glidewell"
            },
            "is_answered": false,
            "view_count": 36,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524154161,
            "creation_date": 1524153682,
            "last_edit_date": 1524153975,
            "question_id": 49925471,
            "body_markdown": "I am required to change the xkcd project in the AtBS book to download the comics from a different website. Here is my script.\r\n\r\n    #! python3\r\n    # getwebcomic.py - Downloads every single smbc comic.\r\n\r\n    import requests, os, bs4\r\n\r\n    os.chdir(&#39;C:\\\\Users\\\\Bob\\\\Desktop\\\\&#39;)\r\n    url = &#39;https://smbc-comics.com&#39; # starting url\r\n    os.makedirs(&#39;smbc&#39;, exist_ok=True) # store comics in ./smbc\r\n    noAbuse=0\r\n\r\n    for noAbuse in range(0, 5):\r\n    #while not url.endswith(&#39;#&#39;):\r\n        # Download the page.\r\n        print(&#39;Downloading page %s...&#39; % url)\r\n        res = requests.get(url)\r\n        res.raise_for_status()\r\n\r\n        soup = bs4.BeautifulSoup(res.text, &quot;html.parser&quot;)\r\n\r\n        # Find the URL of the comic image.\r\n        comicElem = soup.select(&#39;#cc-comicbody&#39;)\r\n        print(&#39;I am finding it&#39;)\r\n        print(comicElem)\r\n        if comicElem == []:\r\n            print(&#39;Could not find comic image.&#39;)\r\n        else:\r\n            print(comicElem[0].get(&#39;src&#39;))\r\n            print(&#39;I dont know why the .get is returning NONE!&#39;)\r\n            print(&#39;It is there???&#39;)\r\n            print(&#39;...and now it crashes&#39;)\r\n            comicUrl = &#39;https//smbc-comics.com&#39; + comicElem[0].get(&#39;src&#39;)\r\n            print(comicUrl)\r\n            # Download the image.\r\n\r\n            print(&#39;Downloading image %s...&#39; % (comicUrl))\r\n            res = requests.get(comicUrl)\r\n            res.raise_for_status()\r\n\r\n            # Save the image to ./smbc\r\n            imageFile = open(os.path.join(&#39;smbc&#39;, os.path.basename(comicUrl)), \r\n    &#39;wb&#39;)\r\n           for chunk in res.iter_content(100000):\r\n                imageFile.write(chunk)\r\n            imageFile.close()\r\n  \r\n        # Get the Prev button&#39;s url.\r\n       prevLink = soup.select(&#39;a[rel=&quot;prev&quot;]&#39;)[0]\r\n       url = &#39;http://smbc-comic.com&#39; + prevLink.get(&#39;href&#39;)\r\n\r\n    print(&#39;Done.&#39;)\r\n\r\n***OutPut***\r\n\r\n    Downloading page https://smbc-comics.com...\r\n\r\n    I am finding it\r\n    [&lt;div id=&quot;cc-comicbody&quot;&gt;&lt;img border=&quot;0&quot; id=&quot;cc-comic&quot; \r\n     src=&quot;/comics/1524150658-20170419 (1).png&quot; \r\n     title=&quot;You can also just use an infinite quantity of compasses as on-off switches.&quot;/&gt;&lt;br/&gt;&lt;/div&gt;]\r\n    None\r\n\r\nI dont know why the `.get` is returning NONE!\r\nIt is there???\r\n...and now it crashes\r\n\r\n&gt;Traceback (most recent call last):&lt;br&gt;\r\n  File &quot;C:\\Users\\Bob\\PythonScripts\\getwebcomic.py&quot;, line 31, in &amp;lt;module&gt;&lt;br&gt;\r\n    comicUrl = &#39;https//smbc-comics.com&#39; + comicElem[0].get(&#39;src&#39;)&lt;br&gt;\r\nTypeError: must be str, not NoneType\r\n\r\nI can&#39;t seem to figure out why the .get method is returning none when the &#39;src&#39; attribute is there. Any hints would be appreciated. I put in some extra print() to help me see what is happening when the script runs. \r\n  ",
            "link": "https://stackoverflow.com/questions/49925471/my-script-is-not-retrieving-an-item-for-a-list-i-would-appreciate-it-if-someon",
            "title": "My script is not retrieving an item for a list. I would appreciate it, if someone could help me understand why?",
            "body": "<p>I am required to change the xkcd project in the AtBS book to download the comics from a different website. Here is my script.</p>\n\n<pre><code>#! python3\n# getwebcomic.py - Downloads every single smbc comic.\n\nimport requests, os, bs4\n\nos.chdir('C:\\\\Users\\\\Bob\\\\Desktop\\\\')\nurl = 'https://smbc-comics.com' # starting url\nos.makedirs('smbc', exist_ok=True) # store comics in ./smbc\nnoAbuse=0\n\nfor noAbuse in range(0, 5):\n#while not url.endswith('#'):\n    # Download the page.\n    print('Downloading page %s...' % url)\n    res = requests.get(url)\n    res.raise_for_status()\n\n    soup = bs4.BeautifulSoup(res.text, \"html.parser\")\n\n    # Find the URL of the comic image.\n    comicElem = soup.select('#cc-comicbody')\n    print('I am finding it')\n    print(comicElem)\n    if comicElem == []:\n        print('Could not find comic image.')\n    else:\n        print(comicElem[0].get('src'))\n        print('I dont know why the .get is returning NONE!')\n        print('It is there???')\n        print('...and now it crashes')\n        comicUrl = 'https//smbc-comics.com' + comicElem[0].get('src')\n        print(comicUrl)\n        # Download the image.\n\n        print('Downloading image %s...' % (comicUrl))\n        res = requests.get(comicUrl)\n        res.raise_for_status()\n\n        # Save the image to ./smbc\n        imageFile = open(os.path.join('smbc', os.path.basename(comicUrl)), \n'wb')\n       for chunk in res.iter_content(100000):\n            imageFile.write(chunk)\n        imageFile.close()\n\n    # Get the Prev button's url.\n   prevLink = soup.select('a[rel=\"prev\"]')[0]\n   url = 'http://smbc-comic.com' + prevLink.get('href')\n\nprint('Done.')\n</code></pre>\n\n<p><strong><em>OutPut</em></strong></p>\n\n<pre><code>Downloading page https://smbc-comics.com...\n\nI am finding it\n[&lt;div id=\"cc-comicbody\"&gt;&lt;img border=\"0\" id=\"cc-comic\" \n src=\"/comics/1524150658-20170419 (1).png\" \n title=\"You can also just use an infinite quantity of compasses as on-off switches.\"/&gt;&lt;br/&gt;&lt;/div&gt;]\nNone\n</code></pre>\n\n<p>I dont know why the <code>.get</code> is returning NONE!\nIt is there???\n...and now it crashes</p>\n\n<blockquote>\n  <p>Traceback (most recent call last):<br>\n    File \"C:\\Users\\Bob\\PythonScripts\\getwebcomic.py\", line 31, in &lt;module><br>\n      comicUrl = 'https//smbc-comics.com' + comicElem[0].get('src')<br>\n  TypeError: must be str, not NoneType</p>\n</blockquote>\n\n<p>I can't seem to figure out why the .get method is returning none when the 'src' attribute is there. Any hints would be appreciated. I put in some extra print() to help me see what is happening when the script runs. </p>\n"
        }
    ],
    "has_more": true,
    "quota_max": 300,
    "quota_remaining": 39
}